import type { OperationsCopy } from "../operations-copy";
const copy = {
  tokensAtLeast: "至少 {count}",
  tokenUsageUnknown: "Token 用量未知",
  tokenCoveragePartial: "部分调用未报告 Token 用量；总数仅表示已知下限。",
  noRecordedUsage: "此时间段内没有用量记录。",
  recoveryTitle: "需要检查已保存的核对决定",
  recoveryHelp:
    "此标签页为本项目保留一项结果未确认的决定，即使它已超出历史记录范围。刷新标签页会保留它；关闭标签页或更换设备可能不会。",
  reviewSaved: "检查已保存的决定",
  recoveryDamaged:
    "无法安全读取已保存的决定。清除前请检查本地数据；不会根据此数据发送请求。",
  clearRecovery: "清除本地恢复记录",
  clearRecoveryHelp:
    "我理解清除此本地副本不会取消或更改服务器上的操作。我已保留所需证据，并将在做出新决定前检查外部结果。",
  recoveryChanged: "本地记录已更改或无法清除。请重新检查。",
  recoveryStorage:
    "浏览器存储不可用。无法验证或清除已保存的决定。恢复存储后请重新检查。",
  draftStorage:
    "浏览器存储不可用。文本保留在此处；未发送任何内容。恢复存储后请再次尝试保存。",
  recoveryBlocked:
    "需要检查另一项已保存的决定或损坏的本地数据。发送前请关闭此对话框并检查恢复面板。",
  damagedDraft: "无法安全读取此已保存的草稿。其原始本地内容显示在下方。",
  discardDraftHelp: "我已检查并保留所需文本。仅删除此尚未发送的本地草稿。",
  discardDraft: "删除损坏的草稿",
  recordedAudit: "服务器原始审计记录",
  acknowledgeRecord: "确认已查看记录的决定",
  noteBytes: "{used} / {limit} 字节",
  fleetTitle: "运行中心",
  fleetEyebrow: "AgenticOS 进程总览",
  command: "系统状态",
  fleetHelp:
    "查看工作进程信号、持久队列和操作凭据。健康样本反映过去 24 小时的记录覆盖情况。",
  projects: "前往项目",
  backProjects: "返回项目",
  studio: "项目工作室",
  refresh: "刷新",
  retry: "重试",
  cursor: "记录游标：{id}",
  projectId: "项目 #{id}",
  snapshot: "上次记录快照：{time}",
  stale: "已保留上次快照。刷新失败，显示的记录并未更新。",
  pressureEyebrow: "副作用边界",
  pressureTitle: "凭据状态",
  reserved: "已预留",
  running: "运行中",
  unknownResult: "结果未知",
  noReplayHelp:
    "结果未知的操作不会自动重放。在依据外部证据完成核对前，它们会一直显示。",
  fleetProcesses: "进程拓扑",
  runtimeTitle: "运行时进程",
  processCount: "已注册进程：{count}",
  instancesError:
    "进程列表刷新失败。下方保留已加载的记录（如有），请勿将其视为当前状态。",
  instancesLoading: "正在检查运行时进程…",
  instancesEmpty: "未发现已注册的运行时进程。",
  persisted: "记录状态：{state}",
  effective: "有效状态：{state}",
  noCapability: "未声明任何能力",
  projectTitle: "运行监控室",
  projectHelp:
    "在持久时间线中查看团队活动、所有权交接、恢复情况和外部影响证据。",
  coverageComplete: "每个分钟区间都有健康记录。",
  coverageGathering: "健康记录正逐分钟积累。",
  coverageHelp:
    "缺失记录不算健康。样本覆盖情况不等同于 24 小时耐久性测试结果。",
  filter: "时间筛选",
  clearFilter: "清除筛选",
  filterHelp: "显示在此区间内开始的尝试。没有源尝试的凭据仍会保留在列表中。",
  attemptEvidence: "尝试证据",
  chainHelp: "逻辑执行、物理调用和凭据组成同一条链。",
  sourceHelp: "名称、角色、操作文本和标识符保留原始记录，不进行翻译。",
  fleetError: "无法加载运行中心",
  fleetErrorHelp: "持久进程快照不可用，不会显示推测状态。",
  fleetLoading: "正在加载运行中心",
  invalidAddress: "运行监控地址无效",
  invalidAddressHelp: "此链接中没有有效的项目标识符。",
  projectMissing: "未找到项目运行数据",
  projectMissingHelp: "此地址仅用于打开根项目的持久运行监控室。",
  projectError: "无法加载运行监控室",
  projectErrorHelp: "无法加载上次已知快照。请检查连接并重试。",
  projectLoading: "正在加载运行监控室",
  activeWork: "活动任务",
  recoveringCount: "正在恢复：{count}",
  queue: "待处理队列",
  sleepingCount: "休眠中：{count}",
  oldest: "最早的待处理项",
  delayAge: "延迟时长",
  queueClear: "队列为空",
  nextWake: "下次唤醒",
  scheduler: "持久调度器",
  intervention: "需要介入",
  approvalCount: "等待批准：{count}",
  tokenUsage: "令牌用量",
  reportedCost: "已报告：{cost}",
  partialCost: "成本覆盖不完整",
  noWake: "未安排唤醒",
  unknownTime: "时间未知",
  now: "现在",
  after: "{duration}后",
  ago: "{duration}前",
  dataBoundary: "证据数据边界",
  limited: "受限证据视图",
  bounded: "有边界的证据视图",
  windowHelp: "API 窗口：{hours} 小时 · 记录时区：{zone} · 显示时区：{display}",
  invocationLimit: "每个凭据最多显示 {count} 次物理调用。",
  limitReached: "{label}：已达到 {count} 条记录的上限",
  attempts: "尝试",
  receipts: "凭据",
  incidents: "事件",
  milestones: "里程碑",
  samples: "健康样本",
  healthAria:
    "24 小时健康窗口：{healthy} 分钟健康，{degraded} 分钟降级，{incident} 分钟发生事件，{unknown} 分钟未知",
  healthLabel: "记录的健康状况",
  healthEyebrow: "健康记录",
  last24: "过去 24 小时",
  coveredMinutes: "已记录分钟数：{count} / {total}",
  intervals: "健康区间",
  minutesState: "{count} 分钟 · {state}",
  inspect: "检查：{content}",
  teamEyebrow: "团队活动",
  teamTitle: "谁在做什么？",
  expertCount: "专家数：{count}",
  waitingWake: "等待计划唤醒",
  teamEmpty: "此视图中没有已验证的团队在线记录。",
  missionEyebrow: "事件记录器",
  missionTitle: "任务日志",
  missionLimit: "最多显示最近 {count} 个事件。",
  evidence: "证据",
  attempt: "尝试",
  receipt: "凭据",
  noEvents: "没有已记录事件",
  noEventsHelp: "已记录的交接、恢复和介入事件将显示在此处。",
  attemptEyebrow: "持久工作流",
  attemptTitle: "执行尝试",
  recentAttempts: "最近尝试数：{count}",
  inspectAttempt: "检查尝试 {id} 的证据",
  recoveryAttempt: "恢复尝试",
  expert: "专家 #{id}",
  cycleAttempt: "周期 {cycle} · 尝试 {attempt}",
  tokens: "{count} 个令牌",
  attemptEmpty: "此窗口内没有持久执行尝试。",
  receiptEyebrow: "外部影响证据",
  receiptTitle: "副作用凭据",
  noReplay: "不会重放",
  unknownHelp: "副作用可能已经开始。未经权威外部来源确认，不会再次执行此操作。",
  eligible: "可核对 · 需要人工证据",
  reconcile: "核对结果",
  appliedRecord: "外部影响已确认发生",
  notAppliedRecord: "外部影响已确认未发生",
  invocationCount: "物理调用记录：{count}",
  receiptEmpty: "此窗口内没有外部影响凭据。",
  chainEyebrow: "所选尝试的持久记录",
  chainTitle: "证据链",
  chainEmpty: "选择一次执行尝试以查看其证据链。",
  logicalExecution: "逻辑执行",
  durableAttempt: "持久尝试",
  physicalInvocation: "物理调用",
  worker: "工作进程：{id}",
  boundaryStarted: "已进入副作用边界：{time}",
  boundaryMissing: "没有进入副作用边界的证据。",
  effectReceipt: "副作用凭据",
  noLinkedEvidence:
    "没有与此尝试关联的物理调用或外部影响凭据。记录缺失并不能证明未发生操作。",
  unknownState: "未知记录：{value}",
  live: "实时 · 工作进程：{count}",
  degradedTruth: "运行降级 · 可能需要介入",
  staleTruth: "工作进程信号延迟",
  offlineTruth: "没有运行中的工作进程",
  emergencyTruth: "紧急停止已启用",
  demoTruth: "本地演示 · 非持久化",
  disconnected: "连接已断开 · 上次信号 {age}",
  staleStream: "数据流延迟 · 上次信号 {age}",
  connecting: "正在连接实时数据流",
  disabledStream: "实时数据流已关闭 · 手动刷新",
  state_working: "工作中",
  state_awaiting_approval: "等待批准",
  state_recovering: "恢复中",
  state_blocked: "已阻止",
  state_idle: "排队中 / 休眠中",
  state_offline: "离线",
  state_unknown: "未知",
  state_healthy: "健康",
  state_degraded: "降级",
  state_incident: "事件",
  state_draining: "正在排空",
  state_stopped: "已停止",
  state_claimed: "已认领",
  state_running: "运行中",
  state_succeeded: "成功",
  state_retrying: "已安排重试",
  state_lost: "所有权已丢失",
  state_failed: "失败",
  state_reserved: "已预留",
  state_in_progress: "进行中",
  state_pending: "待处理",
  state_completed: "已完成",
  state_cancelled: "已取消",
  state_worker: "工作进程",
  state_api: "API 服务器",
  state_combined: "合并进程",
  state_scheduler: "调度器",
  state_read_only: "只读",
  state_local_write: "本地写入",
  state_external_write: "外部写入",
  state_irreversible: "不可逆",
  state_task_step: "任务步骤",
  state_chat_turn: "聊天轮次",
  state_worker_recovered: "工作进程已恢复",
  state_worker_stale: "工作进程信号丢失",
  state_lease_lost: "执行所有权已丢失",
  state_task_recovered: "任务已恢复",
  state_handoff_completed: "交接已完成",
  state_operation_unknown: "操作结果需要验证",
  state_operation_reconciled: "操作结果已核对",
  state_task_completed: "任务已完成",
  reconcileTitle: "核对未知的外部影响",
  reconcileHelp:
    "此决定不会重新执行操作，而是将基于权威外部证据的结果加入不可变的审计记录。",
  project: "项目",
  noLink: "未建立关联",
  operation: "操作",
  effectClass: "副作用类别",
  lastBoundary: "最近的副作用边界",
  boundaryNotRecorded: "未记录进入副作用边界的时间",
  proofHelp:
    "此处不公开原始目标。仅在结果与权威外部记录、送达凭据或接收方确认一致后保存。",
  decision: "已验证结果",
  applied: "外部影响已发生",
  notApplied: "外部影响未发生",
  appliedHelp: "外部系统确认操作已发生。",
  notAppliedHelp: "外部系统确认操作未发生。",
  decisionHelp: "选择已在外部验证的唯一结果。此选择不是重新执行命令。",
  note: "审计备注",
  notePlaceholder: "说明验证了哪项外部记录、何时验证以及如何验证。",
  noteHelp:
    "必须填写备注，最多 {count} 个 UTF-8 字节。部分字符占用多个字节。请勿包含密钥、密码或个人数据。",
  decisionRequired: "请选择结果。",
  noteRequired: "必须填写审计备注。",
  noteLong: "审计备注最多可占用 {count} 个 UTF-8 字节。",
  ineligible: "此凭据已不符合核对条件。请检查最新记录；备注会保留在此处。",
  uncertain: "无法确认保存结果。备注已保留。再次发送前请检查最新记录。",
  checkRecord: "检查最新记录",
  checkFailed: "无法获取最新记录。发送已禁用；可以重新检查。",
  recordMissing: "服务器上未找到此凭据。这不能证明外部结果；发送已禁用。",
  recordConfirmed:
    "服务器已记录决定：{decision}。仅凭此记录无法确认最近提交的备注已保存。",
  recordFresh: "已加载最新记录。凭据仍在等待决定；发送前请复核证据。",
  staleWrite: "快照刷新失败。提交决定前请检查最新记录。",
  saved: "核对决定已记录",
  save: "保存决定",
  cancel: "取消",
  state_stale: "已过期",
  state_at_most_once: "最多一次",
  state_approval_at_most_once: "批准后最多一次",
  state_idempotent: "幂等",
  state_http: "HTTP 服务器",
  healthScope: "健康样本描述整个部署，不归属于单个项目。",
  state_starting: "正在启动",
  state_planning: "规划中",
  sameIntent: "在上次提交结果确定前，决定和备注保持锁定。重试将发送相同内容。",
  state_transactional: "原子数据库操作",
  state_approved_action: "已批准操作",
  snapshotOutdated: "快照无法刷新",
} satisfies OperationsCopy;
export default copy;
