import type { OperationsCopy } from "../operations-copy";
const copy = {
  recoveryTitle: "需要檢查已儲存的核對決定",
  recoveryHelp:
    "此分頁為本專案保留一項結果未確認的決定，即使它已超出歷史記錄範圍。重新整理分頁會保留它；關閉分頁或更換裝置可能不會。",
  reviewSaved: "檢查已儲存的決定",
  recoveryDamaged:
    "無法安全讀取已儲存的決定。清除前請檢查本機資料；不會根據此資料傳送請求。",
  clearRecovery: "清除本機復原記錄",
  clearRecoveryHelp:
    "我理解清除此本機副本不會取消或變更伺服器上的操作。我已保留所需證據，並將在做出新決定前檢查外部結果。",
  recoveryChanged: "本機記錄已變更或無法清除。請重新檢查。",
  recoveryStorage:
    "瀏覽器儲存空間無法使用。無法驗證或清除已儲存的決定。恢復儲存功能後請重新檢查。",
  draftStorage:
    "瀏覽器儲存空間無法使用。文字保留於此處；未傳送任何內容。恢復儲存功能後請再次嘗試儲存。",
  recoveryBlocked:
    "需要檢查另一項已儲存的決定或損壞的本機資料。傳送前請關閉此對話框並檢查復原面板。",
  damagedDraft: "無法安全讀取此已儲存的草稿。其原始本機內容顯示於下方。",
  discardDraftHelp: "我已檢查並保留所需文字。僅刪除此尚未傳送的本機草稿。",
  discardDraft: "刪除損壞的草稿",
  recordedAudit: "伺服器原始稽核記錄",
  acknowledgeRecord: "確認已查看記錄的決定",
  noteBytes: "{used} / {limit} 位元組",
  fleetTitle: "運作中心",
  fleetEyebrow: "AgenticOS 程序總覽",
  command: "系統狀態",
  fleetHelp:
    "查看工作程序訊號、持久佇列與操作憑據。健康樣本反映過去 24 小時的記錄涵蓋情況。",
  projects: "前往專案",
  backProjects: "返回專案",
  studio: "專案工作室",
  refresh: "重新整理",
  retry: "重試",
  cursor: "記錄游標：{id}",
  projectId: "專案 #{id}",
  snapshot: "上次記錄快照：{time}",
  stale: "已保留上次快照。重新整理失敗，顯示的記錄並未更新。",
  pressureEyebrow: "副作用邊界",
  pressureTitle: "憑據狀態",
  reserved: "已保留",
  running: "執行中",
  unknownResult: "結果未知",
  noReplayHelp:
    "結果未知的操作不會自動重播。在依據外部證據完成核對前，它們會持續顯示。",
  fleetProcesses: "程序拓樸",
  runtimeTitle: "執行階段程序",
  processCount: "已註冊程序：{count}",
  instancesError:
    "程序清單重新整理失敗。下方保留已載入的記錄（如有），請勿將其視為目前狀態。",
  instancesLoading: "正在檢查執行階段程序…",
  instancesEmpty: "未發現已註冊的執行階段程序。",
  persisted: "記錄狀態：{state}",
  effective: "有效狀態：{state}",
  noCapability: "未宣告任何能力",
  projectTitle: "運作監控室",
  projectHelp:
    "在持久時間軸中查看團隊活動、所有權交接、復原情況與外部影響證據。",
  coverageComplete: "每個分鐘區間都有健康記錄。",
  coverageGathering: "健康記錄正逐分鐘累積。",
  coverageHelp:
    "缺失記錄不算健康。樣本涵蓋情況不等同於 24 小時耐久性測試結果。",
  filter: "時間篩選",
  clearFilter: "清除篩選",
  filterHelp: "顯示在此區間內開始的嘗試。沒有來源嘗試的憑據仍會保留在清單中。",
  attemptEvidence: "嘗試證據",
  chainHelp: "邏輯執行、實體呼叫與憑據組成同一條鏈。",
  sourceHelp: "名稱、角色、操作文字與識別碼保留原始記錄，不進行翻譯。",
  fleetError: "無法載入運作中心",
  fleetErrorHelp: "持久程序快照無法取得，不會顯示推測狀態。",
  fleetLoading: "正在載入運作中心",
  invalidAddress: "運作監控位址無效",
  invalidAddressHelp: "此連結中沒有有效的專案識別碼。",
  projectMissing: "找不到專案運作資料",
  projectMissingHelp: "此位址僅用於開啟根專案的持久運作監控室。",
  projectError: "無法載入運作監控室",
  projectErrorHelp: "無法載入上次已知快照。請檢查連線並重試。",
  projectLoading: "正在載入運作監控室",
  activeWork: "進行中的工作",
  recoveringCount: "正在復原：{count}",
  queue: "待處理佇列",
  sleepingCount: "休眠中：{count}",
  oldest: "最早的待處理項目",
  delayAge: "延遲時間",
  queueClear: "佇列為空",
  nextWake: "下次喚醒",
  scheduler: "持久排程器",
  intervention: "需要介入",
  approvalCount: "等待核准：{count}",
  tokenUsage: "Token 用量",
  reportedCost: "已回報：{cost}",
  partialCost: "成本涵蓋不完整",
  noWake: "未排定喚醒",
  unknownTime: "時間未知",
  now: "現在",
  after: "{duration}後",
  ago: "{duration}前",
  dataBoundary: "證據資料邊界",
  limited: "受限證據檢視",
  bounded: "有邊界的證據檢視",
  windowHelp: "API 視窗：{hours} 小時 · 記錄時區：{zone} · 顯示時區：{display}",
  invocationLimit: "每個憑據最多顯示 {count} 次實體呼叫。",
  limitReached: "{label}：已達到 {count} 筆記錄的上限",
  attempts: "嘗試",
  receipts: "憑據",
  incidents: "事件",
  milestones: "里程碑",
  samples: "健康樣本",
  healthAria:
    "24 小時健康視窗：{healthy} 分鐘健康，{degraded} 分鐘降級，{incident} 分鐘發生事件，{unknown} 分鐘未知",
  healthLabel: "記錄的健康狀況",
  healthEyebrow: "健康記錄",
  last24: "過去 24 小時",
  coveredMinutes: "已記錄分鐘數：{count} / {total}",
  intervals: "健康區間",
  minutesState: "{count} 分鐘 · {state}",
  inspect: "檢查：{content}",
  teamEyebrow: "團隊活動",
  teamTitle: "誰在做什麼？",
  expertCount: "專家數：{count}",
  waitingWake: "等待排定喚醒",
  teamEmpty: "此檢視中沒有已驗證的團隊上線記錄。",
  missionEyebrow: "事件記錄器",
  missionTitle: "任務日誌",
  missionLimit: "最多顯示最近 {count} 個事件。",
  evidence: "證據",
  attempt: "嘗試",
  receipt: "憑據",
  noEvents: "沒有已記錄事件",
  noEventsHelp: "已記錄的交接、復原與介入事件將顯示於此處。",
  attemptEyebrow: "持久工作流程",
  attemptTitle: "執行嘗試",
  recentAttempts: "最近嘗試數：{count}",
  inspectAttempt: "檢查嘗試 {id} 的證據",
  recoveryAttempt: "復原嘗試",
  expert: "專家 #{id}",
  cycleAttempt: "週期 {cycle} · 嘗試 {attempt}",
  tokens: "{count} 個 Token",
  attemptEmpty: "此視窗內沒有持久執行嘗試。",
  receiptEyebrow: "外部影響證據",
  receiptTitle: "副作用憑據",
  noReplay: "不會重播",
  unknownHelp: "副作用可能已經開始。未經權威外部來源確認，不會再次執行此操作。",
  eligible: "可核對 · 需要人工證據",
  reconcile: "核對結果",
  appliedRecord: "外部影響已確認發生",
  notAppliedRecord: "外部影響已確認未發生",
  invocationCount: "實體呼叫記錄：{count}",
  receiptEmpty: "此視窗內沒有外部影響憑據。",
  chainEyebrow: "所選嘗試的持久記錄",
  chainTitle: "證據鏈",
  chainEmpty: "選擇一次執行嘗試以查看其證據鏈。",
  logicalExecution: "邏輯執行",
  durableAttempt: "持久嘗試",
  physicalInvocation: "實體呼叫",
  worker: "工作程序：{id}",
  boundaryStarted: "已進入副作用邊界：{time}",
  boundaryMissing: "沒有進入副作用邊界的證據。",
  effectReceipt: "副作用憑據",
  noLinkedEvidence:
    "沒有與此嘗試關聯的實體呼叫或外部影響憑據。記錄缺失並不能證明未發生操作。",
  unknownState: "未知記錄：{value}",
  live: "即時 · 工作程序：{count}",
  degradedTruth: "運作降級 · 可能需要介入",
  staleTruth: "工作程序訊號延遲",
  offlineTruth: "沒有執行中的工作程序",
  emergencyTruth: "緊急停止已啟用",
  demoTruth: "本機展示 · 非持久化",
  disconnected: "連線已中斷 · 上次訊號 {age}",
  staleStream: "資料流延遲 · 上次訊號 {age}",
  connecting: "正在連接即時資料流",
  disabledStream: "即時資料流已關閉 · 手動重新整理",
  state_working: "工作中",
  state_awaiting_approval: "等待核准",
  state_recovering: "復原中",
  state_blocked: "已封鎖",
  state_idle: "排隊中 / 休眠中",
  state_offline: "離線",
  state_unknown: "未知",
  state_healthy: "健康",
  state_degraded: "降級",
  state_incident: "事件",
  state_draining: "正在清空",
  state_stopped: "已停止",
  state_claimed: "已認領",
  state_running: "執行中",
  state_succeeded: "成功",
  state_retrying: "已安排重試",
  state_lost: "所有權已遺失",
  state_failed: "失敗",
  state_reserved: "已保留",
  state_in_progress: "進行中",
  state_pending: "待處理",
  state_completed: "已完成",
  state_cancelled: "已取消",
  state_worker: "工作程序",
  state_api: "API 伺服器",
  state_combined: "合併程序",
  state_scheduler: "排程器",
  state_read_only: "唯讀",
  state_local_write: "本機寫入",
  state_external_write: "外部寫入",
  state_irreversible: "不可逆",
  state_task_step: "任務步驟",
  state_chat_turn: "聊天回合",
  state_worker_recovered: "工作程序已復原",
  state_worker_stale: "工作程序訊號遺失",
  state_lease_lost: "執行所有權已遺失",
  state_task_recovered: "任務已復原",
  state_handoff_completed: "交接已完成",
  state_operation_unknown: "操作結果需要驗證",
  state_operation_reconciled: "操作結果已核對",
  state_task_completed: "任務已完成",
  reconcileTitle: "核對未知的外部影響",
  reconcileHelp:
    "此決定不會重新執行操作，而是將基於權威外部證據的結果加入不可變的稽核記錄。",
  project: "專案",
  noLink: "未建立關聯",
  operation: "操作",
  effectClass: "副作用類別",
  lastBoundary: "最近的副作用邊界",
  boundaryNotRecorded: "未記錄進入副作用邊界的時間",
  proofHelp:
    "此處不公開原始目標。僅在結果與權威外部記錄、送達憑據或接收方確認一致後儲存。",
  decision: "已驗證結果",
  applied: "外部影響已發生",
  notApplied: "外部影響未發生",
  appliedHelp: "外部系統確認操作已發生。",
  notAppliedHelp: "外部系統確認操作未發生。",
  decisionHelp: "選擇已在外部驗證的唯一結果。此選擇不是重新執行命令。",
  note: "稽核備註",
  notePlaceholder: "說明驗證了哪項外部記錄、何時驗證及如何驗證。",
  noteHelp:
    "必須填寫備註，最多 {count} 個 UTF-8 位元組。部分字元佔用多個位元組。請勿包含金鑰、密碼或個人資料。",
  decisionRequired: "請選擇結果。",
  noteRequired: "必須填寫稽核備註。",
  noteLong: "稽核備註最多可佔用 {count} 個 UTF-8 位元組。",
  ineligible: "此憑據已不符合核對條件。請檢查最新記錄；備註會保留於此處。",
  uncertain: "無法確認儲存結果。備註已保留。再次傳送前請檢查最新記錄。",
  checkRecord: "檢查最新記錄",
  checkFailed: "無法取得最新記錄。傳送已停用；可以重新檢查。",
  recordMissing: "伺服器上找不到此憑據。這不能證明外部結果；傳送已停用。",
  recordConfirmed:
    "伺服器已記錄決定：{decision}。僅憑此記錄無法確認最近提交的備註已儲存。",
  recordFresh: "已載入最新記錄。憑據仍在等待決定；傳送前請複核證據。",
  staleWrite: "快照重新整理失敗。提交決定前請檢查最新記錄。",
  saved: "核對決定已記錄",
  save: "儲存決定",
  cancel: "取消",
  state_stale: "已過期",
  state_at_most_once: "最多一次",
  state_approval_at_most_once: "核准後最多一次",
  state_idempotent: "冪等",
  state_http: "HTTP 伺服器",
  healthScope: "健康樣本描述整個部署，不歸屬於單一專案。",
  state_starting: "正在啟動",
  state_planning: "規劃中",
  sameIntent: "在上次提交結果確定前，決定與備註保持鎖定。重試將傳送相同內容。",
  state_transactional: "原子資料庫操作",
  state_approved_action: "已核准操作",
  snapshotOutdated: "快照無法重新整理",
} satisfies OperationsCopy;
export default copy;
