import type { OperationsCopy } from "../operations-copy";
const copy = {
  tokensAtLeast: "Mindestens {count}",
  tokenUsageUnknown: "Tokenverbrauch unbekannt",
  tokenCoveragePartial:
    "Für einige Aufrufe fehlt der gemeldete Tokenverbrauch; die Summen sind Untergrenzen.",
  noRecordedUsage: "Keine Nutzungsbelege in diesem Zeitraum.",
  recoveryTitle: "Gespeicherte Abgleichentscheidung prüfen",
  recoveryHelp:
    "Dieser Tab bewahrt eine ungeklärte Entscheidung für dieses Projekt auch außerhalb des Verlaufs auf. Neuladen erhält sie; Schließen des Tabs oder Gerätewechsel möglicherweise nicht.",
  reviewSaved: "Gespeicherte Entscheidung prüfen",
  recoveryDamaged:
    "Die gespeicherte Entscheidung ist nicht sicher lesbar. Prüfen Sie die lokalen Daten vor dem Löschen; daraus wird keine Anfrage gesendet.",
  clearRecovery: "Lokale Wiederherstellung löschen",
  clearRecoveryHelp:
    "Mir ist bewusst, dass das Löschen dieser lokalen Kopie die Serveraktion weder abbricht noch ändert. Ich habe die nötigen Belege gesichert und prüfe das externe Ergebnis vor einer neuen Entscheidung.",
  recoveryChanged:
    "Der lokale Eintrag hat sich geändert oder konnte nicht gelöscht werden. Prüfen Sie ihn erneut.",
  recoveryStorage:
    "Der Browserspeicher ist nicht verfügbar. Die gespeicherte Entscheidung konnte nicht geprüft oder gelöscht werden. Stellen Sie den Speicher wieder her und prüfen Sie erneut.",
  draftStorage:
    "Der Browserspeicher ist nicht verfügbar. Ihr Text bleibt hier; nichts wurde gesendet. Versuchen Sie nach Wiederherstellung des Speichers erneut zu speichern.",
  recoveryBlocked:
    "Eine andere gespeicherte Entscheidung oder beschädigte lokale Daten müssen geprüft werden. Schließen Sie diesen Dialog und prüfen Sie den Wiederherstellungsbereich vor dem Senden.",
  damagedDraft:
    "Dieser gespeicherte Entwurf ist nicht sicher lesbar. Sein ursprünglicher lokaler Inhalt wird unten angezeigt.",
  discardDraftHelp:
    "Ich habe den benötigten Text geprüft und gesichert. Nur dieser ungesendete lokale Entwurf wird entfernt.",
  discardDraft: "Beschädigten Entwurf verwerfen",
  recordedAudit: "Ursprünglicher Servernachweis",
  acknowledgeRecord: "Gespeicherte Entscheidung bestätigen",
  noteBytes: "{used} / {limit} Byte",
  fleetTitle: "Betriebszentrale",
  fleetEyebrow: "AgenticOS-Flottenübersicht",
  command: "Systemstatus",
  fleetHelp:
    "Worker-Signale, persistente Warteschlange und Vorgangsbelege. Gesundheitsdaten zeigen die erfassten letzten 24 Stunden.",
  projects: "Zu den Projekten",
  backProjects: "Zurück zu Projekten",
  studio: "Projektstudio",
  refresh: "Aktualisieren",
  retry: "Erneut versuchen",
  cursor: "Datensatzposition: {id}",
  projectId: "Projekt #{id}",
  snapshot: "Letzter gespeicherter Stand: {time}",
  stale:
    "Letzter Stand bleibt sichtbar. Aktualisierung fehlgeschlagen; die angezeigten Daten sind nicht aktueller geworden.",
  pressureEyebrow: "Wirkungsgrenze",
  pressureTitle: "Belegstatus",
  reserved: "Reserviert",
  running: "Läuft",
  unknownResult: "Ergebnis unklar",
  noReplayHelp:
    "Unklare Ergebnisse werden nicht automatisch wiederholt. Sie bleiben bis zum Abgleich mit externen Nachweisen sichtbar.",
  fleetProcesses: "Prozessübersicht",
  runtimeTitle: "Laufzeitprozesse",
  processCount: "Registrierte Prozesse: {count}",
  instancesError:
    "Die Prozessliste konnte nicht aktualisiert werden. Vorhandene Daten bleiben unten sichtbar und sind möglicherweise veraltet.",
  instancesLoading: "Laufzeitprozesse werden geprüft…",
  instancesEmpty: "Keine registrierten Laufzeitprozesse sichtbar.",
  persisted: "Gespeichert: {state}",
  effective: "Wirksam: {state}",
  noCapability: "Keine Fähigkeiten gemeldet",
  projectTitle: "Betriebsraum",
  projectHelp:
    "Teamaktivität, Zuständigkeitswechsel, Wiederherstellung und externe Wirkungen in einer persistenten Zeitleiste verfolgen.",
  coverageComplete: "Für jede Minute liegt ein Zustandsdatensatz vor.",
  coverageGathering: "Zustandsdaten werden minütlich erfasst.",
  coverageHelp:
    "Lücken gelten nicht als gesund. Stichprobenabdeckung ist kein Ergebnis eines 24-Stunden-Dauertests.",
  filter: "Zeitfilter",
  clearFilter: "Filter entfernen",
  filterHelp:
    "Versuche mit Start in diesem Zeitraum werden angezeigt. Belege ohne Ursprungsversuch bleiben sichtbar.",
  attemptEvidence: "Versuchsnachweis",
  chainHelp: "Logische Ausführung, physischer Aufruf und Beleg in einer Kette.",
  sourceHelp:
    "Namen, Rollen, Aktionstexte und Kennungen sind unveränderte Originaldaten.",
  fleetError: "Betriebszentrale konnte nicht geladen werden",
  fleetErrorHelp:
    "Der persistente Flottenstand ist nicht verfügbar. Es wird kein geschätzter Status angezeigt.",
  fleetLoading: "Betriebszentrale wird geladen",
  invalidAddress: "Ungültige Betriebsadresse",
  invalidAddressHelp: "Dieser Link enthält keine gültige Projektkennung.",
  projectMissing: "Projektbetrieb nicht gefunden",
  projectMissingHelp:
    "Diese Adresse öffnet nur den Betriebsraum übergeordneter Projekte.",
  projectError: "Betriebsraum konnte nicht geladen werden",
  projectErrorHelp:
    "Der letzte bekannte Stand konnte nicht geladen werden. Verbindung prüfen und erneut versuchen.",
  projectLoading: "Betriebsraum wird geladen",
  activeWork: "Aktive Aufgaben",
  recoveringCount: "Wiederherstellung: {count}",
  queue: "Warteschlange",
  sleepingCount: "Ruhend: {count}",
  oldest: "Ältester wartender Eintrag",
  delayAge: "Verzögerungsdauer",
  queueClear: "Warteschlange leer",
  nextWake: "Nächste Aktivierung",
  scheduler: "Persistenter Zeitplaner",
  intervention: "Eingriff",
  approvalCount: "Warten auf Freigabe: {count}",
  tokenUsage: "Token-Nutzung",
  reportedCost: "Gemeldet: {cost}",
  partialCost: "Kosten nur teilweise erfasst",
  noWake: "Keine Aktivierung geplant",
  unknownTime: "Zeit unbekannt",
  now: "Jetzt",
  after: "In {duration}",
  ago: "Vor {duration}",
  dataBoundary: "Grenzen der Nachweisdaten",
  limited: "Begrenzte Nachweisansicht",
  bounded: "Eingegrenzte Nachweisansicht",
  windowHelp:
    "API-Zeitraum: {hours} Stunden · Datensatz-Zeitzone: {zone} · Anzeige: {display}",
  invocationLimit:
    "Pro Beleg werden höchstens {count} physische Aufrufe angezeigt.",
  limitReached: "{label}: Grenze von {count} Datensätzen erreicht",
  attempts: "Versuche",
  receipts: "Belege",
  incidents: "Vorfälle",
  milestones: "Meilensteine",
  samples: "Zustandsproben",
  healthAria:
    "24-Stunden-Zustandsfenster · Minuten: gesund {healthy}, eingeschränkt {degraded}, Vorfälle {incident}, unbekannt {unknown}",
  healthLabel: "Erfasster Zustand",
  healthEyebrow: "Zustandsverlauf",
  last24: "Letzte 24 Stunden",
  coveredMinutes: "Erfasste Minuten: {count} / {total}",
  intervals: "Zustandsintervalle",
  minutesState: "{count} Min. · {state}",
  inspect: "Prüfen: {content}",
  teamEyebrow: "Teamaktivität",
  teamTitle: "Wer arbeitet woran?",
  expertCount: "Fachkräfte: {count}",
  waitingWake: "Wartet auf geplante Aktivierung",
  teamEmpty: "Keine bestätigte Teampräsenz in dieser Ansicht.",
  missionEyebrow: "Ereignisaufzeichnung",
  missionTitle: "Aufgabenprotokoll",
  missionLimit: "Bis zu {count} aktuelle Ereignisse werden angezeigt.",
  evidence: "Nachweis",
  attempt: "Versuch",
  receipt: "Beleg",
  noEvents: "Keine Ereignisse erfasst",
  noEventsHelp:
    "Gespeicherte Übergaben, Wiederherstellungen und Eingriffe erscheinen hier.",
  attemptEyebrow: "Persistenter Arbeitsablauf",
  attemptTitle: "Ausführungsversuche",
  recentAttempts: "Letzte Versuche: {count}",
  inspectAttempt: "Nachweis für Versuch {id} prüfen",
  recoveryAttempt: "Wiederherstellungsversuch",
  expert: "Fachkraft #{id}",
  cycleAttempt: "Zyklus {cycle} · Versuch {attempt}",
  tokens: "{count} Token",
  attemptEmpty: "Keine persistenten Ausführungsversuche in diesem Zeitraum.",
  receiptEyebrow: "Nachweis externer Wirkung",
  receiptTitle: "Wirkungsbelege",
  noReplay: "Keine Wiederholung",
  unknownHelp:
    "Die Wirkung kann bereits eingesetzt haben. Ohne maßgebliche externe Bestätigung wird der Vorgang nicht wiederholt.",
  eligible: "Abgleich möglich · menschlicher Nachweis erforderlich",
  reconcile: "Ergebnis abgleichen",
  appliedRecord: "Externe Wirkung als ausgeführt bestätigt",
  notAppliedRecord: "Externe Wirkung als nicht ausgeführt bestätigt",
  invocationCount: "Physische Aufrufnachweise: {count}",
  receiptEmpty: "Keine Belege externer Wirkungen in diesem Zeitraum.",
  chainEyebrow: "Persistente Spur des gewählten Versuchs",
  chainTitle: "Nachweiskette",
  chainEmpty: "Ausführungsversuch wählen, um seine Kette zu sehen.",
  logicalExecution: "Logische Ausführung",
  durableAttempt: "Persistenter Versuch",
  physicalInvocation: "Physischer Aufruf",
  worker: "Worker: {id}",
  boundaryStarted: "Wirkungsgrenze betreten: {time}",
  boundaryMissing: "Kein Nachweis für das Betreten der Wirkungsgrenze.",
  effectReceipt: "Wirkungsbeleg",
  noLinkedEvidence:
    "Kein physischer Aufruf oder Wirkungsbeleg ist mit diesem Versuch verknüpft. Das Fehlen beweist nicht, dass keine Aktion stattfand.",
  unknownState: "Unbekannter Eintrag: {value}",
  live: "Live · Worker: {count}",
  degradedTruth: "Eingeschränkter Betrieb · Eingriff eventuell erforderlich",
  staleTruth: "Worker-Signal verspätet",
  offlineTruth: "Keine laufenden Worker",
  emergencyTruth: "Notstopp aktiv",
  demoTruth: "Lokale Demo · nicht persistent",
  disconnected: "Verbindung getrennt · letztes Signal {age}",
  staleStream: "Datenstrom verzögert · letztes Signal {age}",
  connecting: "Live-Datenstrom wird verbunden",
  disabledStream: "Live-Datenstrom aus · manuelle Aktualisierung",
  state_working: "In Arbeit",
  state_awaiting_approval: "Wartet auf Freigabe",
  state_recovering: "Wiederherstellung",
  state_blocked: "Blockiert",
  state_idle: "Wartend / ruhend",
  state_offline: "Offline",
  state_unknown: "Unbekannt",
  state_healthy: "Gesund",
  state_degraded: "Eingeschränkt",
  state_incident: "Vorfall",
  state_draining: "Wird geleert",
  state_stopped: "Gestoppt",
  state_claimed: "Übernommen",
  state_running: "Läuft",
  state_succeeded: "Erfolgreich",
  state_retrying: "Wiederholung geplant",
  state_lost: "Zuständigkeit verloren",
  state_failed: "Fehlgeschlagen",
  state_reserved: "Reserviert",
  state_in_progress: "In Bearbeitung",
  state_pending: "Ausstehend",
  state_completed: "Abgeschlossen",
  state_cancelled: "Abgebrochen",
  state_worker: "Worker",
  state_api: "API-Server",
  state_combined: "Kombinierter Prozess",
  state_scheduler: "Zeitplaner",
  state_read_only: "Nur Lesen",
  state_local_write: "Lokaler Schreibzugriff",
  state_external_write: "Externer Schreibzugriff",
  state_irreversible: "Unumkehrbar",
  state_task_step: "Aufgabenschritt",
  state_chat_turn: "Chat-Runde",
  state_worker_recovered: "Worker wiederhergestellt",
  state_worker_stale: "Worker-Signal verloren",
  state_lease_lost: "Ausführungszuständigkeit verloren",
  state_task_recovered: "Aufgabe wiederhergestellt",
  state_handoff_completed: "Übergabe abgeschlossen",
  state_operation_unknown: "Vorgangsergebnis muss geprüft werden",
  state_operation_reconciled: "Vorgangsergebnis abgeglichen",
  state_task_completed: "Aufgabe abgeschlossen",
  reconcileTitle: "Unklare externe Wirkung abgleichen",
  reconcileHelp:
    "Diese Entscheidung führt den Vorgang nicht erneut aus. Sie ergänzt das unveränderliche Prüfprotokoll um ein extern belegtes Ergebnis.",
  project: "Projekt",
  noLink: "Keine Zuordnung",
  operation: "Vorgang",
  effectClass: "Wirkungsklasse",
  lastBoundary: "Letzte Wirkungsgrenze",
  boundaryNotRecorded: "Eintrittszeit an der Wirkungsgrenze nicht erfasst",
  proofHelp:
    "Das rohe Ziel wird hier nicht angezeigt. Erst speichern, wenn das Ergebnis mit einem maßgeblichen externen Datensatz, Zustellbeleg oder einer Empfängerbestätigung abgeglichen wurde.",
  decision: "Bestätigtes Ergebnis",
  applied: "Externe Wirkung ausgeführt",
  notApplied: "Externe Wirkung nicht ausgeführt",
  appliedHelp: "Das externe System bestätigt die Ausführung.",
  notAppliedHelp:
    "Das externe System bestätigt, dass keine Ausführung stattfand.",
  decisionHelp:
    "Das extern bestätigte Ergebnis wählen. Diese Auswahl ist kein Wiederholungsbefehl.",
  note: "Prüfnotiz",
  notePlaceholder:
    "Beschreiben, welchen externen Datensatz Sie wann und wie geprüft haben.",
  noteHelp:
    "Eine Notiz ist erforderlich, höchstens {count} UTF-8-Byte. Manche Zeichen benötigen mehrere Byte. Keine Schlüssel, Passwörter oder personenbezogenen Daten eintragen.",
  decisionRequired: "Ein Ergebnis wählen.",
  noteRequired: "Eine Prüfnotiz ist erforderlich.",
  noteLong: "Die Prüfnotiz darf höchstens {count} UTF-8-Byte enthalten.",
  ineligible:
    "Dieser Beleg ist nicht mehr für den Abgleich geeignet. Aktuellen Stand prüfen; Ihre Notiz bleibt erhalten.",
  uncertain:
    "Das Speicherergebnis ist unbestätigt. Ihre Notiz bleibt erhalten. Vor erneutem Senden den aktuellen Datensatz prüfen.",
  checkRecord: "Aktuellen Datensatz prüfen",
  checkFailed:
    "Aktueller Datensatz nicht verfügbar. Senden ist gesperrt; erneute Prüfung möglich.",
  recordMissing:
    "Der Beleg wurde auf dem Server nicht gefunden. Das beweist kein externes Ergebnis; Senden ist deaktiviert.",
  recordConfirmed:
    "Gespeicherte Serverentscheidung: {decision}. Dies allein bestätigt nicht, dass Ihre letzte Notiz gespeichert wurde.",
  recordFresh:
    "Aktueller Datensatz geladen. Der Beleg wartet weiterhin auf eine Entscheidung; Nachweise vor dem Senden prüfen.",
  staleWrite:
    "Der Stand konnte nicht aktualisiert werden. Vor der Entscheidung den aktuellen Datensatz prüfen.",
  saved: "Abgleichentscheidung gespeichert",
  save: "Entscheidung speichern",
  cancel: "Abbrechen",
  state_stale: "Veraltet",
  state_at_most_once: "Höchstens einmal",
  state_approval_at_most_once: "Höchstens einmal mit Freigabe",
  state_idempotent: "Idempotent",
  state_http: "HTTP-Server",
  healthScope:
    "Zustandsproben betreffen die gesamte Installation und werden keinem einzelnen Projekt zugeschrieben.",
  state_starting: "Wird gestartet",
  state_planning: "In Planung",
  sameIntent:
    "Bis die vorige Übermittlung geklärt ist, bleiben Entscheidung und Notiz unverändert. Ein erneuter Versuch sendet denselben Inhalt.",
  state_transactional: "Atomare Datenbankwirkung",
  state_approved_action: "Freigegebene Aktion",
  snapshotOutdated: "Stand konnte nicht aktualisiert werden",
} satisfies OperationsCopy;
export default copy;
