import type { OperationsCopy } from "../operations-copy";
const copy = {
  recoveryTitle: "Kayıtlı uzlaştırma incelenmeli",
  recoveryHelp:
    "Bu sekme, geçmiş aralığının dışında kalsa da bu proje için sonuçlanmamış bir kararı korur. Sekmeyi yenilemek kaydı korur; sekmeyi kapatmak veya cihaz değiştirmek korumayabilir.",
  reviewSaved: "Kayıtlı kararı incele",
  recoveryDamaged:
    "Kayıtlı karar güvenle okunamıyor. Silmeden önce yerel veriyi incele; bu veriden istek gönderilmez.",
  clearRecovery: "Yerel kurtarma kaydını temizle",
  clearRecoveryHelp:
    "Bu yerel kopyayı temizlemenin sunucudaki işlemi iptal etmediğini veya değiştirmediğini anlıyorum. Gerekli kanıtları sakladım ve yeni karar vermeden önce dış sonucu kontrol edeceğim.",
  recoveryChanged: "Yerel kayıt değişti veya temizlenemedi. Yeniden incele.",
  recoveryStorage:
    "Tarayıcı depolaması kullanılamıyor. Kayıtlı karar doğrulanamadı veya temizlenemedi. Depolamayı düzeltip yeniden incele.",
  draftStorage:
    "Tarayıcı depolaması kullanılamıyor. Metnin burada duruyor; hiçbir şey gönderilmedi. Depolamayı düzelttikten sonra yeniden kaydetmeyi dene.",
  recoveryBlocked:
    "Başka bir kayıtlı karar veya bozuk yerel veri incelenmeli. Göndermeden önce bu pencereyi kapatıp kurtarma panelini incele.",
  damagedDraft:
    "Kayıtlı taslak güvenle okunamıyor. Yerel içeriğin aslı aşağıda gösteriliyor.",
  discardDraftHelp:
    "Gerekli metni inceledim ve sakladım. Yalnızca bu gönderilmemiş yerel taslak silinecek.",
  discardDraft: "Bozuk taslağı sil",
  recordedAudit: "Sunucudaki özgün denetim kaydı",
  acknowledgeRecord: "Kayıtlı kararı gördüm",
  noteBytes: "{used} / {limit} bayt",
  fleetTitle: "Operasyon merkezi",
  fleetEyebrow: "AgenticOS filo görünümü",
  command: "Sistem durumu",
  fleetHelp:
    "Worker sinyalleri, kalıcı sıra ve işlem makbuzları. Sağlık örnekleri son 24 saatin kayıt kapsamını gösterir.",
  projects: "Projelere git",
  backProjects: "Projelere dön",
  studio: "Proje stüdyosu",
  refresh: "Yenile",
  retry: "Yeniden dene",
  cursor: "Kayıt sırası: {id}",
  projectId: "Proje #{id}",
  snapshot: "Son kayıt görünümü: {time}",
  stale:
    "Son görünüm korunuyor. Yenileme başarısız oldu; gösterilen kayıtların zamanı değişmedi.",
  pressureEyebrow: "Etki sınırı",
  pressureTitle: "Makbuz basıncı",
  reserved: "Ayrılmış",
  running: "Çalışıyor",
  unknownResult: "Sonucu belirsiz",
  noReplayHelp:
    "Belirsiz sonuçlar otomatik tekrar oynatılmaz; dış kanıtla uzlaştırılana kadar görünür kalır.",
  fleetProcesses: "Süreç topolojisi",
  runtimeTitle: "Runtime filosu",
  processCount: "{count} kayıtlı süreç",
  instancesError:
    "Süreç listesi yenilenemedi. Varsa son alınan kayıtlar aşağıda korunuyor; güncel durum olarak değerlendirme.",
  instancesLoading: "Runtime süreçleri doğrulanıyor…",
  instancesEmpty: "Kayıtlı runtime süreci görünmüyor.",
  persisted: "Kayıtlı: {state}",
  effective: "Hesaplanan: {state}",
  noCapability: "İlan edilmiş yetenek yok",
  projectTitle: "Operasyon odası",
  projectHelp:
    "Takımın nöbetini, sahiplik devirlerini, toparlanmaları ve dış etki kanıtlarını tek bir kalıcı zaman çizgisinde izle.",
  coverageComplete: "Tüm dakika dilimlerinde sağlık kaydı var.",
  coverageGathering: "Sağlık kaydı dakika dakika birikiyor.",
  coverageHelp:
    "Boşluklar sağlıklı sayılmaz. Bu örnek kapsamı, 24 saatlik dayanıklılık testi sonucu değildir.",
  filter: "Zaman filtresi",
  clearFilter: "Filtreyi kaldır",
  filterHelp:
    "Başlangıç zamanı bu aralıktaki denemeler gösterilir. Köken denemesi olmayan makbuzlar da listede kalır.",
  attemptEvidence: "Deneme kanıtı",
  chainHelp: "Mantıksal yürütme, fiziksel çağrı ve makbuz aynı zincirde.",
  sourceHelp:
    "Adlar, roller, işlem metinleri ve kimlikler özgün kayıtlardır; çevrilmez.",
  fleetError: "Operasyon merkezi yüklenemedi",
  fleetErrorHelp:
    "Kalıcı filo görünümü alınamadığı için tahmini bir durum göstermiyoruz.",
  fleetLoading: "Operasyon merkezi yükleniyor",
  invalidAddress: "Geçersiz operasyon adresi",
  invalidAddressHelp: "Bu bağlantıda kullanılabilir bir proje kimliği yok.",
  projectMissing: "Proje operasyonu bulunamadı",
  projectMissingHelp:
    "Bu adres yalnız ana projelerin kalıcı operasyon odasını açar.",
  projectError: "Operasyon odası yüklenemedi",
  projectErrorHelp:
    "Son sağlam görünüm alınamadı. Bağlantıyı kontrol edip yeniden deneyebilirsin.",
  projectLoading: "Operasyon odası yükleniyor",
  activeWork: "Aktif iş",
  recoveringCount: "{count} toparlanıyor",
  queue: "Bekleyen sıra",
  sleepingCount: "{count} uykuda",
  oldest: "En eski bekleyen",
  delayAge: "Gecikme süresi",
  queueClear: "Sıra temiz",
  nextWake: "Sonraki uyanış",
  scheduler: "Kalıcı zamanlayıcı",
  intervention: "Müdahale",
  approvalCount: "{count} onay bekliyor",
  tokenUsage: "Token kullanımı",
  reportedCost: "{cost} raporlandı",
  partialCost: "Maliyet kapsamı kısmi",
  noWake: "Planlı uyanış yok",
  unknownTime: "Zaman bilinmiyor",
  now: "Şimdi",
  after: "{duration} sonra",
  ago: "{duration} önce",
  dataBoundary: "Kanıt veri sınırları",
  limited: "Sınırlı kanıt görünümü",
  bounded: "Sınırları belirli kanıt görünümü",
  windowHelp:
    "{hours} saatlik API penceresi · Kayıt zaman dilimi: {zone} · Gösterim: {display}",
  invocationLimit: "Makbuz başına en fazla {count} fiziksel çağrı gösterilir.",
  limitReached: "{label}: {count} kayıt sınırına ulaşıldı",
  attempts: "Denemeler",
  receipts: "Makbuzlar",
  incidents: "Olaylar",
  milestones: "Kilometre taşları",
  samples: "Sağlık örnekleri",
  healthAria:
    "24 saatlik sağlık penceresi: {healthy} sağlıklı dakika, {degraded} kısıtlı dakika, {incident} olay dakikası ve {unknown} bilinmeyen",
  healthLabel: "Kayıtlı sağlık",
  healthEyebrow: "Nöbet izi",
  last24: "Son 24 saat",
  coveredMinutes: "{count} / {total} dakika kayıtlı",
  intervals: "İncelenebilir nöbet aralıkları",
  minutesState: "{count} dk {state}",
  inspect: "İncele: {content}",
  teamEyebrow: "Takım yörüngesi",
  teamTitle: "Kim, ne üzerinde?",
  expertCount: "{count} uzman",
  waitingWake: "Planlı uyanışı bekliyor",
  teamEmpty: "Bu görünümde doğrulanmış ekip varlığı yok.",
  missionEyebrow: "Uçuş kaydedici",
  missionTitle: "Görev kaydı",
  missionLimit: "En son {count} olay gösterilir.",
  evidence: "Kanıt",
  attempt: "Deneme",
  receipt: "Makbuz",
  noEvents: "Kayıtlı olay yok",
  noEventsHelp: "Kalıcı bir devir, toparlanma veya müdahale burada görünecek.",
  attemptEyebrow: "Dayanıklı iş akışı",
  attemptTitle: "Çalışma denemeleri",
  recentAttempts: "Son {count} deneme",
  inspectAttempt: "Deneme {id} kanıtını incele",
  recoveryAttempt: "Toparlanma denemesi",
  expert: "Uzman #{id}",
  cycleAttempt: "Döngü {cycle} · deneme {attempt}",
  tokens: "{count} token",
  attemptEmpty: "Bu pencerede kalıcı çalışma denemesi yok.",
  receiptEyebrow: "Dış etki kanıtı",
  receiptTitle: "Etki makbuzları",
  noReplay: "Tekrar oynatılmaz",
  unknownHelp:
    "Etki başlamış olabilir. Yetkili dış kaynaktan doğrulanmadan bu işlem yeniden çalıştırılmaz.",
  eligible: "Uzlaştırma için uygun · insan kanıtı gerekli",
  reconcile: "Sonucu uzlaştır",
  appliedRecord: "Dış etki uygulandı olarak doğrulandı",
  notAppliedRecord: "Dış etki uygulanmadı olarak doğrulandı",
  invocationCount: "{count} fiziksel çağrı kanıtı",
  receiptEmpty: "Bu pencerede dış etki makbuzu yok.",
  chainEyebrow: "Seçili denemenin kalıcı izi",
  chainTitle: "Kanıt zinciri",
  chainEmpty: "Zinciri görmek için bir çalışma denemesi seç.",
  logicalExecution: "Mantıksal yürütme",
  durableAttempt: "Dayanıklı deneme",
  physicalInvocation: "Fiziksel çağrı",
  worker: "Worker: {id}",
  boundaryStarted: "Etki sınırı başladı: {time}",
  boundaryMissing: "Etki sınırına giriş kanıtı yok.",
  effectReceipt: "Etki makbuzu",
  noLinkedEvidence:
    "Bu denemeye bağlanmış fiziksel çağrı veya dış etki makbuzu yok. Bu boşluk, işlem yapılmadığının kanıtı değildir.",
  unknownState: "Bilinmeyen kayıt: {value}",
  live: "Canlı · {count} worker",
  degradedTruth: "Kısıtlı çalışma · müdahale gerekebilir",
  staleTruth: "Worker sinyali gecikiyor",
  offlineTruth: "Çalışan worker yok",
  emergencyTruth: "Acil durdurma etkin",
  demoTruth: "Yerel demo · kalıcı değil",
  disconnected: "Bağlantı koptu · son sinyal {age}",
  staleStream: "Akış gecikiyor · son sinyal {age}",
  connecting: "Canlı akış bağlanıyor",
  disabledStream: "Canlı akış kapalı · elle yenileniyor",
  state_working: "Çalışıyor",
  state_awaiting_approval: "Onay bekliyor",
  state_recovering: "Toparlanıyor",
  state_blocked: "Engellendi",
  state_idle: "Sırada / uykuda",
  state_offline: "Çevrimdışı",
  state_unknown: "Bilinmiyor",
  state_healthy: "Sağlıklı",
  state_degraded: "Kısıtlı",
  state_incident: "Olay",
  state_draining: "Kapanışa hazırlanıyor",
  state_stopped: "Durduruldu",
  state_claimed: "Sahiplenildi",
  state_running: "Çalışıyor",
  state_succeeded: "Tamamlandı",
  state_retrying: "Yeniden denenecek",
  state_lost: "Sahiplik kayıp",
  state_failed: "Başarısız",
  state_reserved: "Ayrıldı",
  state_in_progress: "Devam ediyor",
  state_pending: "Bekliyor",
  state_completed: "Tamamlandı",
  state_cancelled: "İptal edildi",
  state_worker: "Worker",
  state_api: "API sunucusu",
  state_combined: "Birleşik süreç",
  state_scheduler: "Zamanlayıcı",
  state_read_only: "Salt okunur",
  state_local_write: "Yerel yazma",
  state_external_write: "Dış yazma",
  state_irreversible: "Geri alınamaz",
  state_task_step: "Görev adımı",
  state_chat_turn: "Sohbet turu",
  state_worker_recovered: "Worker yeniden devrede",
  state_worker_stale: "Worker sinyali kayboldu",
  state_lease_lost: "Çalışma sahipliği kaybedildi",
  state_task_recovered: "İş yeniden başladı",
  state_handoff_completed: "Devir tamamlandı",
  state_operation_unknown: "İşlem sonucu doğrulanmalı",
  state_operation_reconciled: "İşlem sonucu uzlaştırıldı",
  state_task_completed: "Görev tamamlandı",
  reconcileTitle: "Belirsiz dış etkiyi uzlaştır",
  reconcileHelp:
    "Bu karar işlemi yeniden çalıştırmaz. Yetkili harici kanıta dayanan sonucu değiştirilemez denetim izine ekler.",
  project: "Proje",
  noLink: "Bağ kurulamadı",
  operation: "Operasyon",
  effectClass: "Etki sınıfı",
  lastBoundary: "Son etki sınırı",
  boundaryNotRecorded: "Etki sınırına giriş zamanı kaydedilmedi",
  proofHelp:
    "Ham hedef bu görünümde yayımlanmaz. Kararı yalnız dış sistemdeki yetkili kayıt, teslim makbuzu veya karşı taraf teyidiyle eşleştirdiysen kaydet.",
  decision: "Doğrulanan sonuç",
  applied: "Dış etki uygulandı",
  notApplied: "Dış etki uygulanmadı",
  appliedHelp: "Harici sistem işlemin gerçekleştiğini doğruluyor.",
  notAppliedHelp: "Harici sistem işlemin gerçekleşmediğini doğruluyor.",
  decisionHelp:
    "Harici sistemde doğruladığın tek sonucu seç. Bu seçim bir yeniden çalıştırma komutu değildir.",
  note: "Denetim notu",
  notePlaceholder: "Hangi harici kaydı, ne zaman ve nasıl doğruladığını yaz.",
  noteHelp:
    "Not zorunludur; sınır {count} UTF-8 baytıdır. Bazı karakterler birden fazla bayt kullanır. Gizli anahtar, parola veya kişisel veri ekleme.",
  decisionRequired: "Bir sonuç seç.",
  noteRequired: "Denetim notu zorunlu.",
  noteLong: "Denetim notu en fazla {count} UTF-8 baytı olabilir.",
  ineligible:
    "Bu makbuz artık uzlaştırma için uygun değil. Son kaydı kontrol et; notun burada korunur.",
  uncertain:
    "Kaydetme sonucu doğrulanamadı. Notun korundu. Tekrar göndermeden önce son kaydı kontrol et.",
  checkRecord: "Son kaydı kontrol et",
  checkFailed:
    "Son kayıt alınamadı. Karar gönderimi kapalı; tekrar kontrol edebilirsin.",
  recordMissing:
    "Makbuz sunucuda bulunamadı. Bu durum dış sonucu kanıtlamaz; gönderim kapalı.",
  recordConfirmed:
    "Sunucuda kayıtlı karar: {decision}. Bu kayıt, son denediğin notun kaydedildiğini tek başına doğrulamaz.",
  recordFresh:
    "Son kayıt alındı. Makbuz hâlâ karar bekliyor; göndermeden önce kanıtı gözden geçir.",
  staleWrite:
    "Görünüm yenilenemedi. Karar göndermeden önce son kaydı kontrol et.",
  saved: "Uzlaştırma kararı kaydedildi",
  save: "Kararı kaydet",
  cancel: "Vazgeç",
  state_stale: "Gecikmiş",
  state_at_most_once: "En fazla bir kez",
  state_approval_at_most_once: "Onayla en fazla bir kez",
  state_idempotent: "Yinelenebilir, tek etki",
  state_http: "HTTP sunucusu",
  healthScope:
    "Sağlık örnekleri tüm kurulumun durumunu gösterir; tek bir projeye atfedilmez.",
  state_starting: "Başlatılıyor",
  state_planning: "Planlanıyor",
  sameIntent:
    "Önceki gönderimin sonucu kesinleşene kadar karar ve not sabit kalır. Yeniden gönderim aynı içeriği kullanır.",
  state_transactional: "Veritabanı işlemiyle atomik",
  state_approved_action: "Onaylı eylem",
  snapshotOutdated: "Son görünüm güncellenemedi",
} satisfies OperationsCopy;
export default copy;
