const copy = {
  tokensAtLeast: "At least {count}",
  tokenUsageUnknown: "Token usage unknown",
  tokenCoveragePartial:
    "Some calls have no reported token usage; totals are lower bounds.",
  noRecordedUsage: "No usage receipts in this window.",
  recoveryTitle: "Saved reconciliation needs review",
  recoveryHelp:
    "This tab retains one unresolved decision for this project, even outside the history window. Reloading this tab keeps it; closing the tab or switching devices may not.",
  reviewSaved: "Review saved decision",
  recoveryDamaged:
    "The saved decision cannot be read safely. Review the local data before clearing it; no request will be sent from it.",
  clearRecovery: "Clear local recovery",
  clearRecoveryHelp:
    "I understand that clearing this local copy does not cancel or change server work. I have retained the evidence I need and will check the external outcome before making another decision.",
  recoveryChanged:
    "The local record changed or could not be cleared. Review it again.",
  recoveryStorage:
    "Browser storage is unavailable. The saved decision could not be verified or cleared. Restore storage and review it again.",
  draftStorage:
    "Browser storage is unavailable. Your text stays here; nothing was sent. Try saving again after restoring storage.",
  recoveryBlocked:
    "Another saved decision or damaged local data needs review. Close this dialog and review the recovery panel before sending.",
  damagedDraft:
    "This saved draft cannot be read safely. Its original local content is shown below.",
  discardDraftHelp:
    "I have reviewed and retained any text I need. Only this unsent local draft will be removed.",
  discardDraft: "Discard damaged draft",
  recordedAudit: "Original server audit",
  acknowledgeRecord: "Acknowledge recorded decision",
  noteBytes: "{used} / {limit} bytes",
  fleetTitle: "Operations center",
  fleetEyebrow: "AgenticOS fleet overview",
  command: "System status",
  fleetHelp:
    "Worker signals, durable queue and operation receipts. Health samples show recorded coverage of the last 24 hours.",
  projects: "Go to projects",
  backProjects: "Back to projects",
  studio: "Project studio",
  refresh: "Refresh",
  retry: "Try again",
  cursor: "Record cursor: {id}",
  projectId: "Project #{id}",
  snapshot: "Last recorded snapshot: {time}",
  stale:
    "Last snapshot retained. Refresh failed; the displayed records have not become newer.",
  pressureEyebrow: "Effect boundary",
  pressureTitle: "Receipt status",
  reserved: "Reserved",
  running: "Running",
  unknownResult: "Outcome unknown",
  noReplayHelp:
    "Unknown outcomes are not replayed automatically. They remain visible until reconciled with external evidence.",
  fleetProcesses: "Process topology",
  runtimeTitle: "Runtime fleet",
  processCount: "Registered processes: {count}",
  instancesError:
    "The process list could not refresh. Previously loaded records, if any, remain below; do not treat them as current.",
  instancesLoading: "Checking runtime processes…",
  instancesEmpty: "No registered runtime processes are visible.",
  persisted: "Recorded: {state}",
  effective: "Effective: {state}",
  noCapability: "No declared capabilities",
  projectTitle: "Operations room",
  projectHelp:
    "Follow team activity, ownership transfers, recovery and evidence of external effects in one durable timeline.",
  coverageComplete: "Every minute bucket has a health record.",
  coverageGathering: "Health records accumulate minute by minute.",
  coverageHelp:
    "Gaps do not count as healthy. Sample coverage is not a 24-hour endurance test result.",
  filter: "Time filter",
  clearFilter: "Clear filter",
  filterHelp:
    "Attempts started in this interval are shown. Receipts without an origin attempt remain listed.",
  attemptEvidence: "Attempt evidence",
  chainHelp: "Logical execution, physical invocation and receipt in one chain.",
  sourceHelp:
    "Names, roles, action text and identifiers are original records and are not translated.",
  fleetError: "Operations center could not load",
  fleetErrorHelp:
    "The durable fleet snapshot is unavailable. No estimated status is shown.",
  fleetLoading: "Loading operations center",
  invalidAddress: "Invalid operations address",
  invalidAddressHelp: "This link has no valid project identifier.",
  projectMissing: "Project operations not found",
  projectMissingHelp:
    "This address opens the durable operations room of root projects only.",
  projectError: "Operations room could not load",
  projectErrorHelp:
    "The last known snapshot could not load. Check the connection and try again.",
  projectLoading: "Loading operations room",
  activeWork: "Active work",
  recoveringCount: "Recovering: {count}",
  queue: "Pending queue",
  sleepingCount: "Sleeping: {count}",
  oldest: "Oldest pending",
  delayAge: "Delay age",
  queueClear: "Queue clear",
  nextWake: "Next wake",
  scheduler: "Durable scheduler",
  intervention: "Intervention",
  approvalCount: "Awaiting approval: {count}",
  tokenUsage: "Token usage",
  reportedCost: "Reported: {cost}",
  partialCost: "Cost coverage is partial",
  noWake: "No scheduled wake",
  unknownTime: "Time unknown",
  now: "Now",
  after: "In {duration}",
  ago: "{duration} ago",
  dataBoundary: "Evidence data boundaries",
  limited: "Limited evidence view",
  bounded: "Bounded evidence view",
  windowHelp:
    "API window: {hours} hours · Record timezone: {zone} · Display: {display}",
  invocationLimit:
    "At most {count} physical invocations per receipt are shown.",
  limitReached: "{label}: record limit of {count} reached",
  attempts: "Attempts",
  receipts: "Receipts",
  incidents: "Incidents",
  milestones: "Milestones",
  samples: "Health samples",
  healthAria:
    "24-hour health window · minutes: healthy {healthy}, degraded {degraded}, incidents {incident}, unknown {unknown}",
  healthLabel: "Recorded health",
  healthEyebrow: "Health record",
  last24: "Last 24 hours",
  coveredMinutes: "Recorded minutes: {count} / {total}",
  intervals: "Health intervals",
  minutesState: "{count} min · {state}",
  inspect: "Inspect: {content}",
  teamEyebrow: "Team activity",
  teamTitle: "Who is working on what?",
  expertCount: "Experts: {count}",
  waitingWake: "Waiting for scheduled wake",
  teamEmpty: "No verified team presence in this view.",
  missionEyebrow: "Event recorder",
  missionTitle: "Mission log",
  missionLimit: "Showing up to {count} recent events.",
  evidence: "Evidence",
  attempt: "Attempt",
  receipt: "Receipt",
  noEvents: "No recorded events",
  noEventsHelp:
    "Recorded handoffs, recoveries and interventions will appear here.",
  attemptEyebrow: "Durable workflow",
  attemptTitle: "Execution attempts",
  recentAttempts: "Recent attempts: {count}",
  inspectAttempt: "Inspect evidence for attempt {id}",
  recoveryAttempt: "Recovery attempt",
  expert: "Expert #{id}",
  cycleAttempt: "Cycle {cycle} · attempt {attempt}",
  tokens: "{count} tokens",
  attemptEmpty: "No durable execution attempts in this window.",
  receiptEyebrow: "External effect evidence",
  receiptTitle: "Effect receipts",
  noReplay: "Not replayed",
  unknownHelp:
    "The effect may have started. This operation will not run again without authoritative external confirmation.",
  eligible: "Eligible for reconciliation · human evidence required",
  reconcile: "Reconcile outcome",
  appliedRecord: "External effect confirmed applied",
  notAppliedRecord: "External effect confirmed not applied",
  invocationCount: "Physical invocation records: {count}",
  receiptEmpty: "No external effect receipts in this window.",
  chainEyebrow: "Durable trace of the selected attempt",
  chainTitle: "Evidence chain",
  chainEmpty: "Select an execution attempt to see its chain.",
  logicalExecution: "Logical execution",
  durableAttempt: "Durable attempt",
  physicalInvocation: "Physical invocation",
  worker: "Worker: {id}",
  boundaryStarted: "Effect boundary entered: {time}",
  boundaryMissing: "No evidence of entering the effect boundary.",
  effectReceipt: "Effect receipt",
  noLinkedEvidence:
    "No physical invocation or external effect receipt is linked to this attempt. This absence does not prove that no action occurred.",
  unknownState: "Unknown record: {value}",
  live: "Live · workers: {count}",
  degradedTruth: "Degraded operation · intervention may be needed",
  staleTruth: "Worker signal is late",
  offlineTruth: "No running workers",
  emergencyTruth: "Emergency stop active",
  demoTruth: "Local demo · not durable",
  disconnected: "Disconnected · last signal {age}",
  staleStream: "Stream delayed · last signal {age}",
  connecting: "Connecting live stream",
  disabledStream: "Live stream off · manual refresh",
  state_working: "Working",
  state_awaiting_approval: "Awaiting approval",
  state_recovering: "Recovering",
  state_blocked: "Blocked",
  state_idle: "Queued / sleeping",
  state_offline: "Offline",
  state_unknown: "Unknown",
  state_healthy: "Healthy",
  state_degraded: "Degraded",
  state_incident: "Incident",
  state_draining: "Draining",
  state_stopped: "Stopped",
  state_claimed: "Claimed",
  state_running: "Running",
  state_succeeded: "Succeeded",
  state_retrying: "Retry scheduled",
  state_lost: "Ownership lost",
  state_failed: "Failed",
  state_reserved: "Reserved",
  state_in_progress: "In progress",
  state_pending: "Pending",
  state_completed: "Completed",
  state_cancelled: "Cancelled",
  state_worker: "Worker",
  state_api: "API server",
  state_combined: "Combined process",
  state_scheduler: "Scheduler",
  state_read_only: "Read only",
  state_local_write: "Local write",
  state_external_write: "External write",
  state_irreversible: "Irreversible",
  state_task_step: "Task step",
  state_chat_turn: "Chat turn",
  state_worker_recovered: "Worker recovered",
  state_worker_stale: "Worker signal lost",
  state_lease_lost: "Execution ownership lost",
  state_task_recovered: "Task recovered",
  state_handoff_completed: "Handoff completed",
  state_operation_unknown: "Operation outcome needs verification",
  state_operation_reconciled: "Operation outcome reconciled",
  state_task_completed: "Task completed",
  reconcileTitle: "Reconcile an unknown external effect",
  reconcileHelp:
    "This decision does not rerun the operation. It adds an outcome based on authoritative external evidence to an immutable audit trail.",
  project: "Project",
  noLink: "No link established",
  operation: "Operation",
  effectClass: "Effect class",
  lastBoundary: "Latest effect boundary",
  boundaryNotRecorded: "Effect boundary entry time was not recorded",
  proofHelp:
    "The raw target is not exposed here. Save only after matching the outcome to an authoritative external record, delivery receipt or recipient confirmation.",
  decision: "Verified outcome",
  applied: "External effect applied",
  notApplied: "External effect not applied",
  appliedHelp: "The external system confirms that the operation happened.",
  notAppliedHelp:
    "The external system confirms that the operation did not happen.",
  decisionHelp:
    "Select the one outcome verified externally. This choice is not a rerun command.",
  note: "Audit note",
  notePlaceholder: "Describe which external record you verified, when and how.",
  noteHelp:
    "A note is required, up to {count} UTF-8 bytes. Some characters use several bytes. Do not include keys, passwords or personal data.",
  decisionRequired: "Choose an outcome.",
  noteRequired: "An audit note is required.",
  noteLong: "The audit note may contain at most {count} UTF-8 bytes.",
  ineligible:
    "This receipt is no longer eligible for reconciliation. Check the latest record; your note is retained here.",
  uncertain:
    "The save outcome is unconfirmed. Your note is retained. Check the latest record before sending again.",
  checkRecord: "Check latest record",
  checkFailed:
    "The latest record is unavailable. Sending is disabled; you can check again.",
  recordMissing:
    "The receipt was not found on the server. This does not prove an external outcome; sending is disabled.",
  recordConfirmed:
    "Recorded server decision: {decision}. This record alone does not confirm that your latest note was saved.",
  recordFresh:
    "Latest record loaded. The receipt still awaits a decision; review the evidence before sending.",
  staleWrite:
    "The snapshot could not refresh. Check the latest record before submitting a decision.",
  saved: "Reconciliation decision recorded",
  save: "Save decision",
  cancel: "Cancel",
  state_stale: "Stale",
  state_at_most_once: "At most once",
  state_approval_at_most_once: "At most once with approval",
  state_idempotent: "Idempotent",
  state_http: "HTTP server",
  healthScope:
    "Health samples describe the whole deployment; they are not attributed to one project.",
  state_starting: "Starting",
  state_planning: "Planning",
  sameIntent:
    "Until the previous submission is settled, the decision and note stay fixed. A retry sends the same content.",
  state_transactional: "Atomic database effect",
  state_approved_action: "Approved action",
  snapshotOutdated: "Snapshot could not refresh",
};
export default copy;
