import type { OperationsCopy } from "../operations-copy";
const copy = {
  recoveryTitle: "قرار التسوية المحفوظ يحتاج إلى مراجعة",
  recoveryHelp:
    "تحتفظ علامة التبويب هذه بقرار واحد غير محسوم لهذا المشروع، حتى خارج نطاق السجل. إعادة تحميلها تحفظه؛ إغلاقها أو تغيير الجهاز قد لا يحفظه.",
  reviewSaved: "مراجعة القرار المحفوظ",
  recoveryDamaged:
    "لا يمكن قراءة القرار المحفوظ بأمان. راجع البيانات المحلية قبل مسحها؛ لن يُرسل أي طلب اعتمادًا عليها.",
  clearRecovery: "مسح سجل الاستعادة المحلي",
  clearRecoveryHelp:
    "أفهم أن مسح هذه النسخة المحلية لا يلغي العمل على الخادم ولا يغيّره. احتفظت بالأدلة اللازمة وسأتحقق من النتيجة الخارجية قبل اتخاذ قرار آخر.",
  recoveryChanged: "تغيّر السجل المحلي أو تعذّر مسحه. راجعه مجددًا.",
  recoveryStorage:
    "تخزين المتصفح غير متاح. تعذّر التحقق من القرار المحفوظ أو مسحه. أعد إتاحة التخزين وراجعه مجددًا.",
  draftStorage:
    "تخزين المتصفح غير متاح. يبقى النص هنا؛ لم يُرسل شيء. حاول الحفظ مجددًا بعد إعادة إتاحة التخزين.",
  recoveryBlocked:
    "يجب مراجعة قرار محفوظ آخر أو بيانات محلية تالفة. أغلق هذا الحوار وراجع لوحة الاستعادة قبل الإرسال.",
  damagedDraft:
    "لا يمكن قراءة المسودة المحفوظة بأمان. يظهر محتواها المحلي الأصلي أدناه.",
  discardDraftHelp:
    "راجعت النص اللازم واحتفظت به. ستُحذف هذه المسودة المحلية غير المرسلة فقط.",
  discardDraft: "حذف المسودة التالفة",
  recordedAudit: "سجل التدقيق الأصلي على الخادم",
  acknowledgeRecord: "تأكيد الاطلاع على القرار المسجل",
  noteBytes: "{used} / {limit} بايت",
  fleetTitle: "مركز العمليات",
  fleetEyebrow: "نظرة عامة على عمليات AgenticOS",
  command: "حالة النظام",
  fleetHelp:
    "إشارات العمليات العاملة والطابور الدائم وإيصالات العمليات. توضح عينات الصحة تغطية السجلات خلال آخر 24 ساعة.",
  projects: "الانتقال إلى المشاريع",
  backProjects: "العودة إلى المشاريع",
  studio: "استوديو المشروع",
  refresh: "تحديث",
  retry: "إعادة المحاولة",
  cursor: "موضع السجل: {id}",
  projectId: "المشروع #{id}",
  snapshot: "آخر لقطة مسجلة: {time}",
  stale: "تم الاحتفاظ بآخر لقطة. فشل التحديث ولم تتغير أوقات السجلات المعروضة.",
  pressureEyebrow: "حد التأثير",
  pressureTitle: "حالة الإيصالات",
  reserved: "محجوز",
  running: "قيد التشغيل",
  unknownResult: "النتيجة غير معروفة",
  noReplayHelp:
    "لا تُعاد العمليات ذات النتائج المجهولة تلقائيًا. تبقى ظاهرة حتى تتم تسويتها بأدلة خارجية.",
  fleetProcesses: "بنية العمليات",
  runtimeTitle: "عمليات بيئة التشغيل",
  processCount: "العمليات المسجلة: {count}",
  instancesError:
    "تعذر تحديث قائمة العمليات. تظهر أدناه السجلات السابقة إن وجدت؛ لا تعتبرها الحالة الحالية.",
  instancesLoading: "جارٍ التحقق من عمليات التشغيل…",
  instancesEmpty: "لا توجد عمليات تشغيل مسجلة ظاهرة.",
  persisted: "المسجل: {state}",
  effective: "الحالة الفعلية: {state}",
  noCapability: "لا توجد قدرات معلنة",
  projectTitle: "غرفة العمليات",
  projectHelp:
    "تابع نشاط الفريق وانتقال المسؤولية والتعافي وأدلة التأثيرات الخارجية في سجل زمني دائم.",
  coverageComplete: "توجد عينة صحة لكل دقيقة.",
  coverageGathering: "تتراكم سجلات الصحة دقيقة بدقيقة.",
  coverageHelp:
    "لا تُحسب الفجوات كحالة سليمة. تغطية العينات ليست نتيجة اختبار تحمل لمدة 24 ساعة.",
  filter: "مرشح الوقت",
  clearFilter: "إزالة المرشح",
  filterHelp:
    "تظهر المحاولات التي بدأت في هذه الفترة. تبقى الإيصالات التي لا ترتبط بمحاولة أصلية في القائمة.",
  attemptEvidence: "أدلة المحاولة",
  chainHelp: "التنفيذ المنطقي والاستدعاء الفعلي والإيصال في سلسلة واحدة.",
  sourceHelp:
    "الأسماء والأدوار ونصوص الإجراءات والمعرّفات سجلات أصلية لا تُترجم.",
  fleetError: "تعذر تحميل مركز العمليات",
  fleetErrorHelp: "لقطة العمليات الدائمة غير متاحة. لا تُعرض حالة تقديرية.",
  fleetLoading: "جارٍ تحميل مركز العمليات",
  invalidAddress: "عنوان العمليات غير صالح",
  invalidAddressHelp: "لا يحتوي هذا الرابط على معرّف مشروع صالح.",
  projectMissing: "لم يتم العثور على عمليات المشروع",
  projectMissingHelp:
    "يفتح هذا العنوان غرفة العمليات الدائمة للمشاريع الرئيسية فقط.",
  projectError: "تعذر تحميل غرفة العمليات",
  projectErrorHelp:
    "تعذر تحميل آخر لقطة معروفة. تحقق من الاتصال وأعد المحاولة.",
  projectLoading: "جارٍ تحميل غرفة العمليات",
  activeWork: "العمل النشط",
  recoveringCount: "قيد التعافي: {count}",
  queue: "طابور الانتظار",
  sleepingCount: "في وضع السكون: {count}",
  oldest: "أقدم عنصر معلق",
  delayAge: "مدة التأخير",
  queueClear: "الطابور فارغ",
  nextWake: "التنشيط التالي",
  scheduler: "المجدول الدائم",
  intervention: "التدخل",
  approvalCount: "بانتظار الموافقة: {count}",
  tokenUsage: "استخدام الرموز",
  reportedCost: "المبلغ المسجل: {cost}",
  partialCost: "تغطية التكلفة جزئية",
  noWake: "لا يوجد تنشيط مجدول",
  unknownTime: "الوقت غير معروف",
  now: "الآن",
  after: "بعد {duration}",
  ago: "منذ {duration}",
  dataBoundary: "حدود بيانات الأدلة",
  limited: "عرض أدلة محدود",
  bounded: "عرض الأدلة ضمن حدود محددة",
  windowHelp:
    "نافذة API: {hours} ساعة · منطقة السجلات الزمنية: {zone} · العرض: {display}",
  invocationLimit: "يُعرض بحد أقصى {count} استدعاء فعلي لكل إيصال.",
  limitReached: "{label}: تم بلوغ حد {count} سجل",
  attempts: "المحاولات",
  receipts: "الإيصالات",
  incidents: "الحوادث",
  milestones: "المراحل الرئيسية",
  samples: "عينات الصحة",
  healthAria:
    "نافذة صحة 24 ساعة · عدد الدقائق: سليمة {healthy}، متدهورة {degraded}، حوادث {incident}، مجهولة {unknown}",
  healthLabel: "الصحة المسجلة",
  healthEyebrow: "سجل الصحة",
  last24: "آخر 24 ساعة",
  coveredMinutes: "الدقائق المسجلة: {count} / {total}",
  intervals: "فترات الصحة",
  minutesState: "{count} دقيقة · {state}",
  inspect: "فحص: {content}",
  teamEyebrow: "نشاط الفريق",
  teamTitle: "من يعمل على ماذا؟",
  expertCount: "الخبراء: {count}",
  waitingWake: "بانتظار التنشيط المجدول",
  teamEmpty: "لا يوجد حضور مؤكد للفريق في هذا العرض.",
  missionEyebrow: "مسجل الأحداث",
  missionTitle: "سجل المهام",
  missionLimit: "يُعرض حتى {count} من أحدث الأحداث.",
  evidence: "الدليل",
  attempt: "المحاولة",
  receipt: "الإيصال",
  noEvents: "لا توجد أحداث مسجلة",
  noEventsHelp: "ستظهر هنا سجلات التسليم والتعافي والتدخلات.",
  attemptEyebrow: "سير العمل الدائم",
  attemptTitle: "محاولات التنفيذ",
  recentAttempts: "المحاولات الأخيرة: {count}",
  inspectAttempt: "فحص أدلة المحاولة {id}",
  recoveryAttempt: "محاولة تعافٍ",
  expert: "الخبير #{id}",
  cycleAttempt: "الدورة {cycle} · المحاولة {attempt}",
  tokens: "{count} رمز",
  attemptEmpty: "لا توجد محاولات تنفيذ دائمة في هذه النافذة.",
  receiptEyebrow: "أدلة التأثير الخارجي",
  receiptTitle: "إيصالات التأثير",
  noReplay: "لا تُعاد",
  unknownHelp:
    "قد يكون التأثير قد بدأ. لن تُعاد هذه العملية دون تأكيد من مصدر خارجي موثوق.",
  eligible: "مؤهل للتسوية · يلزم دليل بشري",
  reconcile: "تسوية النتيجة",
  appliedRecord: "تم تأكيد تطبيق التأثير الخارجي",
  notAppliedRecord: "تم تأكيد عدم تطبيق التأثير الخارجي",
  invocationCount: "سجلات الاستدعاء الفعلي: {count}",
  receiptEmpty: "لا توجد إيصالات تأثير خارجي في هذه النافذة.",
  chainEyebrow: "الأثر الدائم للمحاولة المحددة",
  chainTitle: "سلسلة الأدلة",
  chainEmpty: "اختر محاولة تنفيذ لعرض سلسلتها.",
  logicalExecution: "التنفيذ المنطقي",
  durableAttempt: "المحاولة الدائمة",
  physicalInvocation: "الاستدعاء الفعلي",
  worker: "العملية العاملة: {id}",
  boundaryStarted: "تم دخول حد التأثير: {time}",
  boundaryMissing: "لا يوجد دليل على دخول حد التأثير.",
  effectReceipt: "إيصال التأثير",
  noLinkedEvidence:
    "لا يوجد استدعاء فعلي أو إيصال تأثير خارجي مرتبط بهذه المحاولة. غياب السجل لا يثبت عدم حدوث إجراء.",
  unknownState: "سجل غير معروف: {value}",
  live: "مباشر · العمليات العاملة: {count}",
  degradedTruth: "تشغيل متدهور · قد يلزم التدخل",
  staleTruth: "إشارة العملية العاملة متأخرة",
  offlineTruth: "لا توجد عمليات عاملة نشطة",
  emergencyTruth: "الإيقاف الطارئ نشط",
  demoTruth: "عرض محلي · غير دائم",
  disconnected: "انقطع الاتصال · آخر إشارة {age}",
  staleStream: "تأخر التدفق · آخر إشارة {age}",
  connecting: "جارٍ الاتصال بالتدفق المباشر",
  disabledStream: "التدفق المباشر متوقف · تحديث يدوي",
  state_working: "يعمل",
  state_awaiting_approval: "بانتظار الموافقة",
  state_recovering: "قيد التعافي",
  state_blocked: "محظور",
  state_idle: "في الطابور / سكون",
  state_offline: "غير متصل",
  state_unknown: "غير معروف",
  state_healthy: "سليم",
  state_degraded: "متدهور",
  state_incident: "حادث",
  state_draining: "جارٍ إنهاء العمل",
  state_stopped: "متوقف",
  state_claimed: "تم توليه",
  state_running: "قيد التشغيل",
  state_succeeded: "نجح",
  state_retrying: "تمت جدولة إعادة المحاولة",
  state_lost: "فُقدت المسؤولية",
  state_failed: "فشل",
  state_reserved: "محجوز",
  state_in_progress: "قيد التنفيذ",
  state_pending: "معلق",
  state_completed: "مكتمل",
  state_cancelled: "ملغى",
  state_worker: "عملية عاملة",
  state_api: "خادم API",
  state_combined: "عملية مشتركة",
  state_scheduler: "المجدول",
  state_read_only: "للقراءة فقط",
  state_local_write: "كتابة محلية",
  state_external_write: "كتابة خارجية",
  state_irreversible: "غير قابل للتراجع",
  state_task_step: "خطوة مهمة",
  state_chat_turn: "جولة محادثة",
  state_worker_recovered: "تعافت العملية العاملة",
  state_worker_stale: "فُقدت إشارة العملية العاملة",
  state_lease_lost: "فُقدت مسؤولية التنفيذ",
  state_task_recovered: "تمت استعادة المهمة",
  state_handoff_completed: "اكتمل التسليم",
  state_operation_unknown: "يلزم التحقق من نتيجة العملية",
  state_operation_reconciled: "تمت تسوية نتيجة العملية",
  state_task_completed: "اكتملت المهمة",
  reconcileTitle: "تسوية تأثير خارجي غير معروف",
  reconcileHelp:
    "لا يعيد هذا القرار تشغيل العملية. يضيف نتيجة تستند إلى دليل خارجي موثوق إلى سجل تدقيق غير قابل للتغيير.",
  project: "المشروع",
  noLink: "لم يتم الربط",
  operation: "العملية",
  effectClass: "فئة التأثير",
  lastBoundary: "آخر حد للتأثير",
  boundaryNotRecorded: "لم يُسجل وقت دخول حد التأثير",
  proofHelp:
    "لا يُعرض الهدف الأصلي هنا. احفظ فقط بعد مطابقة النتيجة مع سجل خارجي موثوق أو إيصال تسليم أو تأكيد المستلم.",
  decision: "النتيجة المتحقق منها",
  applied: "تم تطبيق التأثير الخارجي",
  notApplied: "لم يتم تطبيق التأثير الخارجي",
  appliedHelp: "يؤكد النظام الخارجي حدوث العملية.",
  notAppliedHelp: "يؤكد النظام الخارجي عدم حدوث العملية.",
  decisionHelp:
    "اختر النتيجة الوحيدة التي تحققت منها خارجيًا. هذا الاختيار ليس أمر إعادة تشغيل.",
  note: "ملاحظة التدقيق",
  notePlaceholder: "صف السجل الخارجي الذي تحققت منه، ومتى وكيف.",
  noteHelp:
    "الملاحظة مطلوبة، بحد أقصى {count} بايت بترميز UTF-8. بعض الأحرف تستهلك عدة بايتات. لا تُدرج مفاتيح أو كلمات مرور أو بيانات شخصية.",
  decisionRequired: "اختر نتيجة.",
  noteRequired: "ملاحظة التدقيق مطلوبة.",
  noteLong: "يجب ألا تتجاوز ملاحظة التدقيق {count} بايت بترميز UTF-8.",
  ineligible:
    "لم يعد هذا الإيصال مؤهلاً للتسوية. تحقق من أحدث سجل؛ تبقى ملاحظتك هنا.",
  uncertain:
    "لم يتم تأكيد نتيجة الحفظ. تم الاحتفاظ بملاحظتك. تحقق من أحدث سجل قبل الإرسال مجددًا.",
  checkRecord: "التحقق من أحدث سجل",
  checkFailed: "أحدث سجل غير متاح. الإرسال معطل؛ يمكنك التحقق مجددًا.",
  recordMissing:
    "لم يُعثر على الإيصال على الخادم. هذا لا يثبت النتيجة الخارجية؛ الإرسال معطل.",
  recordConfirmed:
    "القرار المسجل على الخادم: {decision}. هذا السجل وحده لا يؤكد حفظ ملاحظتك الأخيرة.",
  recordFresh:
    "تم تحميل أحدث سجل. ما زال الإيصال ينتظر قرارًا؛ راجع الأدلة قبل الإرسال.",
  staleWrite: "تعذر تحديث اللقطة. تحقق من أحدث سجل قبل إرسال القرار.",
  saved: "تم تسجيل قرار التسوية",
  save: "حفظ القرار",
  cancel: "إلغاء",
  state_stale: "قديم",
  state_at_most_once: "مرة واحدة كحد أقصى",
  state_approval_at_most_once: "مرة واحدة كحد أقصى بموافقة",
  state_idempotent: "تكرار دون أثر إضافي",
  state_http: "خادم HTTP",
  healthScope: "تصف عينات الصحة التثبيت بأكمله ولا تُنسب إلى مشروع واحد.",
  state_starting: "جارٍ البدء",
  state_planning: "قيد التخطيط",
  sameIntent:
    "يبقى القرار والملاحظة ثابتين حتى تتضح نتيجة الإرسال السابق. تُرسل إعادة المحاولة المحتوى نفسه.",
  state_transactional: "تأثير ذري في قاعدة البيانات",
  state_approved_action: "إجراء معتمد",
  snapshotOutdated: "تعذر تحديث اللقطة",
} satisfies OperationsCopy;
export default copy;
