import type { ProjectStudioCopy } from "../project-studio-copy";
const copy: ProjectStudioCopy = {
  answerHeading: "{name} 正在等待你的回答",
  answerHelp: "请检查问题。发送回答后，任务将排队继续。",
  answerLabel: "你的回答",
  answerPlaceholder: "输入你的决定或缺少的信息…",
  answerDraft: "刷新后，草稿仍保存在此浏览器标签页中。请勿输入凭据。",
  answerRequired: "请输入回答。",
  answerLong: "请勿超过 1,200 个字符。",
  answerSend: "发送回答并继续",
  answerSending: "正在发送回答…",
  answerAccepted: "回答已记录，任务已排队继续。",
  answerUnknown: "尚未确认送达。文本已保留；继续前请检查已保存的回执。",
  answerCheck: "检查送达状态",
  answerNotRecorded:
    "尚无已提交的回执。请求可能仍在处理中。你可以安全地重试相同回答。",
  answerRetry: "重试相同回答",
  answerStorage:
    "无法在此标签页保存恢复信息。未发送任何内容。请复制回答并启用浏览器存储。",
  answerUnavailable: "此任务目前没有可回答的问题。请刷新后再检查。",
  answerChanged: "问题已更改。草稿已保留。请打开当前问题并在发送前检查回答。",
  answerReview: "打开当前问题",
  answerRejected: "服务器未接受此回答。",
  answerTaskChanged: "任务或负责人已更改。请刷新后继续。",
  answerOwnerInactive: "负责的智能体未启用。",
  answerEmergency: "紧急停止已启用。解除后请刷新。",
  answerQuestionLabel: "已记录的问题",
  answerQuestionError: "无法加载问题。草稿已保留。",
  answerPendingHelp:
    "在送达状态确定前，已保存的回答将保持锁定。检查不会再次发送回答。",
  unavailable: "无法获取",
  recordsMissing: "无法加载活动记录。",
  tasksMissing: "无法加载子任务。",
  tasksLoading: "正在加载子任务…",
  tasksStale: "无法刷新子任务。显示上次获取的列表。",
  completedWork: "已加载子任务完成数",
  recordStatus: "记录状态",
  invalidTitle: "项目地址无效",
  invalidHelp: "此链接不包含有效的项目 ID。",
  missingTitle: "找不到项目",
  missingHelp: "项目 #{id} 可能已被删除或尚未创建。",
  loadError: "无法加载项目",
  loadHelp: "无法获取项目详情。请检查连接后重试。",
  stale: "刷新失败。显示上次加载的项目；开始操作前请检查当前状态。",
  snapshot: "上次获取：{time}",
  retry: "重试",
  back: "返回项目",
  parent: "父项目",
  operations: "项目运行",
  stop: "停止",
  stopTitle: "停止此工作？",
  stopHelp:
    "停止“{title}”及其正在进行的子任务。已完成的外部操作不会撤销，记录将保留。",
  dismiss: "取消",
  confirmStop: "停止工作",
  stopping: "正在等待停止结果…",
  stopped: "已记录停止",
  unknownStop: "停止结果尚未确认",
  unknownHelp: "请求可能已到达服务器。检查状态不会再次发送停止请求。",
  checkState: "检查状态",
  checking: "正在检查…",
  activeAfterCheck:
    "上次检查显示工作仍在进行。先前请求的结果未知。你可以另行确认再次停止。",
  reviewStop: "重新确认停止",
  terminalObserved: "服务器状态：{status}。此检查本身不能证明先前请求的结果。",
  storageError: "无法在此标签页保存停止记录；未发送请求。请检查浏览器存储。",
  continuous: "持续运行 · {count} 个周期",
  finite: "有限任务",
  mode: "{name} 模式",
  low: "低",
  normal: "普通",
  high: "高",
  urgent: "紧急",
  warning: "最近的工作警告",
  source: "原始记录文本",
  nextAttempt: "下次尝试：{time}",
  partial: "部分项目信息不可用：{sections}。",
  plan: "工作计划",
  experts: "专家列表",
  team: "项目团队",
  chatMissing: "项目对话不可用",
  ownerMissing: "无法确认协调人。请检查当前项目和团队信息。",
  members: "团队成员：{count}",
  memberLabel: "项目团队成员",
  emptyTeam: "暂无团队信息。",
  coordinatorHelp: "{name} 负责协调，整个团队均可参与。",
  loading: "正在加载项目工作室",
  tabs: "项目工作区视图",
  workspace: "工作区",
  planTab: "计划与轨迹",
  meetings: "会议",
  teamTab: "团队",
  evidence: "交付",
  rosterHelp: "此项目记录的团队",
  coordinator: "协调人",
  workCount: "任务：{count}",
  inTeam: "团队成员",
  inactive: "未启用",
  planHelp: "已记录的子任务及其上次加载的状态",
  steps: "步骤：{count}",
  noTasks: "暂无子任务",
  noTasksHelp: "专家将计划保存为任务后，会显示在此处。",
  expertId: "专家 #{id}",
  records: "活动记录",
  recordsHelp: "服务器记录的最近 {count} 项活动。此窗口可能不含更早的历史。",
  recordsLoading: "正在加载记录",
  recordsError: "无法刷新活动。保留上次加载的记录。",
  noRecords: "暂无工作记录",
  runSummary: "记录摘要",
  progress: "进度",
  attempts: "工作尝试",
  tokens: "词元",
  model: "记录的模型",
  unknownModel: "未记录模型",
  deliverySummary: "交付摘要",
  noDelivery: "尚未记录交付摘要。保存后会显示在此处。",
};
export default copy;
