import type { ProjectStudioCopy } from "../project-studio-copy";
const copy: ProjectStudioCopy = {
  budgetHeading: "已因使用限額暫停",
  budgetHelp:
    "檢查不會消耗模型權杖，也不會重設用量。恢復的工作仍受現有限額約束。如果額度已用完，請提高設定中的限額，或等待滾動日窗口更新。",
  budgetGuide: "使用限額指南",
  budgetCheck: "檢查額度並繼續",
  budgetChecking: "正在檢查…",
  budgetAccepted: "已將 {count} 項工作加入佇列以繼續執行。",
  budgetStillPaused: "仍有 {count} 項工作處於暫停狀態。",
  budgetUnknown: "結果尚未確認。傳送新請求前，請檢查已儲存的操作記錄。",
  budgetInspect: "檢查操作記錄",
  budgetMissing:
    "尚未找到已提交的操作記錄。請求可能仍在處理中；您可以安全地重試同一請求。",
  budgetRetry: "重試同一請求",
  budgetStorage:
    "無法在此分頁儲存復原資訊。未傳送請求，或無法清除已確認操作的資訊。請啟用瀏覽器儲存空間並檢查操作記錄。",
  budgetSnapshotError: "無法讀取目前的工作範圍。請重新檢查。",
  budgetLoadError:
    "無法載入繼續執行控制項。請重新整理頁面；已儲存的請求會保留。",
  budgetReasonEmergency: "緊急停止已開啟。解除後請重新檢查。",
  budgetReasonChanged: "工作或主工作範圍已變更。請查看目前狀態。",
  budgetReasonInvalid: "此工作沒有有效的主工作範圍。未恢復任何工作。",
  budgetReasonLarge: "此工作群組超過 1,000 項工作。未恢復任何工作。",
  budgetReasonExhausted:
    "額度仍已用完。提高限額或滾動日窗口更新後，請重新檢查。",
  budgetReasonIneligible:
    "目前沒有可以安全恢復的工作。請檢查負責人、核准與未完成的操作。",
  answerHeading: "{name} 正在等待你的回答",
  answerHelp: "請檢查問題。送出回答後，任務將排入佇列繼續。",
  answerLabel: "你的回答",
  answerPlaceholder: "輸入你的決定或缺少的資訊…",
  answerDraft: "重新整理後，草稿仍保存在此瀏覽器分頁中。請勿輸入憑證。",
  answerRequired: "請輸入回答。",
  answerLong: "請勿超過 1,200 個字元。",
  answerSend: "送出回答並繼續",
  answerSending: "正在送出回答…",
  answerAccepted: "回答已記錄，任務已排入佇列繼續。",
  answerUnknown: "尚未確認送達。文字已保留；繼續前請檢查已儲存的回執。",
  answerCheck: "檢查送達狀態",
  answerNotRecorded:
    "尚無已提交的回執。請求可能仍在處理中。你可以安全地重試相同回答。",
  answerRetry: "重試相同回答",
  answerStorage:
    "無法在此分頁儲存復原資訊。未送出任何內容。請複製回答並啟用瀏覽器儲存空間。",
  answerUnavailable: "此任務目前沒有可回答的問題。請重新整理後再檢查。",
  answerChanged: "問題已變更。草稿已保留。請開啟目前的問題並在送出前檢查回答。",
  answerReview: "開啟目前的問題",
  answerRejected: "伺服器未接受此回答。",
  answerTaskChanged: "任務或負責人已變更。請重新整理後繼續。",
  answerOwnerInactive: "負責的智慧代理尚未啟用。",
  answerEmergency: "緊急停止已啟用。解除後請重新整理。",
  answerQuestionLabel: "已記錄的問題",
  answerQuestionError: "無法載入問題。草稿已保留。",
  answerPendingHelp:
    "在送達狀態確定前，已儲存的回答將保持鎖定。檢查不會再次送出回答。",
  unavailable: "無法取得",
  recordsMissing: "無法載入活動紀錄。",
  tasksMissing: "無法載入子工作。",
  tasksLoading: "正在載入子工作…",
  tasksStale: "無法重新整理子工作。顯示上次取得的清單。",
  completedWork: "已載入子工作完成數",
  recordStatus: "記錄狀態",
  invalidTitle: "專案網址無效",
  invalidHelp: "此連結不包含有效的專案 ID。",
  missingTitle: "找不到專案",
  missingHelp: "專案 #{id} 可能已刪除或尚未建立。",
  loadError: "無法載入專案",
  loadHelp: "無法取得專案詳細資料。請檢查連線後重試。",
  stale: "重新整理失敗。顯示上次載入的專案；開始操作前請檢查目前狀態。",
  snapshot: "上次取得：{time}",
  retry: "重試",
  back: "返回專案",
  parent: "上層專案",
  operations: "專案作業",
  stop: "停止",
  stopTitle: "停止此工作？",
  stopHelp:
    "停止「{title}」及其進行中的子工作。已完成的外部操作不會撤銷，紀錄會保留。",
  dismiss: "取消",
  confirmStop: "停止工作",
  stopping: "正在等待停止結果…",
  stopped: "已記錄停止",
  unknownStop: "停止結果尚未確認",
  unknownHelp: "請求可能已送達伺服器。檢查狀態不會再次傳送停止請求。",
  checkState: "檢查狀態",
  checking: "正在檢查…",
  activeAfterCheck:
    "上次檢查顯示工作仍在進行。先前請求的結果未知。你可以另行確認再次停止。",
  reviewStop: "重新確認停止",
  terminalObserved: "伺服器狀態：{status}。此檢查本身無法證明先前請求的結果。",
  storageError: "無法在此分頁儲存停止紀錄；未傳送請求。請檢查瀏覽器儲存空間。",
  continuous: "持續執行 · {count} 個週期",
  finite: "有限工作",
  mode: "{name} 模式",
  low: "低",
  normal: "一般",
  high: "高",
  urgent: "緊急",
  warning: "最近的工作警告",
  source: "原始紀錄文字",
  nextAttempt: "下次嘗試：{time}",
  partial: "部分專案資訊無法取得：{sections}。",
  plan: "工作計畫",
  experts: "專家名單",
  team: "專案團隊",
  chatMissing: "專案對話無法使用",
  ownerMissing: "無法確認協調者。請檢查目前專案及團隊資訊。",
  members: "團隊成員：{count}",
  memberLabel: "專案團隊成員",
  emptyTeam: "尚無團隊資訊。",
  coordinatorHelp: "{name} 負責協調，整個團隊都可參與。",
  loading: "正在載入專案工作室",
  tabs: "專案工作區檢視",
  workspace: "工作區",
  planTab: "計畫與軌跡",
  meetings: "會議",
  teamTab: "團隊",
  evidence: "交付",
  rosterHelp: "此專案記錄的團隊",
  coordinator: "協調者",
  workCount: "工作：{count}",
  inTeam: "團隊成員",
  inactive: "未啟用",
  planHelp: "已記錄的子工作及其上次載入的狀態",
  steps: "步驟：{count}",
  noTasks: "尚無子工作",
  noTasksHelp: "專家將計畫儲存為工作後，會顯示於此。",
  expertId: "專家 #{id}",
  records: "活動紀錄",
  recordsHelp: "伺服器記錄的最近 {count} 項活動。此視窗可能不含較早的歷程。",
  recordsLoading: "正在載入紀錄",
  recordsError: "無法重新整理活動。保留上次載入的紀錄。",
  noRecords: "尚無工作紀錄",
  runSummary: "紀錄摘要",
  progress: "進度",
  attempts: "工作嘗試",
  tokens: "Token",
  model: "記錄的模型",
  unknownModel: "未記錄模型",
  deliveryHelp: "這是代理儲存的交付摘要。可在「{tab}」分頁查看驗證紀錄。",
  reviewDelivery: "查看證據",
  cycleDeliveryNote: "這是最近儲存的週期摘要。定期任務的目前狀態顯示於上方。",
  deliverySummary: "交付摘要",
  noDelivery: "尚未記錄交付摘要。儲存後會顯示於此。",
};
export default copy;
