import type { TraceCopy } from "../trace-copy";
const copy: TraceCopy = {
  title: "Activity records",
  help: "Stored task facts and the selected activity page. A record does not establish that a stage passed or an operation succeeded.",
  loading: "Loading records…",
  error: "Records could not be loaded.",
  stale: "Refresh failed. The last loaded records remain visible.",
  snapshot: "Loaded activity window",
  retry: "Try again",
  export: "Download activity JSON",
  exportHelp:
    "Includes original summaries and allowlisted metadata. Review the file before sharing.",
  operations: "Open operation receipts",
  window:
    "Up to {limit} activity records on the selected page. Counts, filters and the export cover this page. Use the page controls to read older records.",
  range: "Loaded range",
  unknown: "Unknown",
  empty: "No activity records in the loaded window.",
  noMatch: "No records match this filter.",
  all: "All",
  people: "Assignments",
  tools: "Tools",
  gates: "Reviews and approvals",
  issues: "Issues",
  records: "Records",
  toolRecords: "Tool-related records",
  judges: "Review records",
  participants: "Referenced agents",
  model: "Last recorded model",
  steps: "Step counter",
  cycles: "Cycle counter",
  categories: "Recorded facts",
  intake: "Request",
  plan: "Planning",
  route: "Ownership",
  execute: "Work",
  review: "Review",
  deliver: "Result",
  created: "Task creation is recorded.",
  owned: "Current owner is recorded in the task.",
  planningRecorded: "A planning status was recorded.",
  executionRecorded: "A progress or tool activity was recorded.",
  reviewRecorded: "A review or approval activity was recorded.",
  summaryStored: "A result summary is stored.",
  markedCompleted: "The task is marked completed; no result summary is stored.",
  missing: "No matching record in the loaded window.",
  taskSource: "Task snapshot",
  activitySource: "Activity record",
  source: "Source",
  record: "Record",
  agent: "Agent #{id}",
  system: "System",
  detail: "Record details",
  noDetail: "No allowlisted detail fields in this record.",
  yes: "Yes",
  no: "No",
  delegations: "Delegation records",
  delegationHelp:
    "Stored briefs and activity summaries, shown in their original language. Agent association does not establish who authored the text.",
  delegationLimit:
    "Assigned tasks from the loaded page of up to {tasks} direct children, plus this task if assigned. Up to {events} activities per page for the selected task. Older pages pause automatic refresh.",
  noDelegations: "No delegated tasks in the loaded list.",
  taskListError:
    "The child-task list could not be refreshed. This view may be incomplete.",
  manager: "Assigned by",
  owner: "Current owner",
  assignment: "Assignment brief",
  accepted: "Acceptance record",
  progress: "Progress record",
  response: "Work note",
  completed: "Completion record",
  status: "Current task status",
  lastUpdated: "Task snapshot updated",
  info: "Information",
  warning: "Warning",
  critical: "Critical",
  fields: {
    status: "Status",
    outcome: "Outcome",
    taskDisposition: "Task disposition",
    progressPercent: "Progress",
    delegationLifecycle: "Delegation lifecycle",
    fromAgentId: "From agent",
    toAgentId: "To agent",
    newAgentId: "New agent",
    parentTaskId: "Parent task",
    completedSubtaskId: "Completed subtask",
    selectedTool: "Selected tool",
    tool: "Tool",
    toolName: "Tool name",
    surface: "Surface",
    previousSurface: "Previous surface",
    phase: "Phase",
    lifecyclePhase: "Lifecycle phase",
    transition: "Transition",
    sequence: "Sequence",
    durationMs: "Recorded duration",
    commandName: "Command type",
    commandChars: "Command length",
    exitCode: "Exit code",
    outputStored: "Output stored",
    count: "Count",
    verdict: "Verdict",
    modelId: "Model",
    primaryModelId: "Primary model",
    fallbackModelId: "Fallback model",
    nextModelId: "Next model",
    provider: "Provider",
    fallbackProvider: "Fallback provider",
    usedModelFallback: "Model fallback used",
    freeOnly: "Free only",
    failureKind: "Failure kind",
    attempt: "Attempt counter",
    consecutiveFailures: "Consecutive failures",
    remainsActive: "Remains active",
    runtimeEvent: "Runtime event",
    guard: "Guard",
    category: "Approval category",
    approvalId: "Approval",
    actionQueued: "Action queued",
    autonomyMode: "Autonomy mode",
    cadenceSeconds: "Cycle interval",
    nextAttemptAt: "Next attempt",
    nextRunAt: "Next run",
    expiresAt: "Expiry",
    url: "Address",
    "scope.toolName": "Approval tool",
  },
};
export default copy;
