import type { TraceCopy } from "../trace-copy";
const copy: TraceCopy = {
  title: "活动记录",
  help: "已保存的任务信息和所选活动页。存在记录不代表某阶段已通过或操作已成功。",
  loading: "正在加载记录…",
  error: "无法加载记录。",
  stale: "刷新失败，仍显示上次加载的记录。",
  snapshot: "已加载的活动范围",
  retry: "重试",
  export: "下载活动 JSON",
  evidenceExport: "下载可分享的证据包",
  evidenceHelp:
    "仅包含一页活动的记录 ID、状态和计数，不含任务文本、摘要、命令或原始工具数据。校验和可发现意外修改，但不能证明作者身份或任务成功。",
  evidenceError: "无法生成证据包，请重试。",
  exportHelp: "包含原始摘要和允许公开的元数据。分享前请检查文件。",
  operations: "打开操作回执",
  window:
    "所选页面最多包含 {limit} 条活动记录。计数、筛选和导出仅涵盖此页。使用翻页控件查看较早的记录。",
  range: "已加载的时间范围",
  unknown: "未知",
  empty: "已加载范围内没有活动记录。",
  noMatch: "没有符合此筛选条件的记录。",
  all: "全部",
  people: "分配",
  tools: "工具",
  gates: "检查与审批",
  issues: "问题",
  records: "记录",
  toolRecords: "工具相关记录",
  judges: "检查记录",
  participants: "涉及的智能体",
  model: "最近记录的模型",
  steps: "步骤计数",
  cycles: "周期计数",
  categories: "已记录的信息",
  intake: "请求",
  plan: "规划",
  route: "负责人",
  execute: "工作",
  review: "检查",
  deliver: "结果",
  created: "已记录任务创建。",
  owned: "任务中已记录当前负责人。",
  planningRecorded: "已记录规划状态。",
  executionRecorded: "已记录进度或工具活动。",
  reviewRecorded: "已记录检查或审批活动。",
  summaryStored: "已保存结果摘要。",
  markedCompleted: "任务已标记为完成，但未保存结果摘要。",
  missing: "已加载范围内没有匹配的记录。",
  taskSource: "任务快照",
  activitySource: "活动记录",
  source: "来源",
  record: "记录",
  agent: "智能体 #{id}",
  system: "系统",
  detail: "记录详情",
  noDetail: "此记录没有可显示的允许字段。",
  yes: "是",
  no: "否",
  delegations: "委派记录",
  delegationHelp:
    "以原始语言显示已保存的任务说明和活动摘要。与智能体关联不代表该智能体撰写了文本。",
  delegationLimit:
    "显示已加载页面中最多 {tasks} 个直属子任务里的已分配任务；若当前任务已分配，也会列出。所选任务每页最多显示 {events} 条活动。查看较早的页面时，自动刷新暂停。",
  noDelegations: "已加载列表中没有委派任务。",
  taskListError: "无法刷新子任务列表，此视图可能不完整。",
  manager: "分配者",
  owner: "当前负责人",
  assignment: "任务分配说明",
  accepted: "接受记录",
  progress: "进度记录",
  response: "工作备注",
  completed: "完成记录",
  status: "当前任务状态",
  lastUpdated: "任务快照更新于",
  info: "信息",
  warning: "警告",
  critical: "严重",
  fields: {
    status: "状态",
    outcome: "结果",
    taskDisposition: "任务处置",
    progressPercent: "进度",
    delegationLifecycle: "委派状态",
    fromAgentId: "发送智能体",
    toAgentId: "接收智能体",
    newAgentId: "新智能体",
    parentTaskId: "父任务",
    completedSubtaskId: "已完成子任务",
    selectedTool: "所选工具",
    tool: "工具",
    toolName: "工具名称",
    surface: "工作环境",
    previousSurface: "上一个环境",
    phase: "阶段",
    lifecyclePhase: "生命周期阶段",
    transition: "切换",
    sequence: "序号",
    durationMs: "记录的时长",
    commandName: "命令类型",
    commandChars: "命令长度",
    exitCode: "退出码",
    outputStored: "输出已保存",
    count: "数量",
    verdict: "判定",
    modelId: "模型",
    primaryModelId: "主模型",
    fallbackModelId: "备用模型",
    nextModelId: "下一个模型",
    provider: "提供商",
    fallbackProvider: "备用提供商",
    usedModelFallback: "已使用备用模型",
    freeOnly: "仅免费",
    failureKind: "故障类型",
    attempt: "尝试计数",
    consecutiveFailures: "连续失败",
    remainsActive: "仍处于活动状态",
    runtimeEvent: "运行事件",
    guard: "保护机制",
    category: "审批类别",
    approvalId: "审批",
    actionQueued: "操作已排队",
    autonomyMode: "自主模式",
    cadenceSeconds: "周期间隔",
    nextAttemptAt: "下次尝试",
    nextRunAt: "下次运行",
    expiresAt: "到期时间",
    url: "地址",
    "scope.toolName": "审批工具",
  },
};
export default copy;
