import type { TraceCopy } from "../trace-copy";
const copy: TraceCopy = {
  title: "Faaliyet kayıtları",
  help: "Kayıtlı görev bilgileri ve seçili faaliyet sayfası. Bir kaydın bulunması, aşamanın geçtiğini veya işlemin başarılı olduğunu kanıtlamaz.",
  loading: "Kayıtlar yükleniyor…",
  error: "Kayıtlar yüklenemedi.",
  stale: "Yenileme başarısız. Son yüklenen kayıtlar gösteriliyor.",
  snapshot: "Yüklenen faaliyet aralığı",
  retry: "Yeniden dene",
  export: "Faaliyet JSON dosyasını indir",
  exportHelp:
    "Özgün özetleri ve izin verilen üst verileri içerir. Paylaşmadan önce dosyayı gözden geçir.",
  operations: "İşlem makbuzlarını aç",
  window:
    "Seçili sayfada en fazla {limit} faaliyet kaydı. Sayılar, filtreler ve dışa aktarma bu sayfayı kapsar. Eski kayıtlara sayfa kontrolleriyle ulaşabilirsiniz.",
  range: "Yüklenen zaman aralığı",
  unknown: "Bilinmiyor",
  empty: "Yüklenen aralıkta faaliyet kaydı yok.",
  noMatch: "Bu filtreyle eşleşen kayıt yok.",
  all: "Tümü",
  people: "Atamalar",
  tools: "Araçlar",
  gates: "Denetimler ve onaylar",
  issues: "Sorunlar",
  records: "Kayıtlar",
  toolRecords: "Araçla ilgili kayıtlar",
  judges: "Denetim kayıtları",
  participants: "Kaydı geçen ajanlar",
  model: "Son kaydedilen model",
  steps: "Adım sayacı",
  cycles: "Döngü sayacı",
  categories: "Kayıtlı bilgiler",
  intake: "Talep",
  plan: "Planlama",
  route: "Sorumluluk",
  execute: "Çalışma",
  review: "Denetim",
  deliver: "Sonuç",
  created: "Görevin oluşturulması kayıtlı.",
  owned: "Güncel sorumlu görevde kayıtlı.",
  planningRecorded: "Bir planlama durumu kaydedilmiş.",
  executionRecorded: "Bir ilerleme veya araç faaliyeti kaydedilmiş.",
  reviewRecorded: "Bir denetim veya onay faaliyeti kaydedilmiş.",
  summaryStored: "Bir sonuç özeti saklanıyor.",
  markedCompleted: "Görev tamamlandı olarak işaretli; kayıtlı sonuç özeti yok.",
  missing: "Yüklenen aralıkta eşleşen kayıt yok.",
  taskSource: "Görev görüntüsü",
  activitySource: "Faaliyet kaydı",
  source: "Kaynak",
  record: "Kayıt",
  agent: "Ajan #{id}",
  system: "Sistem",
  detail: "Kayıt ayrıntıları",
  noDetail: "Bu kayıtta gösterilebilecek izinli ayrıntı alanı yok.",
  yes: "Evet",
  no: "Hayır",
  delegations: "Devir kayıtları",
  delegationHelp:
    "Saklanan talimatlar ve faaliyet özetleri özgün dilinde gösterilir. Ajanla ilişkilendirme, metni kimin yazdığını kanıtlamaz.",
  delegationLimit:
    "Yüklenen sayfadaki en fazla {tasks} doğrudan alt görev arasından atananlar ve atanmışsa bu görev gösterilir. Seçili görev için sayfa başına en fazla {events} faaliyet bulunur. Eski sayfalarda otomatik yenileme durur.",
  noDelegations: "Yüklenen listede devredilmiş görev yok.",
  taskListError: "Alt görev listesi yenilenemedi. Bu görünüm eksik olabilir.",
  manager: "Atayan",
  owner: "Güncel sorumlu",
  assignment: "Atama talimatı",
  accepted: "Kabul kaydı",
  progress: "İlerleme kaydı",
  response: "Çalışma notu",
  completed: "Tamamlanma kaydı",
  status: "Güncel görev durumu",
  lastUpdated: "Görev görüntüsü güncellendi",
  info: "Bilgi",
  warning: "Uyarı",
  critical: "Kritik",
  fields: {
    status: "Durum",
    outcome: "Sonuç",
    taskDisposition: "Görev sonucu",
    progressPercent: "İlerleme",
    delegationLifecycle: "Devir durumu",
    fromAgentId: "Gönderen ajan",
    toAgentId: "Alan ajan",
    newAgentId: "Yeni ajan",
    parentTaskId: "Üst görev",
    completedSubtaskId: "Tamamlanan alt görev",
    selectedTool: "Seçilen araç",
    tool: "Araç",
    toolName: "Araç adı",
    surface: "Çalışma yüzeyi",
    previousSurface: "Önceki yüzey",
    phase: "Aşama",
    lifecyclePhase: "Yaşam döngüsü aşaması",
    transition: "Geçiş",
    sequence: "Sıra",
    durationMs: "Kaydedilen süre",
    commandName: "Komut türü",
    commandChars: "Komut uzunluğu",
    exitCode: "Çıkış kodu",
    outputStored: "Çıktı saklandı",
    count: "Sayı",
    verdict: "Karar",
    modelId: "Model",
    primaryModelId: "Birincil model",
    fallbackModelId: "Yedek model",
    nextModelId: "Sonraki model",
    provider: "Sağlayıcı",
    fallbackProvider: "Yedek sağlayıcı",
    usedModelFallback: "Yedek model kullanıldı",
    freeOnly: "Yalnız ücretsiz",
    failureKind: "Hata türü",
    attempt: "Deneme sayacı",
    consecutiveFailures: "Ardışık hatalar",
    remainsActive: "Etkin kalıyor",
    runtimeEvent: "Çalışma olayı",
    guard: "Koruma",
    category: "Onay kategorisi",
    approvalId: "Onay",
    actionQueued: "İşlem sıraya alındı",
    autonomyMode: "Özerklik modu",
    cadenceSeconds: "Döngü aralığı",
    nextAttemptAt: "Sonraki deneme",
    nextRunAt: "Sonraki çalışma",
    expiresAt: "Sona erme",
    url: "Adres",
    "scope.toolName": "Onay aracı",
  },
};
export default copy;
