import type { TraceCopy } from "../trace-copy";
const copy: TraceCopy = {
  reviewEvidence: {
    loadError: "無法載入審核詳情。請重新整理頁面再試一次。",
    title: "審核依據",
    help: "審核時的紀錄，並非即時狀態或輸出品質保證。不包含命令、原始輸出或子任務報告。",
    cycle: "審核的週期",
    operations: "操作紀錄",
    children: "子任務",
    counts: "審核快照中的紀錄數量",
    countsHelp: "數量包含下方簡短清單中未顯示的紀錄，不包含較早的任務週期。",
    receipts: "操作樣本",
    childSample: "子任務樣本",
    limited: "顯示 {shown} 筆，共 {total} 筆。其餘或無法讀取的紀錄未顯示。",
    empty: "此次審核沒有操作或子任務紀錄。純文字任務也可以不使用工具。",
    taskStep: "任務操作",
    approvedAction: "已核准的操作",
    resultFlag: "回報的成功標記",
    confirmedApplied: "操作人員確認已執行",
    confirmedNotApplied: "操作人員確認未執行",
    states: {
      reserved: "已保留",
      running: "執行中",
      succeeded: "成功",
      failed: "失敗",
      unknown: "結果未知",
      pending: "待處理",
      planning: "規劃中",
      in_progress: "進行中",
      awaiting_approval: "等待核准",
      blocked: "已阻止",
      completed: "已完成",
      cancelled: "已取消",
    },
  },
  title: "活動紀錄",
  help: "已儲存的任務資訊與所選活動頁。存在紀錄不代表某階段已通過或操作已成功。",
  loading: "正在載入紀錄…",
  error: "無法載入紀錄。",
  stale: "重新整理失敗，仍顯示上次載入的紀錄。",
  snapshot: "已載入的活動範圍",
  retry: "重試",
  export: "下載活動 JSON",
  evidenceExport: "下載可分享的證據包",
  evidenceHelp:
    "僅包含一頁活動的紀錄 ID、狀態和計數，不含任務文字、摘要、命令或原始工具資料。校驗碼可發現意外修改，但無法證明作者身分或任務成功。",
  evidenceError: "無法產生證據包，請重試。",
  exportHelp: "包含原始摘要與允許公開的中繼資料。分享前請檢查檔案。",
  operations: "開啟操作回執",
  window:
    "所選頁面最多包含 {limit} 筆活動紀錄。計數、篩選和匯出僅涵蓋此頁。使用翻頁控制項查看較早的紀錄。",
  range: "已載入的時間範圍",
  unknown: "未知",
  empty: "已載入範圍內沒有活動紀錄。",
  noMatch: "沒有符合此篩選條件的紀錄。",
  all: "全部",
  people: "指派",
  tools: "工具",
  gates: "檢查與審批",
  issues: "問題",
  records: "紀錄",
  toolRecords: "工具相關紀錄",
  judges: "檢查紀錄",
  participants: "涉及的代理",
  model: "最近記錄的模型",
  steps: "步驟計數",
  cycles: "週期計數",
  categories: "已記錄的資訊",
  intake: "請求",
  plan: "規劃",
  route: "負責人",
  execute: "工作",
  review: "檢查",
  deliver: "結果",
  created: "已記錄任務建立。",
  owned: "任務中已記錄目前負責人。",
  planningRecorded: "已記錄規劃狀態。",
  executionRecorded: "已記錄進度或工具活動。",
  reviewRecorded: "已記錄檢查或審批活動。",
  summaryStored: "已儲存結果摘要。",
  markedCompleted: "任務已標記為完成，但未儲存結果摘要。",
  missing: "已載入範圍內沒有符合的紀錄。",
  taskSource: "任務快照",
  activitySource: "活動紀錄",
  source: "來源",
  record: "紀錄",
  agent: "代理 #{id}",
  system: "系統",
  detail: "紀錄詳細資料",
  noDetail: "此紀錄沒有可顯示的允許欄位。",
  yes: "是",
  no: "否",
  delegations: "委派紀錄",
  delegationHelp:
    "以原始語言顯示已儲存的任務說明與活動摘要。與代理關聯不代表該代理撰寫了文字。",
  delegationLimit:
    "顯示已載入頁面中最多 {tasks} 個直屬子任務裡的已指派任務；若目前任務已指派，也會列出。所選任務每頁最多顯示 {events} 筆活動。查看較早的頁面時，自動重新整理會暫停。",
  noDelegations: "已載入清單中沒有委派任務。",
  taskListError: "無法重新整理子任務清單，此檢視可能不完整。",
  manager: "指派者",
  owner: "目前負責人",
  assignment: "任務指派說明",
  accepted: "接受紀錄",
  progress: "進度紀錄",
  response: "工作備註",
  completed: "完成紀錄",
  status: "目前任務狀態",
  lastUpdated: "任務快照更新於",
  info: "資訊",
  warning: "警告",
  critical: "嚴重",
  fields: {
    status: "狀態",
    outcome: "結果",
    taskDisposition: "任務處置",
    progressPercent: "進度",
    delegationLifecycle: "委派狀態",
    fromAgentId: "傳送代理",
    toAgentId: "接收代理",
    newAgentId: "新代理",
    parentTaskId: "父任務",
    completedSubtaskId: "已完成子任務",
    selectedTool: "所選工具",
    tool: "工具",
    toolName: "工具名稱",
    surface: "工作環境",
    previousSurface: "上一個環境",
    phase: "階段",
    lifecyclePhase: "生命週期階段",
    transition: "切換",
    sequence: "序號",
    durationMs: "記錄的時長",
    commandName: "命令類型",
    commandChars: "命令長度",
    exitCode: "結束代碼",
    outputStored: "輸出已儲存",
    count: "數量",
    verdict: "判定",
    modelId: "模型",
    primaryModelId: "主要模型",
    fallbackModelId: "備用模型",
    nextModelId: "下一個模型",
    provider: "供應商",
    fallbackProvider: "備用供應商",
    usedModelFallback: "已使用備用模型",
    freeOnly: "僅免費",
    failureKind: "故障類型",
    attempt: "嘗試計數",
    consecutiveFailures: "連續失敗",
    remainsActive: "仍處於活動狀態",
    runtimeEvent: "執行事件",
    guard: "保護機制",
    category: "審批類別",
    approvalId: "審批",
    actionQueued: "操作已排入佇列",
    autonomyMode: "自主模式",
    cadenceSeconds: "週期間隔",
    nextAttemptAt: "下次嘗試",
    nextRunAt: "下次執行",
    expiresAt: "到期時間",
    url: "位址",
    "scope.toolName": "審批工具",
  },
};
export default copy;
