import type { TraceCopy } from "../trace-copy";
const copy: TraceCopy = {
  reviewEvidence: {
    loadError:
      "Die Prüfungsdetails konnten nicht geladen werden. Laden Sie die Seite neu, um es erneut zu versuchen.",
    title: "Grundlage der Prüfung",
    help: "Aufzeichnungen zum Prüfzeitpunkt, kein Live-Status und keine Garantie für die Ergebnisqualität. Befehle, Rohausgaben und Unteraufgabenberichte sind ausgeschlossen.",
    cycle: "Geprüfter Zyklus",
    operations: "Vorgangsaufzeichnungen",
    children: "Unteraufgaben",
    counts: "Anzahl im Prüfungssnapshot",
    countsHelp:
      "Die Zahlen umfassen auch Aufzeichnungen außerhalb der kurzen Auszüge. Frühere Aufgabenzyklen sind ausgeschlossen.",
    receipts: "Ausgewählte Vorgänge",
    childSample: "Ausgewählte Unteraufgaben",
    limited:
      "{shown} von {total} werden angezeigt. Weitere oder nicht lesbare Aufzeichnungen werden nicht angezeigt.",
    empty:
      "Für diese Prüfung wurden keine Vorgänge oder Unteraufgaben aufgezeichnet. Reine Textaufgaben können ohne Werkzeuge gültig sein.",
    taskStep: "Aufgabenvorgang",
    approvedAction: "Genehmigte Aktion",
    resultFlag: "Gemeldetes Erfolgskennzeichen",
    confirmedApplied: "Bediener hat Ausführung bestätigt",
    confirmedNotApplied: "Bediener hat Nichtausführung bestätigt",
    states: {
      reserved: "Reserviert",
      running: "Läuft",
      succeeded: "Erfolgreich",
      failed: "Fehlgeschlagen",
      unknown: "Ergebnis ungewiss",
      pending: "Ausstehend",
      planning: "In Planung",
      in_progress: "In Bearbeitung",
      awaiting_approval: "Wartet auf Genehmigung",
      blocked: "Blockiert",
      completed: "Abgeschlossen",
      cancelled: "Abgebrochen",
    },
  },
  title: "Aktivitätsaufzeichnungen",
  help: "Gespeicherte Aufgabendaten und die ausgewählte Aktivitätsseite. Ein Eintrag belegt weder eine bestandene Phase noch eine erfolgreiche Ausführung.",
  loading: "Aufzeichnungen werden geladen…",
  error: "Aufzeichnungen konnten nicht geladen werden.",
  stale:
    "Aktualisierung fehlgeschlagen. Die zuletzt geladenen Aufzeichnungen bleiben sichtbar.",
  snapshot: "Geladenes Aktivitätsfenster",
  retry: "Erneut versuchen",
  export: "Aktivitäten als JSON herunterladen",
  evidenceExport: "Teilbare Nachweise herunterladen",
  evidenceHelp:
    "Eine Aktivitätsseite mit Datensatz-IDs, Status und Zahlen. Ohne Aufgabentext, Zusammenfassungen, Befehle oder rohe Werkzeugdaten. Die Prüfsumme erkennt versehentliche Änderungen; sie beweist weder Urheberschaft noch Aufgabenerfolg.",
  evidenceError:
    "Nachweise konnten nicht erstellt werden. Bitte erneut versuchen.",
  exportHelp:
    "Enthält Originalzusammenfassungen und zugelassene Metadaten. Datei vor dem Teilen prüfen.",
  operations: "Ausführungsbelege öffnen",
  window:
    "Bis zu {limit} Aktivitäten auf der ausgewählten Seite. Zähler, Filter und Export gelten für diese Seite. Ältere Einträge erreichen Sie über die Seitennavigation.",
  range: "Geladener Zeitraum",
  unknown: "Unbekannt",
  empty: "Keine Aktivitäten im geladenen Zeitraum.",
  noMatch: "Keine Einträge für diesen Filter.",
  all: "Alle",
  people: "Zuweisungen",
  tools: "Werkzeuge",
  gates: "Prüfungen und Freigaben",
  issues: "Probleme",
  records: "Einträge",
  toolRecords: "Werkzeugbezogene Einträge",
  judges: "Prüfeinträge",
  participants: "Referenzierte Agenten",
  model: "Zuletzt erfasstes Modell",
  steps: "Schrittzähler",
  cycles: "Zykluszähler",
  categories: "Erfasste Fakten",
  intake: "Anfrage",
  plan: "Planung",
  route: "Zuständigkeit",
  execute: "Arbeit",
  review: "Prüfung",
  deliver: "Ergebnis",
  created: "Die Aufgabenerstellung ist erfasst.",
  owned: "Der aktuelle Verantwortliche ist in der Aufgabe erfasst.",
  planningRecorded: "Ein Planungsstatus wurde erfasst.",
  executionRecorded: "Eine Fortschritts- oder Werkzeugaktivität wurde erfasst.",
  reviewRecorded: "Eine Prüfungs- oder Freigabeaktivität wurde erfasst.",
  summaryStored: "Eine Ergebniszusammenfassung ist gespeichert.",
  markedCompleted:
    "Die Aufgabe ist als abgeschlossen markiert; eine Ergebniszusammenfassung fehlt.",
  missing: "Kein passender Eintrag im geladenen Zeitraum.",
  taskSource: "Aufgabenstand",
  activitySource: "Aktivitätseintrag",
  source: "Quelle",
  record: "Eintrag",
  agent: "Agent #{id}",
  system: "System",
  detail: "Einzelheiten zum Eintrag",
  noDetail: "Keine zugelassenen Detailfelder in diesem Eintrag.",
  yes: "Ja",
  no: "Nein",
  delegations: "Delegationsaufzeichnungen",
  delegationHelp:
    "Gespeicherte Anweisungen und Aktivitätszusammenfassungen in der Originalsprache. Die Zuordnung zu einem Agenten belegt nicht die Urheberschaft.",
  delegationLimit:
    "Zugewiesene Aufgaben aus der geladenen Seite mit bis zu {tasks} direkten Unteraufgaben, ergänzt um diese Aufgabe, sofern sie zugewiesen wurde. Bis zu {events} Aktivitäten pro Seite für die ausgewählte Aufgabe. Auf älteren Seiten pausiert die automatische Aktualisierung.",
  noDelegations: "Keine delegierten Aufgaben in der geladenen Liste.",
  taskListError:
    "Die Unteraufgabenliste konnte nicht aktualisiert werden. Diese Ansicht kann unvollständig sein.",
  manager: "Zugewiesen von",
  owner: "Aktuell verantwortlich",
  assignment: "Zuweisungsanweisung",
  accepted: "Annahme vermerkt",
  progress: "Fortschritt vermerkt",
  response: "Arbeitsnotiz",
  completed: "Abschluss vermerkt",
  status: "Aktueller Aufgabenstatus",
  lastUpdated: "Aufgabenstand aktualisiert",
  info: "Information",
  warning: "Warnung",
  critical: "Kritisch",
  fields: {
    status: "Status",
    outcome: "Ergebnis",
    taskDisposition: "Aufgabenergebnis",
    progressPercent: "Fortschritt",
    delegationLifecycle: "Delegationsstatus",
    fromAgentId: "Von Agent",
    toAgentId: "An Agent",
    newAgentId: "Neuer Agent",
    parentTaskId: "Übergeordnete Aufgabe",
    completedSubtaskId: "Abgeschlossene Unteraufgabe",
    selectedTool: "Ausgewähltes Werkzeug",
    tool: "Werkzeug",
    toolName: "Werkzeugname",
    surface: "Arbeitsoberfläche",
    previousSurface: "Vorherige Oberfläche",
    phase: "Phase",
    lifecyclePhase: "Lebenszyklusphase",
    transition: "Übergang",
    sequence: "Reihenfolge",
    durationMs: "Erfasste Dauer",
    commandName: "Befehlstyp",
    commandChars: "Befehlslänge",
    exitCode: "Exit-Code",
    outputStored: "Ausgabe gespeichert",
    count: "Anzahl",
    verdict: "Entscheidung",
    modelId: "Modell",
    primaryModelId: "Primäres Modell",
    fallbackModelId: "Ersatzmodell",
    nextModelId: "Nächstes Modell",
    provider: "Anbieter",
    fallbackProvider: "Ersatzanbieter",
    usedModelFallback: "Ersatzmodell verwendet",
    freeOnly: "Nur kostenlos",
    failureKind: "Fehlerart",
    attempt: "Versuchszähler",
    consecutiveFailures: "Aufeinanderfolgende Fehler",
    remainsActive: "Bleibt aktiv",
    runtimeEvent: "Laufzeitereignis",
    guard: "Schutz",
    category: "Freigabekategorie",
    approvalId: "Freigabe",
    actionQueued: "Aktion eingereiht",
    autonomyMode: "Autonomiemodus",
    cadenceSeconds: "Zyklusintervall",
    nextAttemptAt: "Nächster Versuch",
    nextRunAt: "Nächste Ausführung",
    expiresAt: "Ablauf",
    url: "Adresse",
    "scope.toolName": "Freigabewerkzeug",
  },
};
export default copy;
