import type { TraceCopy } from "../trace-copy";
const copy: TraceCopy = {
  title: "سجلات النشاط",
  help: "بيانات المهمة المحفوظة وصفحة الأنشطة المحددة. وجود سجل لا يثبت اجتياز مرحلة أو نجاح عملية.",
  loading: "جارٍ تحميل السجلات…",
  error: "تعذّر تحميل السجلات.",
  stale: "فشل التحديث. تظل آخر سجلات محمّلة ظاهرة.",
  snapshot: "نطاق النشاط المحمّل",
  retry: "إعادة المحاولة",
  export: "تنزيل النشاط بصيغة JSON",
  exportHelp:
    "يتضمن الملخصات الأصلية والبيانات الوصفية المسموح بها. راجع الملف قبل مشاركته.",
  operations: "فتح إيصالات العمليات",
  window:
    "حتى {limit} سجل نشاط في الصفحة المحددة. الأعداد والتصفية والتصدير تخص هذه الصفحة. استخدم أزرار التنقل لقراءة السجلات الأقدم.",
  range: "الفترة المحمّلة",
  unknown: "غير معروف",
  empty: "لا توجد سجلات نشاط في النطاق المحمّل.",
  noMatch: "لا توجد سجلات تطابق هذا المرشح.",
  all: "الكل",
  people: "التكليفات",
  tools: "الأدوات",
  gates: "المراجعات والموافقات",
  issues: "المشكلات",
  records: "السجلات",
  toolRecords: "سجلات مرتبطة بالأدوات",
  judges: "سجلات المراجعة",
  participants: "الوكلاء المذكورون",
  model: "آخر نموذج مسجّل",
  steps: "عدّاد الخطوات",
  cycles: "عدّاد الدورات",
  categories: "البيانات المسجّلة",
  intake: "الطلب",
  plan: "التخطيط",
  route: "المسؤولية",
  execute: "العمل",
  review: "المراجعة",
  deliver: "النتيجة",
  created: "إنشاء المهمة مسجّل.",
  owned: "المسؤول الحالي مسجّل في المهمة.",
  planningRecorded: "سُجّلت حالة تخطيط.",
  executionRecorded: "سُجّل نشاط تقدّم أو أداة.",
  reviewRecorded: "سُجّل نشاط مراجعة أو موافقة.",
  summaryStored: "ملخص النتيجة محفوظ.",
  markedCompleted: "المهمة معلّمة كمكتملة؛ لا يوجد ملخص نتيجة محفوظ.",
  missing: "لا يوجد سجل مطابق في النطاق المحمّل.",
  taskSource: "لقطة المهمة",
  activitySource: "سجل نشاط",
  source: "المصدر",
  record: "السجل",
  agent: "الوكيل #{id}",
  system: "النظام",
  detail: "تفاصيل السجل",
  noDetail: "لا توجد حقول تفاصيل مسموح بها في هذا السجل.",
  yes: "نعم",
  no: "لا",
  delegations: "سجلات التفويض",
  delegationHelp:
    "تُعرض التعليمات المحفوظة وملخصات النشاط بلغتها الأصلية. الارتباط بوكيل لا يثبت أنه كتب النص.",
  delegationLimit:
    "المهام المسندة من الصفحة المحمّلة التي تضم حتى {tasks} مهمة فرعية مباشرة، إضافة إلى هذه المهمة إذا كانت مسندة. حتى {events} سجل نشاط في كل صفحة للمهمة المحددة. يتوقف التحديث التلقائي عند عرض الصفحات الأقدم.",
  noDelegations: "لا توجد مهام مفوّضة في القائمة المحمّلة.",
  taskListError:
    "تعذّر تحديث قائمة المهام الفرعية. قد يكون هذا العرض غير مكتمل.",
  manager: "المكلِّف",
  owner: "المسؤول الحالي",
  assignment: "تعليمات التكليف",
  accepted: "سجل القبول",
  progress: "سجل التقدّم",
  response: "ملاحظة عمل",
  completed: "سجل الإكمال",
  status: "حالة المهمة الحالية",
  lastUpdated: "تحديث لقطة المهمة",
  info: "معلومة",
  warning: "تحذير",
  critical: "حرج",
  fields: {
    status: "الحالة",
    outcome: "النتيجة",
    taskDisposition: "نتيجة المهمة",
    progressPercent: "التقدّم",
    delegationLifecycle: "حالة التفويض",
    fromAgentId: "الوكيل المرسل",
    toAgentId: "الوكيل المستلم",
    newAgentId: "وكيل جديد",
    parentTaskId: "المهمة الأصلية",
    completedSubtaskId: "المهمة الفرعية المكتملة",
    selectedTool: "الأداة المختارة",
    tool: "الأداة",
    toolName: "اسم الأداة",
    surface: "بيئة العمل",
    previousSurface: "البيئة السابقة",
    phase: "المرحلة",
    lifecyclePhase: "مرحلة دورة الحياة",
    transition: "انتقال",
    sequence: "التسلسل",
    durationMs: "المدة المسجّلة",
    commandName: "نوع الأمر",
    commandChars: "طول الأمر",
    exitCode: "رمز الخروج",
    outputStored: "المخرجات محفوظة",
    count: "العدد",
    verdict: "القرار",
    modelId: "النموذج",
    primaryModelId: "النموذج الأساسي",
    fallbackModelId: "النموذج البديل",
    nextModelId: "النموذج التالي",
    provider: "المزوّد",
    fallbackProvider: "المزوّد البديل",
    usedModelFallback: "استُخدم النموذج البديل",
    freeOnly: "مجاني فقط",
    failureKind: "نوع الفشل",
    attempt: "عدّاد المحاولات",
    consecutiveFailures: "إخفاقات متتالية",
    remainsActive: "ما زالت نشطة",
    runtimeEvent: "حدث التشغيل",
    guard: "الحماية",
    category: "فئة الموافقة",
    approvalId: "الموافقة",
    actionQueued: "أُدرج الإجراء في الطابور",
    autonomyMode: "نمط الاستقلالية",
    cadenceSeconds: "فاصل الدورة",
    nextAttemptAt: "المحاولة التالية",
    nextRunAt: "التشغيل التالي",
    expiresAt: "انتهاء الصلاحية",
    url: "العنوان",
    "scope.toolName": "أداة الموافقة",
  },
};
export default copy;
