import type { ApprovalCopy } from "../approval-copy";
export default {
  emptyPage: "此页没有请求",
  closedPreview: "已结束的授权不显示命令预览。",
  eyebrow: "人工控制",
  title: "审批收件箱",
  description: "查看代理申请执行的操作。决定前请核对授权的确切范围。",
  pending: "待审批",
  approved: "已批准",
  rejected: "已拒绝",
  spend: "支出",
  delete: "删除",
  publish: "发布",
  external_contact: "对外联系",
  other: "其他",
  shown: "已显示的请求",
  newer: "较新的请求",
  older: "较早的请求",
  retry: "刷新请求",
  loading: "正在加载审批请求",
  loadError: "无法加载审批请求。",
  stale: "无法刷新请求。确认最新状态之前，审批决定已暂停。",
  emptyPending: "没有待审批请求",
  emptyPendingHelp: "需要你决定的新请求会显示在这里。",
  emptyApproved: "没有已批准请求",
  emptyApprovedHelp: "已批准的请求会列在这里。批准不代表已执行。",
  emptyRejected: "没有已拒绝请求",
  emptyRejectedHelp: "已拒绝和已过期的请求会列在这里。",
  requester: "申请人",
  unknownRequester: "专家",
  task: "打开任务",
  note: "决定备注",
  notePlaceholder: "可选备注，最多 2,000 个字符",
  approve: "批准",
  reject: "拒绝",
  saving: "正在保存决定…",
  approvedSaved: "已记录批准决定",
  rejectedSaved: "已记录拒绝决定",
  approvedHelp: "执行情况尚未确认。请在关联任务中跟踪结果。",
  rejectedHelp: "任务已阻止，等待下一条指令。",
  safetyStopped: "紧急停止已开启。仍可拒绝请求，批准已暂停。",
  safetyUnknown: "无法确认安全状态。仍可拒绝请求，批准已暂停。",
  scope: "仅限此确切操作的一次性授权",
  tool: "工具",
  target: "目标",
  hash: "命令摘要",
  preview: "完整预览",
  expires: "到期时间",
  consumed: "授权已使用",
  consumedHelp: "使用授权不代表操作成功。请检查任务。",
  expired: "已过期",
  noExpiry: "未指定到期时间",
  unscoped: "此请求仅记录你的决定，不授予可重复使用的工具权限。",
  source: "请求文本由代理提供。",
  missingScope: "确切范围、预览或到期时间缺失或无效。请申请新的审批。",
  hostTitle: "主机 Shell 命令",
  hostCategory: "主机访问",
  hostWarning: "此命令在代理沙盒之外，以 API 服务的操作系统账户运行。",
  hostDetails:
    "它不会提升 Windows UAC 或 Unix 权限，但可能影响该账户可访问的文件、程序和进程。请检查下方由服务器提供的命令和目标。",
  hostConfirm: "确认主机命令",
  confirmInstruction: "输入下方摘要的前 8 个字符。",
  confirmInput: "摘要的前 8 个字符",
  confirmSubmit: "批准主机命令",
  cancel: "取消",
  unknownError: "无法确认决定结果。再次决定前请刷新请求。",
  changedError: "此请求已更改或已有决定。决定前请刷新。",
  expiredError: "此授权已过期。请让代理提交新请求。",
  confirmationError: "命令摘要不匹配。请检查当前请求。",
  inputError: "无法接受该决定。请检查备注并刷新请求。",
} satisfies ApprovalCopy;
