import type { ApprovalCopy } from "../approval-copy";
export default {
  emptyPage: "此頁沒有請求",
  closedPreview: "已結束的授權不顯示命令預覽。",
  eyebrow: "人工控制",
  title: "核准收件匣",
  description: "查看代理申請執行的操作。決定前請核對授權的確切範圍。",
  pending: "待審核",
  approved: "已核准",
  rejected: "已拒絕",
  spend: "支出",
  delete: "刪除",
  publish: "發布",
  external_contact: "對外聯繫",
  other: "其他",
  shown: "已顯示的請求",
  newer: "較新的請求",
  older: "較早的請求",
  retry: "重新整理請求",
  loading: "正在載入核准請求",
  loadError: "無法載入核准請求。",
  stale: "無法重新整理請求。確認最新狀態之前，核准決定已暫停。",
  emptyPending: "沒有待審核請求",
  emptyPendingHelp: "需要你決定的新請求會顯示在這裡。",
  emptyApproved: "沒有已核准請求",
  emptyApprovedHelp: "已核准的請求會列在這裡。核准不代表已執行。",
  emptyRejected: "沒有已拒絕請求",
  emptyRejectedHelp: "已拒絕和已到期的請求會列在這裡。",
  requester: "申請人",
  unknownRequester: "專家",
  task: "開啟任務",
  note: "決定備註",
  notePlaceholder: "選填備註，最多 2,000 個字元",
  approve: "核准",
  reject: "拒絕",
  saving: "正在儲存決定…",
  approvedSaved: "已記錄核准決定",
  rejectedSaved: "已記錄拒絕決定",
  approvedHelp: "執行情況尚未確認。請在關聯任務中追蹤結果。",
  rejectedHelp: "任務已阻擋，等待下一條指示。",
  safetyStopped: "緊急停止已開啟。仍可拒絕請求，核准已暫停。",
  safetyUnknown: "無法確認安全狀態。仍可拒絕請求，核准已暫停。",
  scope: "僅限此確切操作的一次性授權",
  tool: "工具",
  target: "目標",
  hash: "命令摘要",
  preview: "完整預覽",
  expires: "到期時間",
  consumed: "授權已使用",
  consumedHelp: "使用授權不代表操作成功。請檢查任務。",
  expired: "已到期",
  noExpiry: "未指定到期時間",
  unscoped: "此請求僅記錄你的決定，不授予可重複使用的工具權限。",
  source: "請求文字由代理提供。",
  missingScope: "確切範圍、預覽或到期時間缺漏或無效。請申請新的核准。",
  hostTitle: "主機 Shell 命令",
  hostCategory: "主機存取",
  hostWarning: "此命令在代理沙盒之外，以 API 服務的作業系統帳戶執行。",
  hostDetails:
    "它不會提升 Windows UAC 或 Unix 權限，但可能影響該帳戶可存取的檔案、程式及處理程序。請檢查下方由伺服器提供的命令及目標。",
  hostConfirm: "確認主機命令",
  confirmInstruction: "輸入下方摘要的前 8 個字元。",
  confirmInput: "摘要的前 8 個字元",
  confirmSubmit: "核准主機命令",
  cancel: "取消",
  unknownError: "無法確認決定結果。再次決定前請重新整理請求。",
  changedError: "此請求已變更或已有決定。決定前請重新整理。",
  expiredError: "此授權已到期。請讓代理提交新請求。",
  confirmationError: "命令摘要不符。請檢查目前請求。",
  inputError: "無法接受該決定。請檢查備註並重新整理請求。",
} satisfies ApprovalCopy;
