import type { MeetingCopy } from "../meeting-copy";
const copy: MeetingCopy = {
  commandDetails: "Ayrıntılar",
  commandReason: "Gerekçe",
  commandDue: "Son tarih",
  commandScheduled: "Planlanan zaman",
  commandRecordedAt: "Kayıt zamanı",
  commandReplyTo: "Yanıt verilen not",
  saveDraft: "Taslağı kaydet",
  commandPending: "Bir toplantı değişikliğinin sonucu bekleniyor",
  commandHelp:
    "Yeni değişiklikler duraklatıldı. Tekrar göndermeden önce kayıtlı sonucu kontrol edin.",
  commandCheck: "Kayıtlı sonucu kontrol et",
  commandRetry: "İlk değişikliği yeniden dene",
  commandMissing:
    "Henüz bir sonuç kaydedilmemiş. Yeniden deneme ilk girdiyi ve işlem kimliğini kullanır.",
  commandSaved: "Değişiklik kaydedildi. Devam etmeden önce gözden geçirin.",
  commandRejected:
    "Değişiklik reddedildi. Taslağınız korundu; düzeltmeden önce toplantının güncel kaydını inceleyin.",
  commandError:
    "Sonuç kontrol edilemedi. Bu sekmeyi açık tutup yeniden kontrol edin.",
  commandStorage:
    "Yerel kurtarma alanına erişilemiyor. Gönderim duraklatıldı. Bu sekmeyi açık tutun.",
  commandDamaged: "Kayıtlı değişiklik okunamadı. Özgün veri korundu.",
  commandReview: "Kayıtlı değişikliği incele",
  commandConfirm: "İnceledim — devam et",
  commandClear: "Bozuk kurtarma kaydını temizle",
  commandClearHelp:
    "Önce kayıtlı veriyi kopyalayın ve sunucudaki kayıtları kontrol edin. Bu yerel kaydı temizlemek yeniden deneme kimliğini kaybettirir; değişikliği tekrarlamak mükerrer kayıt oluşturabilir. Gönderilmemiş taslaklar ve sunucu kayıtları korunur.",
  commandKeep: "Kurtarma kaydını koru",
  commandSource: "Kaydedilmiş girdi",
  commandIdentity: "İşlem kimliği",
  commandScope: "Proje {project} · Toplantı {meeting}",
  commandNew: "Yeni toplantı",
  command_create: "Toplantı oluştur",
  command_update: "Toplantıyı düzenle",
  command_transcript: "Operatör notu ekle",
  command_decision: "Karar kaydet",
  command_action: "Eylem oluştur",
  command_action_update: "Eylemi güncelle",
  command_complete: "Toplantıyı tamamla",
  title: "Proje toplantıları",
  description: "Tutanak, karar ve aksiyonlar bu projenin kayıtlarında tutulur.",
  newMeeting: "Yeni toplantı",
  closeForm: "Formu kapat",
  titleLabel: "Toplantı başlığı",
  titlePlaceholder: "Bu projede konuşulacak konuyu yaz",
  agendaLabel: "Gündem",
  optional: "İsteğe bağlı",
  agendaPlaceholder: "Ele alınacak maddeleri yaz",
  participants: "Katılımcılar",
  participantsHelp:
    "Aktif proje ekibi başlangıçta seçilir. Başlatmadan önce seçimi değiştirebilirsin.",
  noAgents: "Seçilebilecek aktif uzman bulunamadı.",
  selectedCount: "Seçilen katılımcı: {count}",
  noSelection: "Katılımcı seçmeden de toplantı başlatabilirsin.",
  start: "Toplantıyı başlat",
  starting: "Başlatılıyor",
  list: "Proje toplantıları listesi",
  listTitle: "Toplantılar",
  loadingList: "Toplantılar yükleniyor",
  listError: "Toplantılar alınamadı",
  emptyTitle: "Henüz toplantı yok",
  emptyHelp: "Bu projeye ait ilk toplantıyı başlat.",
  firstMeeting: "İlk toplantıyı başlat",
  selectTitle: "Proje toplantı hafızası",
  selectHelp: "Tutanak, karar ve aksiyonları okumak için bir toplantı seç.",
  loadingDetail: "Toplantı ayrıntısı yükleniyor",
  detailError: "Toplantı ayrıntısı alınamadı",
  retry: "Yeniden dene",
  draft: "Taslak",
  scheduled: "Planlandı",
  in_progress: "Devam ediyor",
  completed: "Tamamlandı",
  cancelled: "İptal edildi",
  countParticipants: "Katılımcı: {count}",
  identity: "Toplantı #{meeting} · Proje #{project}",
  noParticipants: "Katılımcı eklenmedi",
  summary: "Kapanış özeti",
  complete: "Toplantıyı tamamla",
  transcript: "Tutanak",
  emptyTranscript: "Henüz tutanak satırı yok.",
  messageLabel: "Toplantıya yaz",
  nextTurn: "Yeni turu başlat",
  decisions: "Kararlar",
  decisionLabel: "Karar",
  addDecision: "Karar ekle",
  emptyDecisions: "Henüz karar kaydı yok.",
  owner: "Sahip: {name}",
  sharedDecision: "Ortak karar",
  actions: "Aksiyonlar",
  actionLabel: "Aksiyon",
  addAction: "Aksiyon ekle",
  emptyActions: "Henüz aksiyon kaydı yok.",
  unassigned: "Sahip atanmadı",
  noneOwner: "Sahip seçilmedi",
  ownerLabel: "{label} sahibi",
  emptyRoster: "Bu toplantıda katılımcı yok. {label} sahipsiz kaydedilebilir.",
  actionComplete: "{title} aksiyonunu tamamla",
  actionReopen: "{title} aksiyonunu yeniden aç",
  saving: "Kaydediliyor",
  founder: "Kurucu",
  agent: "Uzman",
  created: "Toplantı taslağı kaydedildi",
  started: "Toplantı başladı",
  turnComplete: "Yeni toplantı turu tamamlandı",
  contributions: "Tutanağa yazılan uzman yanıtı: {count}",
  noContribution: "Ek uzman yanıtı kaydedilmedi.",
  saveError:
    "Sonuç doğrulanamadı. Girdilerin korunuyor. İşlemi tekrarlamadan önce toplantı kayıtlarını kontrol et.",
  completedTitle: "Toplantı tamamlandı",
  required: "Devam etmek için bu alanı doldur.",
  tooLong: "En fazla {count} karakter kullan.",
  rosterChanged:
    "Kullanılabilir bir katılımcı seç veya kullanılamayan seçimi kaldır.",
  staleList: "Toplantı listesi yenilenemedi. Son yüklenen liste gösteriliyor.",
  staleDetail:
    "Toplantı ayrıntıları yenilenemedi. Son kayıtlar gösteriliyor; düzenlemeden önce tekrar kontrol et.",
  snapshot: "Son yükleme: {time}",
  draftHelp:
    "Gönderilmemiş taslaklar bu tarayıcı sekmesinde saklanır. Başka cihazlarla paylaşılmaz.",
  draftError:
    "Taslaklar tarayıcıya kaydedilemiyor. Sekmeyi açık tut; ayrılmadan önce metnini kopyala. Depolama düzelene kadar gönderim bekletiliyor.",
  damagedDraft: "Kayıtlı taslaklar okunamadı. Üzerlerine yazılmadı.",
  resetDrafts: "Yerel taslakları incele",
  resetHelp:
    "Yalnızca bu projenin bu sekmedeki gönderilmemiş taslakları silinir. Gerekli metni önce kopyala. Sunucu kayıtları ve bekleyen tur kimlikleri korunur.",
  keepDrafts: "Taslakları koru",
  resetConfirm: "Yerel taslakları temizle",
  recordsHelp:
    "Toplantı metinleri özgün içeriktir. İş önerileri, işlemin yapıldığına dair kanıt değildir.",
  action_open: "Açık",
  action_in_progress: "Devam ediyor",
  action_done: "Tamamlandı",
  action_cancelled: "İptal edildi",
};
export default copy;
