import type { MeetingCopy } from "../meeting-copy";
const copy: MeetingCopy = {
  commandDetails: "Einzelheiten",
  commandReason: "Begründung",
  commandDue: "Fälligkeitsdatum",
  commandScheduled: "Geplanter Zeitpunkt",
  commandRecordedAt: "Aufgezeichneter Zeitpunkt",
  commandReplyTo: "Antwort auf Notiz",
  saveDraft: "Entwurf speichern",
  commandPending: "Eine Besprechungsänderung muss bestätigt werden",
  commandHelp:
    "Neue Änderungen sind pausiert. Prüfen Sie vor dem erneuten Senden das gespeicherte Ergebnis.",
  commandCheck: "Gespeichertes Ergebnis prüfen",
  commandRetry: "Ursprüngliche Änderung erneut senden",
  commandMissing:
    "Es ist noch kein Ergebnis gespeichert. Der erneute Versuch verwendet die ursprüngliche Eingabe und Kennung.",
  commandSaved:
    "Die Änderung wurde gespeichert. Prüfen Sie sie, bevor Sie fortfahren.",
  commandRejected:
    "Die Änderung wurde abgelehnt. Ihr Entwurf bleibt erhalten; prüfen Sie vor der Korrektur den aktuellen Besprechungsstand.",
  commandError:
    "Das Ergebnis konnte nicht geprüft werden. Lassen Sie diesen Tab geöffnet und prüfen Sie erneut.",
  commandStorage:
    "Der lokale Wiederherstellungsspeicher ist nicht verfügbar. Das Senden ist pausiert. Lassen Sie diesen Tab geöffnet.",
  commandDamaged:
    "Eine gespeicherte Änderung ist nicht lesbar. Die ursprünglichen Daten bleiben erhalten.",
  commandReview: "Gespeicherte Änderung prüfen",
  commandConfirm: "Geprüft — fortfahren",
  commandClear: "Beschädigten Wiederherstellungseintrag löschen",
  commandClearHelp:
    "Kopieren Sie zuerst die gespeicherten Daten und prüfen Sie die Servereinträge. Beim Löschen dieses lokalen Eintrags geht die Kennung für Wiederholungen verloren; erneutes Senden kann Duplikate erzeugen. Ungesendete Entwürfe und Servereinträge bleiben erhalten.",
  commandKeep: "Wiederherstellungseintrag behalten",
  commandSource: "Gespeicherte Eingabe",
  commandIdentity: "Anfragekennung",
  commandScope: "Projekt {project} · Besprechung {meeting}",
  commandNew: "Neue Besprechung",
  command_create: "Besprechung erstellen",
  command_update: "Besprechung bearbeiten",
  command_transcript: "Betreibernotiz hinzufügen",
  command_decision: "Entscheidung erfassen",
  command_action: "Maßnahme erstellen",
  command_action_update: "Maßnahme aktualisieren",
  command_complete: "Besprechung abschließen",
  title: "Projektbesprechungen",
  description:
    "Gespräche, Entscheidungen und Folgeaufgaben werden in diesem Projekt festgehalten.",
  newMeeting: "Neue Besprechung",
  closeForm: "Formular schließen",
  titleLabel: "Titel der Besprechung",
  titlePlaceholder: "Was soll besprochen werden?",
  agendaLabel: "Tagesordnung",
  optional: "Optional",
  agendaPlaceholder: "Themen für die Besprechung eingeben",
  participants: "Teilnehmende",
  participantsHelp:
    "Das aktive Projektteam ist anfangs ausgewählt. Passe die Auswahl vor dem Start an.",
  noAgents: "Keine aktiven Fachkräfte verfügbar.",
  selectedCount: "Ausgewählte Teilnehmende: {count}",
  noSelection: "Du kannst ohne Teilnehmende beginnen.",
  start: "Besprechung starten",
  starting: "Wird gestartet…",
  list: "Liste der Projektbesprechungen",
  listTitle: "Besprechungen",
  loadingList: "Besprechungen werden geladen",
  listError: "Besprechungen konnten nicht geladen werden.",
  emptyTitle: "Noch keine Besprechungen",
  emptyHelp: "Starte die erste Besprechung für dieses Projekt.",
  firstMeeting: "Erste Besprechung starten",
  selectTitle: "Besprechungsunterlagen",
  selectHelp:
    "Wähle eine Besprechung, um Protokoll, Entscheidungen und Aufgaben zu lesen.",
  loadingDetail: "Besprechungsdetails werden geladen",
  detailError: "Besprechungsdetails konnten nicht geladen werden.",
  retry: "Erneut versuchen",
  draft: "Entwurf",
  scheduled: "Geplant",
  in_progress: "Läuft",
  completed: "Abgeschlossen",
  cancelled: "Abgebrochen",
  countParticipants: "Teilnehmende: {count}",
  identity: "Besprechung #{meeting} · Projekt #{project}",
  noParticipants: "Keine Teilnehmenden",
  summary: "Abschlussübersicht",
  complete: "Besprechung abschließen",
  transcript: "Protokoll",
  emptyTranscript: "Noch keine Protokolleinträge.",
  messageLabel: "Nachricht an die Besprechung",
  nextTurn: "Nächste Runde starten",
  decisions: "Entscheidungen",
  decisionLabel: "Entscheidung",
  addDecision: "Entscheidung hinzufügen",
  emptyDecisions: "Noch keine Entscheidungen erfasst.",
  owner: "Verantwortlich: {name}",
  sharedDecision: "Gemeinsame Entscheidung",
  actions: "Aufgaben",
  actionLabel: "Aufgabe",
  addAction: "Aufgabe hinzufügen",
  emptyActions: "Noch keine Aufgaben erfasst.",
  unassigned: "Niemand zugewiesen",
  noneOwner: "Keine verantwortliche Person gewählt",
  ownerLabel: "Verantwortlich für {label}",
  emptyRoster:
    "Diese Besprechung hat keine Teilnehmenden. {label} kann ohne Zuweisung gespeichert werden.",
  actionComplete: "{title} als erledigt markieren",
  actionReopen: "{title} erneut öffnen",
  saving: "Wird gespeichert…",
  founder: "Betreiber",
  agent: "Fachkraft",
  created: "Besprechungsentwurf gespeichert",
  started: "Besprechung gestartet",
  turnComplete: "Besprechungsrunde beendet",
  contributions: "Erfasste Antworten: {count}",
  noContribution: "Keine weitere Antwort wurde erfasst.",
  saveError:
    "Das Ergebnis konnte nicht bestätigt werden. Deine Eingaben bleiben erhalten. Prüfe die Besprechungsunterlagen, bevor du die Aktion wiederholst.",
  completedTitle: "Besprechung abgeschlossen",
  required: "Gib einen Wert ein, um fortzufahren.",
  tooLong: "Verwende höchstens {count} Zeichen.",
  rosterChanged:
    "Wähle eine verfügbare Person oder entferne die nicht verfügbare Auswahl.",
  staleList:
    "Die Liste konnte nicht aktualisiert werden. Die zuletzt geladene Liste bleibt sichtbar.",
  staleDetail:
    "Die Details konnten nicht aktualisiert werden. Die letzten Daten bleiben sichtbar. Prüfe sie vor dem Bearbeiten erneut.",
  snapshot: "Zuletzt geladen: {time}",
  draftHelp:
    "Nicht gesendete Entwürfe werden in diesem Browser-Tab gespeichert und nicht mit anderen Geräten geteilt.",
  draftError:
    "Entwürfe können nicht gespeichert werden. Lass diesen Tab offen und kopiere deinen Text vor dem Verlassen. Das Senden ist bis zur Wiederherstellung des Speichers gesperrt.",
  damagedDraft:
    "Gespeicherte Entwürfe konnten nicht gelesen werden. Sie wurden nicht überschrieben.",
  resetDrafts: "Lokale Entwürfe prüfen",
  resetHelp:
    "Dies löscht nur die nicht gesendeten Entwürfe dieses Projekts in diesem Tab. Kopiere benötigte Texte zuerst. Serverdaten und Kennungen ausstehender Runden bleiben erhalten.",
  keepDrafts: "Entwürfe behalten",
  resetConfirm: "Lokale Entwürfe löschen",
  recordsHelp:
    "Besprechungstexte sind Originalinhalte. Ein Arbeitsvorschlag belegt keine ausgeführte Aktion.",
  action_open: "Offen",
  action_in_progress: "In Bearbeitung",
  action_done: "Erledigt",
  action_cancelled: "Abgebrochen",
};
export default copy;
