import type { MeetingCopy } from "../meeting-copy";
const copy: MeetingCopy = {
  commandDetails: "详情",
  commandReason: "理由",
  commandDue: "截止日期",
  commandScheduled: "计划时间",
  commandRecordedAt: "记录时间",
  commandReplyTo: "回复备注",
  saveDraft: "保存草稿",
  commandPending: "会议更改的结果需要确认",
  commandHelp: "新的更改已暂停。再次发送前，请检查已保存的结果。",
  commandCheck: "检查已保存的结果",
  commandRetry: "重试原始更改",
  commandMissing: "尚未记录结果。重试将使用原始输入和请求标识。",
  commandSaved: "更改已保存。请查看后再继续。",
  commandRejected: "更改被拒绝。草稿已保留；修改前请检查会议的当前记录。",
  commandError: "无法检查结果。请保持此标签页打开并再次检查。",
  commandStorage: "本地恢复存储不可用，发送已暂停。请保持此标签页打开。",
  commandDamaged: "无法读取已保存的更改，原始数据已保留。",
  commandReview: "查看已保存的更改",
  commandConfirm: "已查看 — 继续",
  commandClear: "清除损坏的恢复记录",
  commandClearHelp:
    "请先复制已保存的数据并检查服务器记录。清除此本地记录会丢失重试标识；再次提交可能产生重复记录。未发送的草稿和服务器记录会保留。",
  commandKeep: "保留恢复记录",
  commandSource: "已保存的输入",
  commandIdentity: "请求标识",
  commandScope: "项目 {project} · 会议 {meeting}",
  commandNew: "新会议",
  command_create: "创建会议",
  command_update: "编辑会议",
  command_transcript: "添加操作员备注",
  command_decision: "记录决策",
  command_action: "创建行动",
  command_action_update: "更新行动",
  command_complete: "结束会议",
  title: "项目会议",
  description: "将讨论、决策和后续事项保存在本项目的记录中。",
  newMeeting: "新建会议",
  closeForm: "关闭表单",
  titleLabel: "会议标题",
  titlePlaceholder: "本次会议讨论什么？",
  agendaLabel: "议程",
  optional: "选填",
  agendaPlaceholder: "填写要讨论的事项",
  participants: "参会成员",
  participantsHelp: "默认选择当前项目的活跃团队成员。开始前可以调整。",
  noAgents: "没有可用的活跃专家。",
  selectedCount: "已选成员：{count}",
  noSelection: "也可以不选择成员直接开始。",
  start: "开始会议",
  starting: "正在开始…",
  list: "项目会议列表",
  listTitle: "会议",
  loadingList: "正在加载会议",
  listError: "无法加载会议。",
  emptyTitle: "还没有会议",
  emptyHelp: "为本项目开始第一次会议。",
  firstMeeting: "开始第一次会议",
  selectTitle: "项目会议记录",
  selectHelp: "选择会议以查看讨论记录、决策和行动事项。",
  loadingDetail: "正在加载会议详情",
  detailError: "无法加载会议详情。",
  retry: "重试",
  draft: "草稿",
  scheduled: "已安排",
  in_progress: "进行中",
  completed: "已完成",
  cancelled: "已取消",
  countParticipants: "成员：{count}",
  identity: "会议 #{meeting} · 项目 #{project}",
  noParticipants: "没有参会成员",
  summary: "结束总结",
  complete: "结束会议",
  transcript: "讨论记录",
  emptyTranscript: "还没有讨论记录。",
  messageLabel: "向会议发言",
  nextTurn: "开始下一轮",
  decisions: "决策",
  decisionLabel: "决策内容",
  addDecision: "添加决策",
  emptyDecisions: "还没有决策记录。",
  owner: "负责人：{name}",
  sharedDecision: "共同决策",
  actions: "行动事项",
  actionLabel: "行动事项",
  addAction: "添加行动事项",
  emptyActions: "还没有行动事项。",
  unassigned: "未指定负责人",
  noneOwner: "未选择负责人",
  ownerLabel: "{label}的负责人",
  emptyRoster: "本次会议没有成员。{label}可以不指定负责人直接保存。",
  actionComplete: "将“{title}”标记为已完成",
  actionReopen: "重新打开“{title}”",
  saving: "正在保存…",
  founder: "操作员",
  agent: "专家",
  created: "会议草稿已保存",
  started: "会议已开始",
  turnComplete: "本轮会议已结束",
  contributions: "已记录的专家回复：{count}",
  noContribution: "没有记录到其他专家回复。",
  saveError: "无法确认结果。您的输入已保留。再次执行前请检查会议记录。",
  completedTitle: "会议已结束",
  required: "请填写此字段后继续。",
  tooLong: "请勿超过 {count} 个字符。",
  rosterChanged: "请选择可用成员，或移除不可用的选择。",
  staleList: "无法刷新会议列表。仍显示上次加载的列表。",
  staleDetail: "无法刷新会议详情。仍显示上次的记录；编辑前请重新检查。",
  snapshot: "上次加载：{time}",
  draftHelp: "未发送的草稿保存在当前浏览器标签页中，不会同步到其他设备。",
  draftError:
    "草稿存储不可用。请保持此标签页打开，并在离开前复制文本。存储恢复前暂停发送。",
  damagedDraft: "无法读取已保存的草稿。原记录未被覆盖。",
  resetDrafts: "检查本地草稿",
  resetHelp:
    "仅清除此标签页中本项目未发送的草稿。请先复制需要保留的文本。服务器记录和待处理轮次的标识将保留。",
  keepDrafts: "保留草稿",
  resetConfirm: "清除本地草稿",
  recordsHelp: "会议文本为原始内容。提出工作建议不代表已执行操作。",
  action_open: "待处理",
  action_in_progress: "进行中",
  action_done: "已完成",
  action_cancelled: "已取消",
};
export default copy;
