const copy = {
  commandDetails: "Details",
  commandReason: "Reason",
  commandDue: "Due date",
  commandScheduled: "Scheduled time",
  commandRecordedAt: "Recorded time",
  commandReplyTo: "Reply to note",
  saveDraft: "Save draft",
  commandPending: "A meeting change needs confirmation",
  commandHelp:
    "New changes are paused. Check the saved result before sending again.",
  commandCheck: "Check saved result",
  commandRetry: "Retry original change",
  commandMissing:
    "No result is recorded yet. Retry uses the original input and identity.",
  commandSaved: "The change was saved. Review it before continuing.",
  commandRejected:
    "The change was rejected. Your draft is kept; review the current meeting before correcting it.",
  commandError:
    "The result could not be checked. Keep this tab open and try checking again.",
  commandStorage:
    "Local recovery storage is unavailable. Sending is paused. Keep this tab open.",
  commandDamaged:
    "A saved change could not be read. Its original data has been kept.",
  commandReview: "Review saved change",
  commandConfirm: "Reviewed — continue",
  commandClear: "Clear damaged recovery record",
  commandClearHelp:
    "Copy the saved data first and check the server records. Clearing this local record loses its retry identity; repeating the change may create a duplicate. Unsent drafts and server records are kept.",
  commandKeep: "Keep recovery record",
  commandSource: "Saved input",
  commandIdentity: "Request identity",
  commandScope: "Project {project} · Meeting {meeting}",
  commandNew: "New meeting",
  command_create: "Create meeting",
  command_update: "Edit meeting",
  command_transcript: "Add operator note",
  command_decision: "Record decision",
  command_action: "Create action",
  command_action_update: "Update action",
  command_complete: "Complete meeting",
  title: "Project meetings",
  description:
    "Keep the conversation, decisions and follow-up work in this project's records.",
  newMeeting: "New meeting",
  closeForm: "Close form",
  titleLabel: "Meeting title",
  titlePlaceholder: "What will this meeting cover?",
  agendaLabel: "Agenda",
  optional: "Optional",
  agendaPlaceholder: "Add the topics to discuss",
  participants: "Participants",
  participantsHelp:
    "The active project team is selected initially. Adjust the selection before starting.",
  noAgents: "No active experts are available.",
  selectedCount: "Selected participants: {count}",
  noSelection: "You can start without participants.",
  start: "Start meeting",
  starting: "Starting…",
  list: "Project meeting list",
  listTitle: "Meetings",
  loadingList: "Loading meetings",
  listError: "Meetings could not be loaded.",
  emptyTitle: "No meetings yet",
  emptyHelp: "Start the first meeting for this project.",
  firstMeeting: "Start first meeting",
  selectTitle: "Project meeting records",
  selectHelp: "Select a meeting to read its transcript, decisions and actions.",
  loadingDetail: "Loading meeting details",
  detailError: "Meeting details could not be loaded.",
  retry: "Try again",
  draft: "Draft",
  scheduled: "Scheduled",
  in_progress: "In progress",
  completed: "Completed",
  cancelled: "Cancelled",
  countParticipants: "Participants: {count}",
  identity: "Meeting #{meeting} · Project #{project}",
  noParticipants: "No participants",
  summary: "Closing summary",
  complete: "Complete meeting",
  transcript: "Transcript",
  emptyTranscript: "No transcript entries yet.",
  messageLabel: "Message the meeting",
  nextTurn: "Start next turn",
  decisions: "Decisions",
  decisionLabel: "Decision",
  addDecision: "Add decision",
  emptyDecisions: "No decisions recorded yet.",
  owner: "Owner: {name}",
  sharedDecision: "Shared decision",
  actions: "Actions",
  actionLabel: "Action",
  addAction: "Add action",
  emptyActions: "No actions recorded yet.",
  unassigned: "No owner assigned",
  noneOwner: "No owner selected",
  ownerLabel: "{label} owner",
  emptyRoster:
    "This meeting has no participants. {label} can be saved without an owner.",
  actionComplete: "Mark {title} as done",
  actionReopen: "Reopen {title}",
  saving: "Saving…",
  founder: "Operator",
  agent: "Expert",
  created: "Meeting draft saved",
  started: "Meeting started",
  turnComplete: "Meeting turn finished",
  contributions: "Recorded expert replies: {count}",
  noContribution: "No additional expert reply was recorded.",
  saveError:
    "The result could not be confirmed. Your input is kept. Check the meeting records before repeating the action.",
  completedTitle: "Meeting completed",
  required: "Enter a value to continue.",
  tooLong: "Use no more than {count} characters.",
  rosterChanged:
    "Choose an available participant or remove the unavailable selection.",
  staleList:
    "The meeting list could not be refreshed. The last loaded list remains visible.",
  staleDetail:
    "Meeting details could not be refreshed. The last loaded records remain visible; check again before editing.",
  snapshot: "Last loaded: {time}",
  draftHelp:
    "Unsent drafts are saved in this browser tab. They are not shared with another device.",
  draftError:
    "Draft storage is unavailable. Keep this tab open and copy your text before leaving. Sending is paused until storage works.",
  damagedDraft:
    "Saved drafts could not be read. They have not been overwritten.",
  resetDrafts: "Review local drafts",
  resetHelp:
    "This clears only this project's unsent drafts in this browser tab. Copy any text you need first. Server records and pending turn identities are kept.",
  keepDrafts: "Keep drafts",
  resetConfirm: "Clear local drafts",
  recordsHelp:
    "Meeting text is source content. Proposed work is not proof of an executed action.",
  action_open: "Open",
  action_in_progress: "In progress",
  action_done: "Done",
  action_cancelled: "Cancelled",
};
export default copy;
