import type { MeetingCopy } from "../meeting-copy";
const copy: MeetingCopy = {
  commandDetails: "التفاصيل",
  commandReason: "المبرر",
  commandDue: "تاريخ الاستحقاق",
  commandScheduled: "الوقت المجدول",
  commandRecordedAt: "وقت التسجيل",
  commandReplyTo: "رد على الملاحظة",
  saveDraft: "حفظ المسودة",
  commandPending: "نتيجة تعديل الاجتماع تحتاج إلى تأكيد",
  commandHelp:
    "تم إيقاف التعديلات الجديدة مؤقتًا. تحقق من النتيجة المحفوظة قبل الإرسال مجددًا.",
  commandCheck: "التحقق من النتيجة المحفوظة",
  commandRetry: "إعادة محاولة التعديل الأصلي",
  commandMissing:
    "لم تُسجّل نتيجة بعد. ستستخدم إعادة المحاولة البيانات والمعرّف الأصليين.",
  commandSaved: "تم حفظ التعديل. راجعه قبل المتابعة.",
  commandRejected:
    "رُفض التعديل. مسودتك محفوظة؛ تحقق من سجل الاجتماع الحالي قبل التصحيح.",
  commandError:
    "تعذّر التحقق من النتيجة. أبقِ علامة التبويب هذه مفتوحة وحاول التحقق مجددًا.",
  commandStorage:
    "التخزين المحلي للاسترداد غير متاح. تم إيقاف الإرسال مؤقتًا. أبقِ علامة التبويب هذه مفتوحة.",
  commandDamaged: "تعذّرت قراءة تعديل محفوظ. تم الاحتفاظ بالبيانات الأصلية.",
  commandReview: "مراجعة التعديل المحفوظ",
  commandConfirm: "تمت المراجعة — متابعة",
  commandClear: "مسح سجل الاسترداد التالف",
  commandClearHelp:
    "انسخ البيانات المحفوظة أولًا وتحقق من سجلات الخادم. يؤدي مسح هذا السجل المحلي إلى فقدان معرّف إعادة المحاولة؛ وقد تؤدي إعادة التعديل إلى إنشاء سجل مكرر. تُحفظ المسودات غير المرسلة وسجلات الخادم.",
  commandKeep: "الاحتفاظ بسجل الاسترداد",
  commandSource: "البيانات المحفوظة",
  commandIdentity: "معرّف الطلب",
  commandScope: "المشروع {project} · الاجتماع {meeting}",
  commandNew: "اجتماع جديد",
  command_create: "إنشاء اجتماع",
  command_update: "تعديل الاجتماع",
  command_transcript: "إضافة ملاحظة المشغّل",
  command_decision: "تسجيل قرار",
  command_action: "إنشاء إجراء",
  command_action_update: "تحديث الإجراء",
  command_complete: "إنهاء الاجتماع",
  title: "اجتماعات المشروع",
  description: "احفظ المناقشات والقرارات ومهام المتابعة في سجلات هذا المشروع.",
  newMeeting: "اجتماع جديد",
  closeForm: "إغلاق النموذج",
  titleLabel: "عنوان الاجتماع",
  titlePlaceholder: "ما موضوع هذا الاجتماع؟",
  agendaLabel: "جدول الأعمال",
  optional: "اختياري",
  agendaPlaceholder: "أضف المواضيع المطلوب مناقشتها",
  participants: "المشاركون",
  participantsHelp:
    "يُختار فريق المشروع النشط مبدئيًا. يمكنك تعديل الاختيار قبل البدء.",
  noAgents: "لا يوجد خبراء نشطون متاحون.",
  selectedCount: "عدد المشاركين المختارين: {count}",
  noSelection: "يمكنك البدء دون مشاركين.",
  start: "بدء الاجتماع",
  starting: "جارٍ البدء…",
  list: "قائمة اجتماعات المشروع",
  listTitle: "الاجتماعات",
  loadingList: "جارٍ تحميل الاجتماعات",
  listError: "تعذّر تحميل الاجتماعات.",
  emptyTitle: "لا توجد اجتماعات بعد",
  emptyHelp: "ابدأ الاجتماع الأول لهذا المشروع.",
  firstMeeting: "بدء الاجتماع الأول",
  selectTitle: "سجلات اجتماعات المشروع",
  selectHelp: "اختر اجتماعًا لقراءة المحضر والقرارات والإجراءات.",
  loadingDetail: "جارٍ تحميل تفاصيل الاجتماع",
  detailError: "تعذّر تحميل تفاصيل الاجتماع.",
  retry: "إعادة المحاولة",
  draft: "مسودة",
  scheduled: "مجدول",
  in_progress: "جارٍ",
  completed: "مكتمل",
  cancelled: "ملغى",
  countParticipants: "عدد المشاركين: {count}",
  identity: "الاجتماع #{meeting} · المشروع #{project}",
  noParticipants: "لا يوجد مشاركون",
  summary: "ملخص الختام",
  complete: "إنهاء الاجتماع",
  transcript: "المحضر",
  emptyTranscript: "لا توجد مدخلات في المحضر بعد.",
  messageLabel: "رسالة إلى الاجتماع",
  nextTurn: "بدء الجولة التالية",
  decisions: "القرارات",
  decisionLabel: "القرار",
  addDecision: "إضافة قرار",
  emptyDecisions: "لا توجد قرارات مسجلة بعد.",
  owner: "المسؤول: {name}",
  sharedDecision: "قرار مشترك",
  actions: "الإجراءات",
  actionLabel: "الإجراء",
  addAction: "إضافة إجراء",
  emptyActions: "لا توجد إجراءات مسجلة بعد.",
  unassigned: "لم يُعيّن مسؤول",
  noneOwner: "لم يُختر مسؤول",
  ownerLabel: "المسؤول عن {label}",
  emptyRoster: "لا يوجد مشاركون في هذا الاجتماع. يمكن حفظ {label} دون مسؤول.",
  actionComplete: "وضع علامة الإنجاز على «{title}»",
  actionReopen: "إعادة فتح «{title}»",
  saving: "جارٍ الحفظ…",
  founder: "المشغّل",
  agent: "الخبير",
  created: "حُفظت مسودة الاجتماع",
  started: "بدأ الاجتماع",
  turnComplete: "انتهت جولة الاجتماع",
  contributions: "عدد ردود الخبراء المسجلة: {count}",
  noContribution: "لم يُسجّل رد إضافي من الخبراء.",
  saveError:
    "تعذّر تأكيد النتيجة. احتُفظ بمدخلاتك. راجع سجلات الاجتماع قبل تكرار الإجراء.",
  completedTitle: "انتهى الاجتماع",
  required: "أدخل قيمة للمتابعة.",
  tooLong: "استخدم {count} حرفًا كحد أقصى.",
  rosterChanged: "اختر مشاركًا متاحًا أو أزل الاختيار غير المتاح.",
  staleList: "تعذّر تحديث قائمة الاجتماعات. ما زالت آخر قائمة محمّلة ظاهرة.",
  staleDetail:
    "تعذّر تحديث تفاصيل الاجتماع. ما زالت السجلات السابقة ظاهرة؛ تحقّق مجددًا قبل التعديل.",
  snapshot: "آخر تحميل: {time}",
  draftHelp:
    "تُحفظ المسودات غير المرسلة في علامة تبويب المتصفح هذه، ولا تُشارك مع جهاز آخر.",
  draftError:
    "تخزين المسودات غير متاح. أبقِ علامة التبويب مفتوحة وانسخ النص قبل المغادرة. يتوقف الإرسال حتى يعود التخزين للعمل.",
  damagedDraft: "تعذّرت قراءة المسودات المحفوظة. لم تُستبدل بياناتها.",
  resetDrafts: "مراجعة المسودات المحلية",
  resetHelp:
    "يؤدي هذا إلى مسح المسودات غير المرسلة لهذا المشروع في علامة التبويب هذه فقط. انسخ النص الذي تحتاجه أولًا. تُحفظ سجلات الخادم ومعرّفات الجولات المعلّقة.",
  keepDrafts: "الاحتفاظ بالمسودات",
  resetConfirm: "مسح المسودات المحلية",
  recordsHelp:
    "نصوص الاجتماع محتوى أصلي. اقتراح العمل ليس دليلًا على تنفيذ الإجراء.",
  action_open: "مفتوح",
  action_in_progress: "قيد التنفيذ",
  action_done: "منجز",
  action_cancelled: "ملغى",
};
export default copy;
