import type { MeetingCopy } from "../meeting-copy";
const copy: MeetingCopy = {
  commandDetails: "詳細資料",
  commandReason: "理由",
  commandDue: "截止日期",
  commandScheduled: "排定時間",
  commandRecordedAt: "記錄時間",
  commandReplyTo: "回覆備註",
  saveDraft: "儲存草稿",
  commandPending: "會議變更的結果需要確認",
  commandHelp: "新的變更已暫停。再次傳送前，請檢查已儲存的結果。",
  commandCheck: "檢查已儲存的結果",
  commandRetry: "重試原始變更",
  commandMissing: "尚未記錄結果。重試將使用原始輸入和請求識別碼。",
  commandSaved: "變更已儲存。請檢視後再繼續。",
  commandRejected: "變更遭拒。草稿已保留；修改前請檢查會議的目前紀錄。",
  commandError: "無法檢查結果。請保持此分頁開啟並再次檢查。",
  commandStorage: "本機復原儲存空間無法使用，傳送已暫停。請保持此分頁開啟。",
  commandDamaged: "無法讀取已儲存的變更，原始資料已保留。",
  commandReview: "檢視已儲存的變更",
  commandConfirm: "已檢視 — 繼續",
  commandClear: "清除損壞的復原紀錄",
  commandClearHelp:
    "請先複製已儲存的資料並檢查伺服器紀錄。清除此本機紀錄會遺失重試識別碼；再次提交可能產生重複紀錄。未傳送的草稿和伺服器紀錄會保留。",
  commandKeep: "保留復原紀錄",
  commandSource: "已儲存的輸入",
  commandIdentity: "請求識別碼",
  commandScope: "專案 {project} · 會議 {meeting}",
  commandNew: "新會議",
  command_create: "建立會議",
  command_update: "編輯會議",
  command_transcript: "新增操作員備註",
  command_decision: "記錄決策",
  command_action: "建立行動",
  command_action_update: "更新行動",
  command_complete: "結束會議",
  title: "專案會議",
  description: "將討論、決策和後續事項保存在本專案的紀錄中。",
  newMeeting: "新增會議",
  closeForm: "關閉表單",
  titleLabel: "會議標題",
  titlePlaceholder: "這次會議要討論什麼？",
  agendaLabel: "議程",
  optional: "選填",
  agendaPlaceholder: "填寫要討論的事項",
  participants: "與會成員",
  participantsHelp: "預設選取目前專案的活躍團隊成員。開始前可以調整。",
  noAgents: "沒有可用的活躍專家。",
  selectedCount: "已選成員：{count}",
  noSelection: "也可以不選成員直接開始。",
  start: "開始會議",
  starting: "正在開始…",
  list: "專案會議清單",
  listTitle: "會議",
  loadingList: "正在載入會議",
  listError: "無法載入會議。",
  emptyTitle: "尚無會議",
  emptyHelp: "為本專案開始第一次會議。",
  firstMeeting: "開始第一次會議",
  selectTitle: "專案會議紀錄",
  selectHelp: "選取會議以查看討論紀錄、決策和行動事項。",
  loadingDetail: "正在載入會議詳細資料",
  detailError: "無法載入會議詳細資料。",
  retry: "重試",
  draft: "草稿",
  scheduled: "已排程",
  in_progress: "進行中",
  completed: "已完成",
  cancelled: "已取消",
  countParticipants: "成員：{count}",
  identity: "會議 #{meeting} · 專案 #{project}",
  noParticipants: "沒有與會成員",
  summary: "結束摘要",
  complete: "結束會議",
  transcript: "討論紀錄",
  emptyTranscript: "尚無討論紀錄。",
  messageLabel: "向會議發言",
  nextTurn: "開始下一輪",
  decisions: "決策",
  decisionLabel: "決策內容",
  addDecision: "新增決策",
  emptyDecisions: "尚無決策紀錄。",
  owner: "負責人：{name}",
  sharedDecision: "共同決策",
  actions: "行動事項",
  actionLabel: "行動事項",
  addAction: "新增行動事項",
  emptyActions: "尚無行動事項。",
  unassigned: "未指派負責人",
  noneOwner: "未選擇負責人",
  ownerLabel: "{label}的負責人",
  emptyRoster: "這次會議沒有成員。{label}可以不指定負責人直接儲存。",
  actionComplete: "將「{title}」標記為已完成",
  actionReopen: "重新開啟「{title}」",
  saving: "正在儲存…",
  founder: "操作員",
  agent: "專家",
  created: "會議草稿已儲存",
  started: "會議已開始",
  turnComplete: "本輪會議已結束",
  contributions: "已記錄的專家回覆：{count}",
  noContribution: "沒有記錄到其他專家回覆。",
  saveError: "無法確認結果。您的輸入已保留。再次執行前請檢查會議紀錄。",
  completedTitle: "會議已結束",
  required: "請填寫此欄位後繼續。",
  tooLong: "請勿超過 {count} 個字元。",
  rosterChanged: "請選擇可用成員，或移除不可用的選項。",
  staleList: "無法更新會議清單。仍顯示上次載入的清單。",
  staleDetail: "無法更新會議詳細資料。仍顯示上次的紀錄；編輯前請重新檢查。",
  snapshot: "上次載入：{time}",
  draftHelp: "未送出的草稿儲存在目前瀏覽器分頁中，不會同步到其他裝置。",
  draftError:
    "草稿儲存空間無法使用。請保持此分頁開啟，並在離開前複製文字。儲存功能恢復前暫停傳送。",
  damagedDraft: "無法讀取已儲存的草稿。原紀錄未被覆寫。",
  resetDrafts: "檢查本機草稿",
  resetHelp:
    "僅清除此分頁中本專案未送出的草稿。請先複製需要保留的文字。伺服器紀錄和待處理輪次的識別碼將保留。",
  keepDrafts: "保留草稿",
  resetConfirm: "清除本機草稿",
  recordsHelp: "會議文字為原始內容。提出工作建議不代表已執行操作。",
  action_open: "待處理",
  action_in_progress: "進行中",
  action_done: "已完成",
  action_cancelled: "已取消",
};
export default copy;
