import type { AgentDirectoryCopy } from "../agent-directory-copy";

const copy = {
  eyebrow: "認識你的團隊",
  title: "為工作找到合適的專家。",
  description: "了解每位專家的職責，開始對話，或為團隊新增角色。",
  addExpert: "新增專家",
  conversationTitle: "與一位專家交流，還是與整個團隊討論？",
  conversationDescription:
    "在專家個人檔案開始一對一對話。共同話題可在公司聊天室討論。",
  companyRoom: "進入公司聊天室",
  directory: "專家目錄",
  search: "搜尋專家",
  searchPlaceholder: "姓名、專長或你想完成的工作…",
  department: "專業領域",
  allDepartments: "所有領域",
  general: "一般",
  departments: {
    executive: "管理",
    marketing: "行銷",
    sales: "銷售",
    operations: "營運",
    finance: "財務",
    product: "產品",
    engineering: "工程",
    research: "研究",
    support: "客戶支援",
    content: "內容",
    design: "設計",
    quality: "品質",
    data: "資料",
    automation: "自動化",
    custom: "自訂專長",
  },
  summaries: {
    ceo: "將目標轉化為計畫，協調工作職責並彙整成果。",
    marketing_director: "研究目標受眾、品牌訊息和可衡量的成長計畫。",
    sales_director: "梳理客戶需求、銷售機會並準備提案。",
    operations_director: "追蹤工作流程、職責分配和日常營運進度。",
    finance_director: "根據現有資料評估預算、成本和財務計畫。",
    product_director: "將使用者需求轉化為產品範圍、優先順序和驗收標準。",
    engineering_director: "協調可用軟體的開發、技術實作和可維護的架構。",
    research_director: "研究資料來源、核實論述並蒐集決策依據。",
    support_director: "整理客戶問題，擬定解決方案和清楚的回覆。",
    content_director: "依照品牌風格撰寫文案、內容計畫和發佈草稿。",
    ux_designer: "將複雜介面轉化為適用於手機和電腦的無障礙操作流程。",
    quality_engineer: "透過真實情境測試工作，回報缺陷並記錄交付依據。",
    data_analyst: "分析資料、核對計算並提供支援決策的分析結果。",
    automation_specialist:
      "將重複工作轉化為可控制、可觀察且能從故障中復原的流程。",
  },
  customSummary: (role) =>
    `\u2068${role}\u2069。可在個人檔案查看工作指示和權限。`,
  filterStatus: "依狀態篩選專家",
  all: "全部",
  statuses: {
    idle: "就緒",
    working: "工作中",
    blocked: "需要支援",
    archived: "已封存",
  },
  count: (shown, total, filtered) =>
    filtered ? `專家：${shown} / ${total}` : `專家：${shown}`,
  loading: "正在載入專家…",
  countUnavailable: "無法取得團隊人數",
  loadFailed: "無法載入專家",
  refreshFailed: "無法更新專家",
  errorDescription: "請檢查連線並重試。",
  staleDescription: "目前顯示上次載入的團隊。請檢查連線並重試。",
  retry: "重試",
  noMatch: "找不到符合條件的專家",
  noMatchDescription: "請縮短搜尋詞或清除篩選條件。",
  emptyTitle: "新增你的第一位專家",
  emptyDescription: "選擇預設角色，開始組建團隊。",
  clearFilters: "清除篩選",
  pagination: "專家目錄分頁",
  previous: "上一頁",
  next: "下一頁",
  page: (current, total) => `第 ${current} 頁，共 ${total} 頁`,
  workingAction: "正在處理指派的任務",
  openProfile: "個人檔案與工作指示",
} satisfies AgentDirectoryCopy;

export default copy;
