import type { AgentDirectoryCopy } from "../agent-directory-copy";

const copy = {
  eyebrow: "认识你的团队",
  title: "为工作找到合适的专家。",
  description: "了解每位专家的职责，开始对话，或为团队添加新角色。",
  addExpert: "添加专家",
  conversationTitle: "与一位专家交流，还是与整个团队讨论？",
  conversationDescription:
    "在专家资料页开始一对一对话。共同话题可在公司聊天室讨论。",
  companyRoom: "进入公司聊天室",
  directory: "专家目录",
  search: "搜索专家",
  searchPlaceholder: "姓名、专长或你想完成的工作…",
  department: "专业领域",
  allDepartments: "所有领域",
  general: "通用",
  departments: {
    executive: "管理",
    marketing: "市场营销",
    sales: "销售",
    operations: "运营",
    finance: "财务",
    product: "产品",
    engineering: "工程",
    research: "研究",
    support: "客户支持",
    content: "内容",
    design: "设计",
    quality: "质量",
    data: "数据",
    automation: "自动化",
    custom: "自定义专长",
  },
  summaries: {
    ceo: "将目标转化为计划，协调工作职责并汇总成果。",
    marketing_director: "研究目标受众、品牌信息和可衡量的增长计划。",
    sales_director: "梳理客户需求、销售机会并准备提案。",
    operations_director: "跟踪工作流程、职责分配和日常运营进展。",
    finance_director: "根据现有数据评估预算、成本和财务计划。",
    product_director: "将用户需求转化为产品范围、优先级和验收标准。",
    engineering_director: "协调可用软件的开发、技术实现和可维护的架构。",
    research_director: "研究资料来源、核实论断并收集决策依据。",
    support_director: "整理客户问题，起草解决方案和清晰的回复。",
    content_director: "按照品牌风格撰写文案、内容计划和发布草稿。",
    ux_designer: "将复杂界面转化为适用于手机和电脑的无障碍操作流程。",
    quality_engineer: "通过真实场景测试工作，报告缺陷并记录交付依据。",
    data_analyst: "分析数据、核查计算并提供支持决策的分析结果。",
    automation_specialist:
      "将重复工作转化为可控制、可观察且能从故障中恢复的流程。",
  },
  customSummary: (role) =>
    `\u2068${role}\u2069。可在资料页查看工作指令和权限。`,
  filterStatus: "按状态筛选专家",
  all: "全部",
  statuses: {
    idle: "就绪",
    working: "工作中",
    blocked: "需要支持",
    archived: "已归档",
  },
  count: (shown, total, filtered) =>
    filtered ? `专家：${shown} / ${total}` : `专家：${shown}`,
  loading: "正在加载专家…",
  countUnavailable: "无法获取团队人数",
  loadFailed: "无法加载专家",
  refreshFailed: "无法刷新专家",
  errorDescription: "请检查连接并重试。",
  staleDescription: "当前显示上次加载的团队。请检查连接并重试。",
  retry: "重试",
  noMatch: "未找到匹配的专家",
  noMatchDescription: "请缩短搜索词或清除筛选条件。",
  emptyTitle: "添加你的第一位专家",
  emptyDescription: "选择预设角色，开始组建团队。",
  clearFilters: "清除筛选",
  pagination: "专家目录分页",
  previous: "上一页",
  next: "下一页",
  page: (current, total) => `第 ${current} 页，共 ${total} 页`,
  workingAction: "正在处理分配的任务",
  openProfile: "资料与工作指令",
} satisfies AgentDirectoryCopy;

export default copy;
