import type { ConnectionCopy } from "../connection-copy";
export default {
  apiProviders: "API 提供商",
  signedOut: "此账户已退出登录。使用前请重新登录。",
  signInAgain: "重新登录",
  clearAttempt: "清除已结束的登录",
  description:
    "连接时，你的任务会保留在这里。保存连接后，正在等待提供商的现有任务可能会继续执行。",
  local: "本地模型",
  localHint: "使用本机或私有服务器上的 Ollama。",
  allowCloud: "允许此服务器使用云端模型",
  cloudUsage:
    "云端模型会将提示发送至 Ollama 云端，并使用该账户的适用配额或付费额度。保存不会发送模型请求。",
  localLocation: "在本地运行",
  cloudLocation: "使用 Ollama 云端",
  unknownLocation: "运行位置未验证",
  localRequirement:
    "强制本地运行需要 Ollama 0.18.0 或更高版本。请更新此服务器，再检查连接。",
  localVerified: "本地模型使用此服务器的硬件。工具支持会单独显示。",
  cloudOff: "已保存服务器的云端权限已关闭。",
  cloudOn: "已保存服务器的云端权限已开启。",
  chatgptHint: "使用符合条件的 ChatGPT 套餐；仍受权限和配额限制。",
  api: "API 密钥",
  apiHint: "用你自己的密钥连接 OpenAI 或 OpenRouter。提供商可能收费。",
  back: "所有连接选项",
  endpoint: "Ollama 地址",
  endpointHint: "由后端访问此地址，而不是你的手机。请使用私有 HTTP(S) 地址。",
  save: "保存连接",
  restore: "使用安装默认值",
  restoreHint: "移除已保存的地址。环境变量中的地址仍然有效。",
  key: "API 密钥",
  keyHint: "密钥会保留在内存中，直到安全保存到后端。不会存入浏览器存储。",
  saved: "连接已保存。发现的模型尚未通过模型请求测试。",
  unconfirmed: "无法确认保存结果。再次保存前，请检查当前连接。",
  invalid: "检查地址或密钥后重试。",
  changed: "连接已更改。再次保存前，请读取当前状态。",
  discovered: "发现的模型",
  none: "暂无可用的工具模型。请检查提供商；如果使用 Ollama，请添加模型后再次检查。",
  tools: "可使用工具",
  chatOnly: "仅聊天",
  advanced: "高级设置和手动模型测试",
  done: "返回我的任务",
  accounts: "已保存的账户",
  noAccounts: "尚无已保存的账户。",
  selected: "已选择",
  select: "选择此账户",
  identityOnly: "仅完成身份登录。请授权使用套餐以调用模型。",
  planReady: "已获得套餐权限。运行任务时会检查可用性和配额。",
  paused: "套餐使用已暂停。重试任务前，请查看限制。",
  signIn: "通过 ChatGPT 继续",
  sameComputer: "浏览器和后端运行在同一台电脑上。",
  officialLink: "打开官方登录页面",
  pending: "正在等待登录。请在官方页面完成登录，然后检查状态。",
  review: "保存前请核对此账户。保存不会选择账户或启动任务。",
  confirm: "保存已核对的账户",
  cancel: "取消登录",
  connected: "账户已保存。请明确选择它以使用。",
  ended: "此次登录已结束。原来的账户选择没有更改。",
  handoffTitle: "手机、服务器或容器",
  handoffText:
    "远程浏览器无法访问后端的私有回调地址。请在自己的电脑上登录，按照指南将受保护的记录传输到服务器。不要在此粘贴凭据。",
  handoffGuide: "打开安全传输指南",
  enablePlan: "授予套餐权限",
  refresh: "检查当前连接",
  unknown: "结果尚未确认。请读取当前状态，不要盲目重复操作。",
} satisfies ConnectionCopy;
