import type { ConnectionCopy } from "../connection-copy";
export default {
  apiProviders: "API 供應商",
  signedOut: "此帳戶已登出。使用前請重新登入。",
  signInAgain: "重新登入",
  clearAttempt: "清除已結束的登入",
  description:
    "連線時，你的任務會保留在這裡。儲存連線後，正在等待供應商的現有任務可能會繼續執行。",
  local: "本機模型",
  localHint: "使用本機或私人伺服器上的 Ollama。",
  chatgptHint: "使用符合資格的 ChatGPT 方案；仍受權限和配額限制。",
  api: "API 金鑰",
  apiHint: "用你自己的金鑰連接 OpenAI 或 OpenRouter。供應商可能收費。",
  back: "所有連線選項",
  endpoint: "Ollama 位址",
  endpointHint: "由後端存取此位址，而不是你的手機。請使用私人 HTTP(S) 位址。",
  save: "儲存連線",
  restore: "使用安裝預設值",
  restoreHint: "移除已儲存的位址。環境變數中的位址仍然有效。",
  key: "API 金鑰",
  keyHint: "金鑰會保留在記憶體中，直到安全儲存到後端。不會存入瀏覽器儲存空間。",
  saved: "連線已儲存。找到的模型尚未透過模型請求測試。",
  unconfirmed: "無法確認儲存結果。再次儲存前，請檢查目前連線。",
  invalid: "檢查位址或金鑰後重試。",
  changed: "連線已變更。再次儲存前，請讀取目前狀態。",
  discovered: "找到的模型",
  none: "暫無可用的工具模型。請檢查供應商；若使用 Ollama，請新增模型後再次檢查。",
  tools: "可使用工具",
  chatOnly: "僅聊天",
  advanced: "進階設定和手動模型測試",
  done: "返回我的任務",
  accounts: "已儲存的帳戶",
  noAccounts: "尚無已儲存的帳戶。",
  selected: "已選取",
  select: "選取此帳戶",
  identityOnly: "僅完成身分登入。請授權使用方案以呼叫模型。",
  planReady: "已取得方案權限。執行任務時會檢查可用性和配額。",
  paused: "方案使用已暫停。重試任務前，請查看限制。",
  signIn: "透過 ChatGPT 繼續",
  sameComputer: "瀏覽器和後端執行於同一台電腦。",
  officialLink: "開啟官方登入頁面",
  pending: "正在等待登入。請在官方頁面完成登入，然後檢查狀態。",
  review: "儲存前請核對此帳戶。儲存不會選取帳戶或啟動任務。",
  confirm: "儲存已核對的帳戶",
  cancel: "取消登入",
  connected: "帳戶已儲存。請明確選取它以使用。",
  ended: "此次登入已結束。原來的帳戶選取沒有變更。",
  handoffTitle: "手機、伺服器或容器",
  handoffText:
    "遠端瀏覽器無法存取後端的私人回呼位址。請在自己的電腦上登入，按照指南將受保護的記錄傳輸到伺服器。不要在此貼上憑證。",
  handoffGuide: "開啟安全傳輸指南",
  enablePlan: "授予方案權限",
  refresh: "檢查目前連線",
  unknown: "結果尚未確認。請讀取目前狀態，不要盲目重複操作。",
} satisfies ConnectionCopy;
