import type { NewAgentCopy } from "../new-agent-copy";

export default {
  back: "Uzmanlara dön",
  eyebrow: "Ekibini genişlet",
  title: "Yeni bir uzman ekle.",
  description:
    "Bir uzmanlık seç, adını belirle. Çalışma talimatı ve önerilen yetkiler hazır gelsin.",
  specialtyHeading: "1. Hangi işte yardımcı olsun?",
  recommended: "Yeni uzmanlıklar",
  recommendedAria: "Önerilen uzmanlıklar",
  templatesLoading: "Uzmanlıklar yükleniyor…",
  templatesError: "Uzmanlıklar yüklenemedi.",
  templatesEmpty:
    "Hazır rol bulunmuyor. Gelişmiş ayarlardan kendi çalışma talimatını yazabilirsin.",
  allTemplates: "Tüm uzmanlıklar",
  chooseTemplate: "Bir uzmanlık seç",
  identityHeading: "2. Ekibindeki yerini belirle",
  name: "Uzmanın adı",
  namePlaceholder: "Örneğin: Deniz",
  nameHelp: "Hazır adı kullanabilir veya kendi adını verebilirsin.",
  role: "Sorumluluğu",
  rolePlaceholder: "Örneğin: Ürün ve deneyim tasarımı",
  department: "Uzmanlık alanı",
  departmentPlaceholder: "Örneğin: Tasarım",
  departmentHelp: "Ekipte bu uzmanı bulmayı kolaylaştırır.",
  parent: "Kime bağlı çalışsın?",
  parentNone: "Doğrudan bana bağlı",
  teamLoading: "Ekip yükleniyor…",
  teamError: "Ekip listesi alınamadı. Doğrudan sana bağlı oluşturulabilir.",
  advanced: "Gelişmiş ayarlar",
  advancedHelp: "İsteğe bağlı · model, çalışma talimatı ve yetkiler",
  modelMode: "Model seçimi",
  modelAuto: "Otomatik seçim (önerilen)",
  modelManual: "Modeli kendim seçeceğim",
  modelHelp:
    "Otomatik seçim, bağlı modeller arasından işe uygun olanı kullanır.",
  fixedModel: "Sabit model",
  autoSummary: "Otomatik model seçimi",
  custom: "Çalışma talimatını kendim yazacağım",
  customHelp: "Hazır rol yerine özel sorumluluk tanımla.",
  prompt: "Çalışma talimatı",
  promptPlaceholder:
    "Hangi işi yapacağını, nasıl çalışacağını ve ne teslim edeceğini anlat.",
  promptReview: "Hazır çalışma talimatını incele",
  promptSource:
    "Bu talimatlar seçili dilde uygulanır. Kendin yazdığın talimatlar otomatik çevrilmez.",
  permissionsHeading: "Yetkiler",
  permissionsAria: "Uzman yetkileri",
  permissionsHelp:
    "İzinler, sistemdeki onay ve çalışma alanı kurallarıyla birlikte uygulanır.",
  startHint: "Bir uzmanlık seçerek başlayabilirsin.",
  customSummary: "Özel çalışma talimatı",
  cancel: "Vazgeç",
  submit: "Uzmanı ekle",
  submitting: "Ekleniyor…",
  retry: "Yeniden dene",
  saveFailed:
    "Uzman eklenemedi. Bağlantını kontrol edip yeniden dene. Bilgilerin korunuyor.",
  saved: "Uzman ekibe katıldı",
  savedDescription:
    "Uzmanlar sayfasından profilini açabilir ve görev verebilirsin.",
  validation: {
    nameShort: "Uzman için en az 2 karakterlik bir ad yaz.",
    nameLong: "Adı 80 karakter içinde yaz.",
    roleShort: "Uzmanın sorumluluğunu yaz.",
    roleLong: "Sorumluluğu 120 karakter içinde yaz.",
    departmentLong: "Uzmanlık alanını 120 karakter içinde yaz.",
    promptLong: "Çalışma talimatı fazla uzun; metni kısalt.",
    template: "Bir uzmanlık seç.",
    promptShort: "Çalışma talimatını en az 20 karakterle anlat.",
    model: "Araç kullanımını destekleyen kullanılabilir bir model seç.",
  },
  permissions: {
    canBrowse: "İnternette bilgi araştırma",
    canUseTerminal: "Çalışma alanındaki dosya ve araçlar",
    canDelegate: "Görev devretme",
    canCreateSubAgents: "Alt uzman oluşturma",
    canSpend: "Harcama isteği oluşturma",
    canDelete: "Silme isteği oluşturma",
    canPublish: "Yayınlama isteği oluşturma",
    canContactExternal: "Dış iletişim isteği oluşturma",
  },
  templates: {
    marketing_director: "Pazarlama Direktörü",
    sales_director: "Satış Direktörü",
    operations_director: "Operasyon Direktörü",
    finance_director: "Finans Direktörü",
    product_director: "Ürün Direktörü",
    engineering_director: "Mühendislik Direktörü",
    research_director: "Araştırma Direktörü",
    support_director: "Müşteri Desteği Direktörü",
    content_director: "İçerik Direktörü",
    ux_designer: "Tasarım Uzmanı",
    quality_engineer: "Kalite Uzmanı",
    data_analyst: "Veri Analisti",
    automation_specialist: "Otomasyon Uzmanı",
    specialist: "Uzman",
  },
  specialistSummary:
    "Belirli bir görevi teslimata ve kanıtlı doğrulamaya kadar yürütür.",
  model: {
    search: "Sabit model kataloğunda ara",
    placeholder: "Model veya sağlayıcı ara…",
    count: "Model sayısı",
    loading: "Model kataloğu yükleniyor",
    error: "Model kataloğu yüklenemedi.",
    stale:
      "Model kataloğu güncellenemedi. Model seçmeden önce kullanılabilirliği yeniden denetle.",
    connection: "Bağlantı gerekli",
    connectReason: "Bu sağlayıcıyı Bağlantılar sayfasından bağla.",
    toolsReason:
      "Bu model ajan araçlarını desteklemiyor; yalnız sohbet için kullanılabilir.",
    default: "Varsayılan",
    free: "Ücretsiz",
    noTools: "Araç yok · yalnız sohbet",
    showMore: "80 modele kadar daha göster",
    empty: "Henüz kullanılabilir model yok",
    noMatch: "Eşleşen model yok",
    emptyHelp: "Bağlantılar sayfasından bir model sağlayıcısı ekleyebilirsin.",
    noMatchHelp: "Model veya sağlayıcı adını farklı yazarak dene.",
    sourceDescription: "Özgün katalog açıklaması",
    builtin: "Yerleşik filo",
    tiers: {
      economy: "Ekonomik",
      standard: "Standart",
      premium: "Premium",
      reasoning: "Muhakeme",
    },
  },
} satisfies NewAgentCopy;
