import type { NewAgentCopy } from "../new-agent-copy";

export default {
  back: "返回专家列表",
  eyebrow: "扩充团队",
  title: "添加新专家。",
  description: "选择专业领域并设置名称，即可使用预设工作指令和建议权限。",
  specialtyHeading: "1. 希望专家协助什么工作？",
  recommended: "推荐专业领域",
  recommendedAria: "推荐专业领域",
  templatesLoading: "正在加载专业领域…",
  templatesError: "无法加载专业领域。",
  templatesEmpty: "暂无预设角色。你可以在高级设置中编写自己的工作指令。",
  allTemplates: "全部专业领域",
  chooseTemplate: "选择专业领域",
  identityHeading: "2. 确定专家在团队中的职责",
  name: "专家名称",
  namePlaceholder: "例如：小林",
  nameHelp: "使用建议名称，或自行命名。",
  role: "职责",
  rolePlaceholder: "例如：产品与体验设计",
  department: "专业领域",
  departmentPlaceholder: "例如：设计",
  departmentHelp: "方便在团队中找到这位专家。",
  parent: "向谁汇报？",
  parentNone: "直接向我汇报",
  teamLoading: "正在加载团队…",
  teamError: "无法加载团队。仍可创建直接向你汇报的专家。",
  advanced: "高级设置",
  advancedHelp: "可选 · 模型、工作指令与权限",
  modelMode: "模型选择",
  modelAuto: "自动选择（推荐）",
  modelManual: "自行选择模型",
  modelHelp: "自动选择会从已连接的服务商中使用适合当前工作的模型。",
  fixedModel: "固定模型",
  autoSummary: "自动选择模型",
  custom: "自行编写工作指令",
  customHelp: "自行定义职责，而不使用预设角色。",
  prompt: "工作指令",
  promptPlaceholder: "描述要完成的工作、工作方式和交付成果。",
  promptReview: "查看工作指令",
  promptSource: "这些指令使用所选语言。您自行编写的指令不会自动翻译。",
  permissionsHeading: "权限",
  permissionsAria: "专家权限",
  permissionsHelp: "这些权限与系统的审批规则及工作区规则共同生效。",
  startHint: "先选择一个专业领域。",
  customSummary: "自定义工作指令",
  cancel: "取消",
  submit: "添加专家",
  submitting: "正在添加…",
  retry: "重试",
  saveFailed: "无法添加专家。请检查网络连接后重试。已保留你填写的内容。",
  saved: "专家已加入团队",
  savedDescription: "在专家列表中打开其资料，即可分配工作。",
  validation: {
    nameShort: "专家名称至少需要 2 个字符。",
    nameLong: "名称不能超过 80 个字符。",
    roleShort: "请描述专家的职责。",
    roleLong: "职责不能超过 120 个字符。",
    departmentLong: "专业领域不能超过 120 个字符。",
    promptLong: "工作指令过长，请缩短内容。",
    template: "请选择专业领域。",
    promptShort: "工作指令至少需要 20 个字符。",
    model: "请选择支持智能体工具的可用模型。",
  },
  permissions: {
    canBrowse: "在网上查找信息",
    canUseTerminal: "使用工作区文件与工具",
    canDelegate: "委派任务",
    canCreateSubAgents: "创建下级专家",
    canSpend: "申请支出",
    canDelete: "申请删除",
    canPublish: "申请发布",
    canContactExternal: "申请对外沟通",
  },
  templates: {
    marketing_director: "市场总监",
    sales_director: "销售总监",
    operations_director: "运营总监",
    finance_director: "财务总监",
    product_director: "产品总监",
    engineering_director: "工程总监",
    research_director: "研究总监",
    support_director: "客户支持总监",
    content_director: "内容总监",
    ux_designer: "设计专家",
    quality_engineer: "质量专家",
    data_analyst: "数据分析师",
    automation_specialist: "自动化专家",
    specialist: "通用专家",
  },
  specialistSummary: "负责具体任务的交付，并通过证据验证成果。",
  model: {
    search: "搜索固定模型目录",
    placeholder: "搜索模型或服务商…",
    count: "模型数量",
    loading: "正在加载模型目录",
    error: "无法加载模型目录。",
    stale: "无法刷新模型目录。选择模型前，请重试以确认其可用性。",
    connection: "需要连接",
    connectReason: "请在连接页面连接此服务商。",
    toolsReason: "此模型不支持智能体工具，仅可用于聊天。",
    default: "默认",
    free: "免费",
    noTools: "无工具 · 仅聊天",
    showMore: "再显示最多 80 个模型",
    empty: "暂无可用模型",
    noMatch: "没有匹配的模型",
    emptyHelp: "可在连接页面添加模型服务商。",
    noMatchHelp: "请尝试其他模型或服务商名称。",
    sourceDescription: "目录原始说明",
    builtin: "内置模型",
    tiers: {
      economy: "经济型",
      standard: "标准型",
      premium: "高级型",
      reasoning: "推理型",
    },
  },
} satisfies NewAgentCopy;
