import type { NewAgentCopy } from "../new-agent-copy";

export default {
  back: "Zurück zu Experten",
  eyebrow: "Dein Team erweitern",
  title: "Einen Experten hinzufügen.",
  description:
    "Wähle ein Fachgebiet und einen Namen. Arbeitsanweisungen und empfohlene Berechtigungen sind bereits vorbereitet.",
  specialtyHeading: "1. Wobei soll die Person helfen?",
  recommended: "Empfohlene Fachgebiete",
  recommendedAria: "Empfohlene Fachgebiete",
  templatesLoading: "Fachgebiete werden geladen…",
  templatesError: "Fachgebiete konnten nicht geladen werden.",
  templatesEmpty:
    "Keine vorbereiteten Rollen verfügbar. Eigene Anweisungen kannst du in den erweiterten Einstellungen verfassen.",
  allTemplates: "Alle Fachgebiete",
  chooseTemplate: "Fachgebiet auswählen",
  identityHeading: "2. Den Platz im Team festlegen",
  name: "Name des Experten",
  namePlaceholder: "Zum Beispiel: Alex",
  nameHelp: "Übernimm den vorgeschlagenen Namen oder wähle einen eigenen.",
  role: "Verantwortungsbereich",
  rolePlaceholder: "Zum Beispiel: Produkt- und Erlebnisgestaltung",
  department: "Fachgebiet",
  departmentPlaceholder: "Zum Beispiel: Design",
  departmentHelp: "So findest du diesen Experten leichter im Team.",
  parent: "An wen soll die Person berichten?",
  parentNone: "Direkt an mich",
  teamLoading: "Team wird geladen…",
  teamError:
    "Das Team konnte nicht geladen werden. Du kannst einen Experten erstellen, der direkt an dich berichtet.",
  advanced: "Erweiterte Einstellungen",
  advancedHelp: "Optional · Modell, Arbeitsanweisungen und Berechtigungen",
  modelMode: "Modellauswahl",
  modelAuto: "Automatische Auswahl (empfohlen)",
  modelManual: "Modell selbst auswählen",
  modelHelp:
    "Die automatische Auswahl verwendet ein geeignetes Modell deiner verbundenen Anbieter.",
  fixedModel: "Festes Modell",
  autoSummary: "Automatische Modellauswahl",
  custom: "Eigene Arbeitsanweisungen verfassen",
  customHelp:
    "Lege eigene Verantwortlichkeiten statt einer vorbereiteten Rolle fest.",
  prompt: "Arbeitsanweisungen",
  promptPlaceholder:
    "Beschreibe die Aufgabe, die Vorgehensweise und das erwartete Ergebnis.",
  promptReview: "Arbeitsanweisungen prüfen",
  promptSource:
    "Diese Anweisungen gelten in der gewählten Sprache. Selbst verfasste Anweisungen werden nicht automatisch übersetzt.",
  permissionsHeading: "Berechtigungen",
  permissionsAria: "Berechtigungen des Experten",
  permissionsHelp:
    "Berechtigungen gelten zusammen mit den Freigabe- und Arbeitsbereichsregeln des Systems.",
  startHint: "Wähle zuerst ein Fachgebiet.",
  customSummary: "Eigene Arbeitsanweisungen",
  cancel: "Abbrechen",
  submit: "Experten hinzufügen",
  submitting: "Wird hinzugefügt…",
  retry: "Erneut versuchen",
  saveFailed:
    "Der Experte konnte nicht hinzugefügt werden. Prüfe die Verbindung und versuche es erneut. Deine Eingaben bleiben erhalten.",
  saved: "Experte zum Team hinzugefügt",
  savedDescription: "Öffne das Profil unter Experten, um Aufgaben zuzuweisen.",
  validation: {
    nameShort: "Der Name muss mindestens 2 Zeichen enthalten.",
    nameLong: "Der Name darf höchstens 80 Zeichen enthalten.",
    roleShort: "Beschreibe den Verantwortungsbereich.",
    roleLong: "Der Verantwortungsbereich darf höchstens 120 Zeichen enthalten.",
    departmentLong: "Das Fachgebiet darf höchstens 120 Zeichen enthalten.",
    promptLong: "Die Arbeitsanweisungen sind zu lang. Kürze den Text.",
    template: "Wähle ein Fachgebiet.",
    promptShort: "Beschreibe die Arbeitsanweisungen mit mindestens 20 Zeichen.",
    model: "Wähle ein verfügbares Modell, das Agentenwerkzeuge unterstützt.",
  },
  permissions: {
    canBrowse: "Informationen im Internet recherchieren",
    canUseTerminal: "Dateien und Werkzeuge im Arbeitsbereich",
    canDelegate: "Aufgaben delegieren",
    canCreateSubAgents: "Untergeordnete Experten erstellen",
    canSpend: "Ausgaben anfragen",
    canDelete: "Löschungen anfragen",
    canPublish: "Veröffentlichungen anfragen",
    canContactExternal: "Externe Kommunikation anfragen",
  },
  templates: {
    marketing_director: "Marketingleitung",
    sales_director: "Vertriebsleitung",
    operations_director: "Betriebsleitung",
    finance_director: "Finanzleitung",
    product_director: "Produktleitung",
    engineering_director: "Entwicklungsleitung",
    research_director: "Forschungsleitung",
    support_director: "Leitung Kundenservice",
    content_director: "Redaktionsleitung",
    ux_designer: "Designexperte",
    quality_engineer: "Qualitätsexperte",
    data_analyst: "Datenanalyst",
    automation_specialist: "Automatisierungsexperte",
    specialist: "Allgemeiner Experte",
  },
  specialistSummary:
    "Führt einen klar umrissenen Auftrag bis zur Übergabe und nachweisbaren Prüfung aus.",
  model: {
    search: "Katalog für feste Modelle durchsuchen",
    placeholder: "Modell oder Anbieter suchen…",
    count: "Modelle",
    loading: "Modellkatalog wird geladen",
    error: "Modellkatalog konnte nicht geladen werden.",
    stale:
      "Modellkatalog konnte nicht aktualisiert werden. Prüfe die Verfügbarkeit vor der Auswahl erneut.",
    connection: "Verbindung erforderlich",
    connectReason: "Verbinde diesen Anbieter unter Verbindungen.",
    toolsReason:
      "Dieses Modell unterstützt keine Agentenwerkzeuge und kann nur für Chats verwendet werden.",
    default: "Standard",
    free: "Kostenlos",
    noTools: "Keine Werkzeuge · nur Chat",
    showMore: "Bis zu 80 weitere Modelle anzeigen",
    empty: "Noch keine verfügbaren Modelle",
    noMatch: "Keine passenden Modelle",
    emptyHelp: "Füge unter Verbindungen einen Modellanbieter hinzu.",
    noMatchHelp: "Versuche einen anderen Modell- oder Anbieternamen.",
    sourceDescription: "Originale Katalogbeschreibung",
    builtin: "Integrierte Modelle",
    tiers: {
      economy: "Sparsam",
      standard: "Standard",
      premium: "Premium",
      reasoning: "Schlussfolgern",
    },
  },
} satisfies NewAgentCopy;
