import type { NewAgentCopy } from "../new-agent-copy";

export default {
  back: "Back to experts",
  eyebrow: "Build your team",
  title: "Add a new expert.",
  description:
    "Choose an expertise and a name. Start with ready-made instructions and suggested permissions.",
  specialtyHeading: "1. What should they help with?",
  recommended: "Featured expertise",
  recommendedAria: "Recommended expertise",
  templatesLoading: "Loading expertise…",
  templatesError: "Could not load expertise.",
  templatesEmpty:
    "No ready-made roles are available. You can write custom instructions in Advanced settings.",
  allTemplates: "All expertise",
  chooseTemplate: "Choose an expertise",
  identityHeading: "2. Find their place in your team",
  name: "Expert name",
  namePlaceholder: "For example: Alex",
  nameHelp: "Use the suggested name or choose your own.",
  role: "Responsibility",
  rolePlaceholder: "For example: Product and experience design",
  department: "Area of expertise",
  departmentPlaceholder: "For example: Design",
  departmentHelp: "Makes this expert easier to find in your team.",
  parent: "Who should they report to?",
  parentNone: "Directly to me",
  teamLoading: "Loading your team…",
  teamError:
    "Could not load the team. You can create an expert reporting directly to you.",
  advanced: "Advanced settings",
  advancedHelp: "Optional · model, working instructions, and permissions",
  modelMode: "Model selection",
  modelAuto: "Automatic selection (recommended)",
  modelManual: "Choose a model myself",
  modelHelp:
    "Automatic selection uses a suitable model from your connected providers.",
  fixedModel: "Fixed model",
  autoSummary: "Automatic model selection",
  custom: "Write my own working instructions",
  customHelp:
    "Define custom responsibilities instead of using a ready-made role.",
  prompt: "Working instructions",
  promptPlaceholder:
    "Describe the work, how to approach it, and what to deliver.",
  promptReview: "Review the working instructions",
  promptSource:
    "These instructions apply in the selected language. Instructions you write yourself are not automatically translated.",
  permissionsHeading: "Permissions",
  permissionsAria: "Expert permissions",
  permissionsHelp:
    "Permissions work together with the system's approval and workspace rules.",
  startHint: "Start by choosing an expertise.",
  customSummary: "Custom working instructions",
  cancel: "Cancel",
  submit: "Add expert",
  submitting: "Adding…",
  retry: "Try again",
  saveFailed:
    "Could not add the expert. Check your connection and try again. Your entries are preserved.",
  saved: "Expert added to your team",
  savedDescription: "Open their profile from Experts to assign work.",
  validation: {
    nameShort: "Use at least 2 characters for the expert's name.",
    nameLong: "Keep the name within 80 characters.",
    roleShort: "Describe the expert's responsibility.",
    roleLong: "Keep the responsibility within 120 characters.",
    departmentLong: "Keep the area of expertise within 120 characters.",
    promptLong: "The working instructions are too long; shorten them.",
    template: "Choose an expertise.",
    promptShort: "Describe the working instructions in at least 20 characters.",
    model: "Choose an available model that supports agent tools.",
  },
  permissions: {
    canBrowse: "Research information online",
    canUseTerminal: "Workspace files and tools",
    canDelegate: "Delegate work",
    canCreateSubAgents: "Create subordinate experts",
    canSpend: "Request spending",
    canDelete: "Request deletion",
    canPublish: "Request publication",
    canContactExternal: "Request external communication",
  },
  templates: {
    marketing_director: "Marketing Director",
    sales_director: "Sales Director",
    operations_director: "Operations Director",
    finance_director: "Finance Director",
    product_director: "Product Director",
    engineering_director: "Engineering Director",
    research_director: "Research Director",
    support_director: "Customer Support Director",
    content_director: "Content Director",
    ux_designer: "Design Expert",
    quality_engineer: "Quality Expert",
    data_analyst: "Data Analyst",
    automation_specialist: "Automation Expert",
    specialist: "General Specialist",
  },
  specialistSummary:
    "Takes a defined assignment through delivery and evidence-based verification.",
  model: {
    search: "Search the fixed model catalog",
    placeholder: "Search models or providers…",
    count: "Models",
    loading: "Loading the model catalog",
    error: "Could not load the model catalog.",
    stale:
      "Could not refresh the model catalog. Retry to confirm availability before selecting a model.",
    connection: "Connection required",
    connectReason: "Connect this provider from Connections.",
    toolsReason:
      "This model does not support agent tools; it is available for chat only.",
    default: "Default",
    free: "Free",
    noTools: "No tools · chat only",
    showMore: "Show up to 80 more models",
    empty: "No available models yet",
    noMatch: "No matching models",
    emptyHelp: "Add a model provider from Connections.",
    noMatchHelp: "Try another model or provider name.",
    sourceDescription: "Original catalog description",
    builtin: "Built-in fleet",
    tiers: {
      economy: "Economy",
      standard: "Standard",
      premium: "Premium",
      reasoning: "Reasoning",
    },
  },
} satisfies NewAgentCopy;
