import type { NewAgentCopy } from "../new-agent-copy";

export default {
  back: "返回專家清單",
  eyebrow: "擴充團隊",
  title: "新增專家。",
  description: "選擇專業領域並設定名稱，即可使用預設工作指示與建議權限。",
  specialtyHeading: "1. 希望專家協助什麼工作？",
  recommended: "推薦專業領域",
  recommendedAria: "推薦專業領域",
  templatesLoading: "正在載入專業領域…",
  templatesError: "無法載入專業領域。",
  templatesEmpty: "目前沒有預設角色。你可以在進階設定中撰寫自己的工作指示。",
  allTemplates: "所有專業領域",
  chooseTemplate: "選擇專業領域",
  identityHeading: "2. 確定專家在團隊中的職責",
  name: "專家名稱",
  namePlaceholder: "例如：小林",
  nameHelp: "使用建議名稱，或自行命名。",
  role: "職責",
  rolePlaceholder: "例如：產品與體驗設計",
  department: "專業領域",
  departmentPlaceholder: "例如：設計",
  departmentHelp: "方便在團隊中找到這位專家。",
  parent: "向誰回報？",
  parentNone: "直接向我回報",
  teamLoading: "正在載入團隊…",
  teamError: "無法載入團隊。仍可建立直接向你回報的專家。",
  advanced: "進階設定",
  advancedHelp: "選填 · 模型、工作指示與權限",
  modelMode: "模型選擇",
  modelAuto: "自動選擇（建議）",
  modelManual: "自行選擇模型",
  modelHelp: "自動選擇會從已連線的供應商中使用適合目前工作的模型。",
  fixedModel: "固定模型",
  autoSummary: "自動選擇模型",
  custom: "自行撰寫工作指示",
  customHelp: "自行定義職責，而不使用預設角色。",
  prompt: "工作指示",
  promptPlaceholder: "描述要完成的工作、工作方式與交付成果。",
  promptReview: "檢視工作指示",
  promptSource: "這些指示使用所選語言。您自行撰寫的指示不會自動翻譯。",
  permissionsHeading: "權限",
  permissionsAria: "專家權限",
  permissionsHelp: "這些權限與系統的核准規則及工作區規則共同生效。",
  startHint: "先選擇一個專業領域。",
  customSummary: "自訂工作指示",
  cancel: "取消",
  submit: "新增專家",
  submitting: "正在新增…",
  retry: "重試",
  saveFailed: "無法新增專家。請檢查網路連線後重試。已保留你填寫的內容。",
  saved: "專家已加入團隊",
  savedDescription: "在專家清單中開啟其個人資料，即可指派工作。",
  validation: {
    nameShort: "專家名稱至少需要 2 個字元。",
    nameLong: "名稱不能超過 80 個字元。",
    roleShort: "請描述專家的職責。",
    roleLong: "職責不能超過 120 個字元。",
    departmentLong: "專業領域不能超過 120 個字元。",
    promptLong: "工作指示過長，請縮短內容。",
    template: "請選擇專業領域。",
    promptShort: "工作指示至少需要 20 個字元。",
    model: "請選擇支援代理工具的可用模型。",
  },
  permissions: {
    canBrowse: "在網路上查找資訊",
    canUseTerminal: "使用工作區檔案與工具",
    canDelegate: "委派任務",
    canCreateSubAgents: "建立下屬專家",
    canSpend: "申請支出",
    canDelete: "申請刪除",
    canPublish: "申請發佈",
    canContactExternal: "申請對外溝通",
  },
  templates: {
    marketing_director: "行銷總監",
    sales_director: "業務總監",
    operations_director: "營運總監",
    finance_director: "財務總監",
    product_director: "產品總監",
    engineering_director: "工程總監",
    research_director: "研究總監",
    support_director: "客戶支援總監",
    content_director: "內容總監",
    ux_designer: "設計專家",
    quality_engineer: "品質專家",
    data_analyst: "資料分析師",
    automation_specialist: "自動化專家",
    specialist: "通用專家",
  },
  specialistSummary: "負責具體任務的交付，並透過證據驗證成果。",
  model: {
    search: "搜尋固定模型目錄",
    placeholder: "搜尋模型或供應商…",
    count: "模型數量",
    loading: "正在載入模型目錄",
    error: "無法載入模型目錄。",
    stale: "無法更新模型目錄。選擇模型前，請重試以確認其可用性。",
    connection: "需要連線",
    connectReason: "請在連線頁面連接此供應商。",
    toolsReason: "此模型不支援代理工具，僅可用於聊天。",
    default: "預設",
    free: "免費",
    noTools: "無工具 · 僅聊天",
    showMore: "再顯示最多 80 個模型",
    empty: "目前沒有可用模型",
    noMatch: "沒有相符的模型",
    emptyHelp: "可在連線頁面新增模型供應商。",
    noMatchHelp: "請嘗試其他模型或供應商名稱。",
    sourceDescription: "目錄原始說明",
    builtin: "內建模型",
    tiers: {
      economy: "經濟型",
      standard: "標準型",
      premium: "進階型",
      reasoning: "推理型",
    },
  },
} satisfies NewAgentCopy;
