import type { NewAgentCopy } from "../new-agent-copy";

export default {
  back: "العودة إلى الخبراء",
  eyebrow: "وسّع فريقك",
  title: "أضف خبيرًا جديدًا.",
  description: "اختر التخصص والاسم، وابدأ بتعليمات عمل جاهزة وصلاحيات مقترحة.",
  specialtyHeading: "1. في أي عمل تريد المساعدة؟",
  recommended: "تخصصات مقترحة",
  recommendedAria: "التخصصات المقترحة",
  templatesLoading: "جارٍ تحميل التخصصات…",
  templatesError: "تعذّر تحميل التخصصات.",
  templatesEmpty:
    "لا توجد أدوار جاهزة. يمكنك كتابة تعليماتك الخاصة في الإعدادات المتقدمة.",
  allTemplates: "كل التخصصات",
  chooseTemplate: "اختر تخصصًا",
  identityHeading: "2. حدّد مكانه في الفريق",
  name: "اسم الخبير",
  namePlaceholder: "مثلًا: نور",
  nameHelp: "استخدم الاسم المقترح أو اختر اسمًا آخر.",
  role: "المسؤولية",
  rolePlaceholder: "مثلًا: تصميم المنتج وتجربة المستخدم",
  department: "مجال التخصص",
  departmentPlaceholder: "مثلًا: التصميم",
  departmentHelp: "يسهّل العثور على هذا الخبير ضمن الفريق.",
  parent: "إلى من يرفع تقاريره؟",
  parentNone: "إليّ مباشرة",
  teamLoading: "جارٍ تحميل الفريق…",
  teamError: "تعذّر تحميل الفريق. يمكنك إنشاء خبير يرفع تقاريره إليك مباشرة.",
  advanced: "الإعدادات المتقدمة",
  advancedHelp: "اختياري · النموذج وتعليمات العمل والصلاحيات",
  modelMode: "اختيار النموذج",
  modelAuto: "اختيار تلقائي (موصى به)",
  modelManual: "سأختار النموذج بنفسي",
  modelHelp: "يستخدم الاختيار التلقائي نموذجًا مناسبًا من المزوّدين المتصلين.",
  fixedModel: "نموذج ثابت",
  autoSummary: "اختيار تلقائي للنموذج",
  custom: "سأكتب تعليمات العمل بنفسي",
  customHelp: "حدّد مسؤوليات خاصة بدلًا من استخدام دور جاهز.",
  prompt: "تعليمات العمل",
  promptPlaceholder:
    "صِف العمل المطلوب وطريقة تنفيذه والنتيجة التي يجب تسليمها.",
  promptReview: "مراجعة تعليمات العمل",
  promptSource:
    "تُطبَّق هذه التعليمات باللغة المختارة. لا تُترجم التعليمات التي تكتبها بنفسك تلقائيًا.",
  permissionsHeading: "الصلاحيات",
  permissionsAria: "صلاحيات الخبير",
  permissionsHelp:
    "تُطبَّق الصلاحيات إلى جانب قواعد الموافقة ومساحة العمل في النظام.",
  startHint: "ابدأ باختيار تخصص.",
  customSummary: "تعليمات عمل مخصصة",
  cancel: "إلغاء",
  submit: "إضافة الخبير",
  submitting: "جارٍ الإضافة…",
  retry: "إعادة المحاولة",
  saveFailed:
    "تعذّرت إضافة الخبير. تحقّق من الاتصال وأعد المحاولة. لم تفقد البيانات التي أدخلتها.",
  saved: "تمت إضافة الخبير إلى الفريق",
  savedDescription: "افتح ملفه من صفحة الخبراء لتكليفه بالعمل.",
  validation: {
    nameShort: "اكتب اسمًا للخبير من حرفين على الأقل.",
    nameLong: "يجب ألا يتجاوز الاسم 80 حرفًا.",
    roleShort: "صِف مسؤولية الخبير.",
    roleLong: "يجب ألا تتجاوز المسؤولية 120 حرفًا.",
    departmentLong: "يجب ألا يتجاوز مجال التخصص 120 حرفًا.",
    promptLong: "تعليمات العمل طويلة جدًا؛ اختصر النص.",
    template: "اختر تخصصًا.",
    promptShort: "اكتب تعليمات العمل في 20 حرفًا على الأقل.",
    model: "اختر نموذجًا متاحًا يدعم أدوات الوكيل.",
  },
  permissions: {
    canBrowse: "البحث عن معلومات على الإنترنت",
    canUseTerminal: "ملفات مساحة العمل وأدواتها",
    canDelegate: "تفويض المهام",
    canCreateSubAgents: "إنشاء خبراء تابعين",
    canSpend: "طلب الإنفاق",
    canDelete: "طلب الحذف",
    canPublish: "طلب النشر",
    canContactExternal: "طلب التواصل الخارجي",
  },
  templates: {
    marketing_director: "مدير التسويق",
    sales_director: "مدير المبيعات",
    operations_director: "مدير العمليات",
    finance_director: "المدير المالي",
    product_director: "مدير المنتج",
    engineering_director: "مدير الهندسة",
    research_director: "مدير الأبحاث",
    support_director: "مدير دعم العملاء",
    content_director: "مدير المحتوى",
    ux_designer: "خبير التصميم",
    quality_engineer: "خبير الجودة",
    data_analyst: "محلل البيانات",
    automation_specialist: "خبير الأتمتة",
    specialist: "خبير عام",
  },
  specialistSummary: "يتولى مهمة محددة حتى تسليمها والتحقق من نتائجها بالأدلة.",
  model: {
    search: "البحث في كتالوج النماذج الثابتة",
    placeholder: "ابحث عن نموذج أو مزوّد…",
    count: "النماذج",
    loading: "جارٍ تحميل كتالوج النماذج",
    error: "تعذّر تحميل كتالوج النماذج.",
    stale:
      "تعذّر تحديث كتالوج النماذج. أعد المحاولة للتحقق من التوفر قبل اختيار نموذج.",
    connection: "يلزم الاتصال",
    connectReason: "اربط هذا المزوّد من صفحة الاتصالات.",
    toolsReason:
      "لا يدعم هذا النموذج أدوات الوكيل؛ يمكن استخدامه للمحادثة فقط.",
    default: "الافتراضي",
    free: "مجاني",
    noTools: "بلا أدوات · للمحادثة فقط",
    showMore: "عرض ما يصل إلى 80 نموذجًا إضافيًا",
    empty: "لا توجد نماذج متاحة بعد",
    noMatch: "لا توجد نماذج مطابقة",
    emptyHelp: "يمكنك إضافة مزوّد نماذج من صفحة الاتصالات.",
    noMatchHelp: "جرّب اسم نموذج أو مزوّد آخر.",
    sourceDescription: "وصف الكتالوج الأصلي",
    builtin: "النماذج المدمجة",
    tiers: {
      economy: "اقتصادي",
      standard: "قياسي",
      premium: "متقدم",
      reasoning: "استدلال",
    },
  },
} satisfies NewAgentCopy;
