import type { ShellPack } from "../i18n";

export default {
  skillsLibrary: "技能与工具",
  skillsLoadError: "无法加载技能库。",
  historyPages: "记录分页",
  historyOlder: "较早记录",
  historyNewer: "较新记录",
  historyLatest: "最新记录",
  historyWindow: "第 {page} 页：{count} 条记录，每页最多 {limit} 条。",
  historyPaused: "正在查看较早的页面。自动刷新已暂停。",
  historyLoading: "正在加载页面…",
  historyError: "无法加载此页。此前已加载的记录仍会显示。",
  historyPageFilters: "搜索、筛选和计数仅针对已加载的页面。",
  eventRuntimeRegistered: "运行进程已注册",
  eventRuntimeStateChanged: "运行进程状态已更改",
  eventAttemptCreated: "任务尝试已创建",
  eventAttemptStateChanged: "任务尝试状态已更改",
  eventReceiptReserved: "操作记录已预留",
  eventReceiptStateChanged: "操作记录状态已更改",
  eventInvocationCreated: "工具调用已创建",
  eventInvocationStateChanged: "工具调用状态已更改",
  eventRecoveryRecorded: "恢复已记录",
  eventRuntimeControlChanged: "运行控制已更改",
  eventReconciliationRecorded: "结果核对已记录",
  eventHealthSampleRecorded: "系统健康测量已记录",
  roomCopyError: "无法加载公司聊天室语言文件。",
  approvalCopyError: "无法加载审批语言文件。",
  workforceCopyError: "无法加载团队页面语言文件。",
  languageDescription: "选择界面和代理回复所用的工作区语言。",
  localeSaving: "正在将语言保存到服务器…",
  localeSaved: "工作区语言已保存。",
  localeError: "无法保存语言，请重试。",
  home: "首页",
  projects: "项目",
  companyRoom: "团队讨论室",
  experts: "专家",
  teams: "团队",
  operations: "运营中心",
  activity: "活动",
  approvals: "审批",
  connections: "连接",
  workspaceGroup: "工作区",
  companyGroup: "公司",
  controlGroup: "控制",
  skipToContent: "跳转到主要内容",
  openMenu: "打开菜单",
  closeMenu: "关闭菜单",
  mainMenu: "主菜单",
  workingExperts: "工作中的专家：{count}",
  switchToLight: "切换到浅色主题",
  switchToDark: "切换到深色主题",
  signOut: "退出登录",
  signOutSecure: "结束安全会话",
  signingOut: "正在退出…",
  signOutFailed: "无法退出登录",
  signOutRetry: "会话可能仍处于登录状态。请重试。",
  close: "关闭",
  clearSearch: "清除搜索",
  searchPagesAndExperts: "搜索页面或专家",
  commandDescription: "打开页面、开始新工作或查找专家。",
  noResults: "未找到结果。",
  pages: "页面",
  commandResults: "搜索结果",
  expertsLoading: "正在加载专家…",
  expertsRetry: "无法加载专家 · 重试",
  projectStartBlocked: "新建项目 · 安全停止已启用",
  providerSetupMessage:
    "尚未连接可用模型。项目会保存，团队将在连接模型后开始工作。",
  providerSetupAction: "连接模型",
  notifications: "通知",
  openSearch: "打开搜索和命令面板",
  search: "搜索",
  createNew: "新建",
  new: "新建",
  newProject: "新建项目",
  newTeam: "新建团队",
  newExpert: "新建专家",
  project: "项目",
  projectOperations: "项目运营",
  expertDetail: "专家详情",
  agentChat: "智能体聊天",
  settings: "连接与设置",
  systemChecking: "正在检查系统",
  systemReady: "系统已就绪",
  apiUnavailable: "API 不可用",
  localWorkspace: "本地工作区",
  openSource: "开源",
  pageNotFound: "页面未找到",
  pageNotFoundDescription: "地址无效或页面已移动。",
  backHome: "返回首页",
  homeCopyError: "无法加载首页语言文件。",
  projectListCopyError: "无法加载项目页面语言文件。",
  newProjectCopyError: "无法加载新建项目页面语言文件。",
  agentDirectoryCopyError: "无法加载专家目录语言文件。",
  newAgentCopyError: "无法加载添加专家页面语言文件。",
  authCopyError: "无法加载登录页面语言文件。",
} satisfies ShellPack;
