import type { ShellPack } from "../i18n";

export default {
  skillsLibrary: "Beceriler ve araçlar",
  skillsLoadError: "Beceri kütüphanesi yüklenemedi.",
  historyPages: "Kayıt sayfaları",
  historyOlder: "Daha eski kayıtlar",
  historyNewer: "Daha yeni kayıtlar",
  historyLatest: "En son kayıtlar",
  historyWindow: "Sayfa {page}: {count} kayıt; sayfa başına en fazla {limit}.",
  historyPaused:
    "Eski bir sayfayı görüntülüyorsunuz. Otomatik yenileme duraklatıldı.",
  historyLoading: "Sayfa yükleniyor…",
  historyError:
    "Bu sayfa yüklenemedi. Önceden yüklenen kayıtlar görünür kalır.",
  historyPageFilters:
    "Arama, filtreler ve sayılar yüklenen sayfa için geçerlidir.",
  eventRuntimeRegistered: "Çalışma süreci kaydedildi",
  eventRuntimeStateChanged: "Çalışma sürecinin durumu değişti",
  eventAttemptCreated: "Görev denemesi oluşturuldu",
  eventAttemptStateChanged: "Görev denemesinin durumu değişti",
  eventReceiptReserved: "İşlem kaydı ayrıldı",
  eventReceiptStateChanged: "İşlem kaydının durumu değişti",
  eventInvocationCreated: "Araç çağrısı oluşturuldu",
  eventInvocationStateChanged: "Araç çağrısının durumu değişti",
  eventRecoveryRecorded: "Kurtarma kaydedildi",
  eventRuntimeControlChanged: "Çalışma denetimi değişti",
  eventReconciliationRecorded: "Sonuç uzlaştırması kaydedildi",
  eventHealthSampleRecorded: "Sistem sağlık ölçümü kaydedildi",
  roomCopyError: "Şirket Odası dil dosyası yüklenemedi.",
  approvalCopyError: "Onay ekranının dil dosyası yüklenemedi.",
  workforceCopyError: "Ekip ekranının dil dosyası yüklenemedi.",
  languageDescription:
    "Arayüz ve ajan yanıtları için çalışma alanı dilini seç.",
  localeSaving: "Dil sunucuya kaydediliyor…",
  localeSaved: "Dil çalışma alanına kaydedildi.",
  localeError: "Dil sunucuya kaydedilemedi. Yeniden dene.",
  home: "Ana Sayfa",
  projects: "Projelerim",
  companyRoom: "Şirket Odası",
  experts: "Uzmanlar",
  teams: "Ekipler",
  operations: "Operasyon Merkezi",
  activity: "Çalışmalar",
  approvals: "Onaylar",
  connections: "Bağlantılar",
  workspaceGroup: "Çalışma alanı",
  companyGroup: "Şirket",
  controlGroup: "Kontrol",
  skipToContent: "Ana içeriğe geç",
  openMenu: "Menüyü aç",
  closeMenu: "Menüyü kapat",
  mainMenu: "Ana menü",
  workingExperts: "Çalışan uzmanlar: {count}",
  switchToLight: "Açık temaya geç",
  switchToDark: "Koyu temaya geç",
  signOut: "Oturumu kapat",
  signOutSecure: "Güvenli oturumu kapat",
  signingOut: "Oturum kapatılıyor…",
  signOutFailed: "Oturum kapatılamadı",
  signOutRetry: "Oturumun açık kalmış olabilir. Yeniden dene.",
  close: "Kapat",
  clearSearch: "Aramayı temizle",
  searchPagesAndExperts: "Sayfa veya uzman ara",
  commandDescription: "Bir sayfaya git, yeni bir iş başlat veya uzmanını bul.",
  noResults: "Sonuç bulunamadı.",
  pages: "Sayfalar",
  commandResults: "Arama sonuçları",
  expertsLoading: "Uzmanlar yükleniyor…",
  expertsRetry: "Uzmanlar yüklenemedi · yeniden dene",
  projectStartBlocked: "Yeni proje · güvenlik freni etkin",
  providerSetupMessage:
    "Henüz kullanılabilir bir model bağlı değil. Projeyi şimdi kaydedebilirsin; model bağlandıktan sonra çalışmaya başlanır.",
  providerSetupChecking: "Kullanılabilir modeller kontrol ediliyor…",
  providerSetupError:
    "Model kullanılabilirliği kontrol edilemedi. Tekrar dene veya bağlantıları gözden geçir.",
  providerSetupAction: "Model bağla",
  notifications: "Bildirimler",
  openSearch: "Arama ve komut paletini aç",
  search: "Ara",
  createNew: "Yeni oluştur",
  new: "Yeni",
  newProject: "Yeni proje",
  newTeam: "Yeni ekip",
  newExpert: "Yeni uzman",
  project: "Proje",
  projectOperations: "Proje Operasyonu",
  expertDetail: "Uzman detayı",
  agentChat: "Ajan sohbeti",
  settings: "Bağlantılar ve Ayarlar",
  systemChecking: "Altyapı denetleniyor",
  systemReady: "Altyapı hazır",
  apiUnavailable: "API bağlantısı yok",
  localWorkspace: "Yerel çalışma alanı",
  openSource: "Açık kaynak",
  pageNotFound: "Sayfa bulunamadı",
  pageNotFoundDescription:
    "Bu adres geçerli değil veya sayfa taşınmış olabilir.",
  backHome: "Ana sayfaya dön",
  homeCopyError: "Ana ekranın dil dosyası yüklenemedi.",
  projectListCopyError: "Projeler listesinin dil dosyası yüklenemedi.",
  newProjectCopyError: "Yeni proje ekranının dil dosyası yüklenemedi.",
  agentDirectoryCopyError: "Uzman dizininin dil dosyası yüklenemedi.",
  newAgentCopyError: "Yeni uzman ekranının dil dosyası yüklenemedi.",
  authCopyError: "Giriş ekranının dil dosyası yüklenemedi.",
} satisfies ShellPack;
