import type { ShellPack } from "../i18n";

export default {
  skillsLibrary: "Навыки и инструменты",
  skillsLoadError: "Не удалось загрузить библиотеку навыков.",
  historyPages: "Страницы записей",
  historyOlder: "Более старые записи",
  historyNewer: "Более новые записи",
  historyLatest: "Последние записи",
  historyWindow: "Страница {page} · Записи: {count} · До {limit} на странице.",
  historyPaused:
    "Открыта более старая страница. Автоматическое обновление приостановлено.",
  historyLoading: "Загрузка страницы…",
  historyError:
    "Не удалось загрузить страницу. Ранее загруженные записи остаются видимыми.",
  historyPageFilters:
    "Поиск, фильтры и счётчики относятся к загруженной странице.",
  eventRuntimeRegistered: "Рабочий процесс зарегистрирован",
  eventRuntimeStateChanged: "Состояние рабочего процесса изменено",
  eventAttemptCreated: "Попытка выполнения задачи создана",
  eventAttemptStateChanged: "Состояние попытки выполнения задачи изменено",
  eventReceiptReserved: "Запись операции зарезервирована",
  eventReceiptStateChanged: "Состояние записи операции изменено",
  eventInvocationCreated: "Вызов инструмента создан",
  eventInvocationStateChanged: "Состояние вызова инструмента изменено",
  eventRecoveryRecorded: "Восстановление записано",
  eventRuntimeControlChanged: "Управление выполнением изменено",
  eventReconciliationRecorded: "Сверка результата записана",
  eventHealthSampleRecorded: "Измерение состояния системы записано",
  roomCopyError: "Не удалось загрузить языковой файл комнаты компании.",
  approvalCopyError: "Не удалось загрузить языковой файл согласований.",
  workforceCopyError: "Не удалось загрузить языковой файл студии команд.",
  languageDescription: "Выберите язык интерфейса и ответов агентов.",
  localeSaving: "Язык сохраняется на сервере…",
  localeSaved: "Язык сохранён для рабочего пространства.",
  localeError: "Не удалось сохранить язык. Повторите попытку.",
  home: "Главная",
  projects: "Проекты",
  companyRoom: "Комната команды",
  experts: "Специалисты",
  teams: "Команды",
  operations: "Операции",
  activity: "Активность",
  approvals: "Согласования",
  connections: "Подключения",
  workspaceGroup: "Рабочая область",
  companyGroup: "Компания",
  controlGroup: "Контроль",
  skipToContent: "Перейти к содержимому",
  openMenu: "Открыть меню",
  closeMenu: "Закрыть меню",
  mainMenu: "Главное меню",
  workingExperts: "Эксперты за работой: {count}",
  switchToLight: "Включить светлую тему",
  switchToDark: "Включить тёмную тему",
  signOut: "Выйти",
  signOutSecure: "Завершить защищённый сеанс",
  signingOut: "Выход…",
  signOutFailed: "Не удалось выйти",
  signOutRetry: "Сеанс может оставаться открытым. Повторите попытку.",
  close: "Закрыть",
  clearSearch: "Очистить поиск",
  searchPagesAndExperts: "Поиск страниц или специалистов",
  commandDescription:
    "Откройте страницу, начните работу или найдите специалиста.",
  noResults: "Ничего не найдено.",
  pages: "Страницы",
  commandResults: "Результаты поиска",
  expertsLoading: "Загружаем специалистов…",
  expertsRetry: "Не удалось загрузить специалистов · повторить",
  projectStartBlocked: "Новый проект · защитная остановка включена",
  providerSetupMessage:
    "Подходящая модель ещё не подключена. Проект можно сохранить сейчас; работа начнётся после подключения модели.",
  providerSetupChecking: "Проверяем доступные модели…",
  providerSetupError:
    "Не удалось проверить доступность модели. Повторите попытку или проверьте подключения.",
  providerSetupAction: "Подключить",
  notifications: "Уведомления",
  openSearch: "Открыть поиск и команды",
  search: "Поиск",
  createNew: "Создать",
  new: "Новое",
  newProject: "Новый проект",
  newTeam: "Новая команда",
  newExpert: "Новый специалист",
  project: "Проект",
  projectOperations: "Операции проекта",
  expertDetail: "Сведения о специалисте",
  agentChat: "Чат с агентом",
  settings: "Подключения и настройки",
  systemChecking: "Проверка системы",
  systemReady: "Система готова",
  apiUnavailable: "API недоступен",
  localWorkspace: "Локальная рабочая область",
  openSource: "Открытый код",
  pageNotFound: "Страница не найдена",
  pageNotFoundDescription: "Адрес неверен или страница была перемещена.",
  backHome: "На главную",
  homeCopyError: "Не удалось загрузить языковой файл главной страницы.",
  projectListCopyError: "Не удалось загрузить языковой файл страницы проектов.",
  newProjectCopyError:
    "Не удалось загрузить языковой файл страницы нового проекта.",
  agentDirectoryCopyError:
    "Не удалось загрузить языковой файл каталога экспертов.",
  newAgentCopyError:
    "Не удалось загрузить языковой файл страницы добавления эксперта.",
  authCopyError: "Не удалось загрузить языковой файл страницы входа.",
} satisfies ShellPack;
