import type { ShellPack } from "../i18n";

export default {
  skillsLibrary: "Skills & tools",
  skillsLoadError: "The skill library could not be loaded.",
  historyPages: "Record pages",
  historyOlder: "Older records",
  historyNewer: "Newer records",
  historyLatest: "Latest records",
  historyWindow: "Page {page} · Records: {count} · Up to {limit} per page.",
  historyPaused: "Viewing an older page. Automatic refresh is paused.",
  historyLoading: "Loading page…",
  historyError:
    "Could not load this page. Any previously loaded records remain visible.",
  historyPageFilters: "Search, filters and counts apply to the loaded page.",
  eventRuntimeRegistered: "Runtime registered",
  eventRuntimeStateChanged: "Runtime state changed",
  eventAttemptCreated: "Task attempt created",
  eventAttemptStateChanged: "Task attempt state changed",
  eventReceiptReserved: "Operation receipt reserved",
  eventReceiptStateChanged: "Operation receipt state changed",
  eventInvocationCreated: "Tool invocation created",
  eventInvocationStateChanged: "Tool invocation state changed",
  eventRecoveryRecorded: "Recovery recorded",
  eventRuntimeControlChanged: "Runtime control changed",
  eventReconciliationRecorded: "Outcome reconciliation recorded",
  eventHealthSampleRecorded: "System health sample recorded",
  roomCopyError: "Could not load the Company Room language file.",
  approvalCopyError: "Could not load the approval language file.",
  workforceCopyError: "Could not load the team page language file.",
  languageDescription:
    "Choose the workspace language for the interface and agent replies.",
  localeSaving: "Saving language to the server…",
  localeSaved: "Language saved for this workspace.",
  localeError: "Could not save the language to the server. Try again.",
  home: "Home",
  projects: "Projects",
  companyRoom: "Company room",
  experts: "Experts",
  teams: "Teams",
  operations: "Operations",
  activity: "Activity",
  approvals: "Approvals",
  connections: "Connections",
  workspaceGroup: "Workspace",
  companyGroup: "Company",
  controlGroup: "Control",
  skipToContent: "Skip to main content",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  mainMenu: "Main menu",
  workingExperts: "Working experts: {count}",
  switchToLight: "Switch to light theme",
  switchToDark: "Switch to dark theme",
  signOut: "Sign out",
  signOutSecure: "Sign out of the secure session",
  signingOut: "Signing out…",
  signOutFailed: "Could not sign out",
  signOutRetry: "Your session may still be open. Try again.",
  close: "Close",
  clearSearch: "Clear search",
  searchPagesAndExperts: "Search pages or experts",
  commandDescription: "Go to a page, start new work, or find your expert.",
  noResults: "No results found.",
  pages: "Pages",
  commandResults: "Search results",
  expertsLoading: "Loading experts…",
  expertsRetry: "Could not load experts · try again",
  projectStartBlocked: "New project · safety stop active",
  providerSetupMessage:
    "No usable model is connected yet. Your project is saved, and the team waits until you connect one.",
  providerSetupAction: "Connect a model",
  notifications: "Notifications",
  openSearch: "Open search and command palette",
  search: "Search",
  createNew: "Create new",
  new: "New",
  newProject: "New project",
  newTeam: "New team",
  newExpert: "New expert",
  project: "Project",
  projectOperations: "Project operations",
  expertDetail: "Expert details",
  agentChat: "Agent chat",
  settings: "Connections and settings",
  systemChecking: "Checking system",
  systemReady: "System ready",
  apiUnavailable: "API unavailable",
  localWorkspace: "Local workspace",
  openSource: "Open source",
  pageNotFound: "Page not found",
  pageNotFoundDescription:
    "This address is invalid or the page may have moved.",
  backHome: "Back to home",
  homeCopyError: "Could not load the home page language file.",
  projectListCopyError: "Could not load the Projects page language file.",
  newProjectCopyError: "Could not load the New project page language file.",
  agentDirectoryCopyError: "Could not load the expert directory language file.",
  newAgentCopyError: "Could not load the New expert page language file.",
  authCopyError: "Could not load the sign-in language file.",
} satisfies ShellPack;
