import type { ShellPack } from "../i18n";

export default {
  skillsLibrary: "Fähigkeiten & Werkzeuge",
  skillsLoadError: "Die Bibliothek konnte nicht geladen werden.",
  historyPages: "Datensatzseiten",
  historyOlder: "Ältere Einträge",
  historyNewer: "Neuere Einträge",
  historyLatest: "Neueste Einträge",
  historyWindow: "Seite {page} · Einträge: {count} · Bis zu {limit} pro Seite.",
  historyPaused:
    "Sie sehen eine ältere Seite. Die automatische Aktualisierung ist pausiert.",
  historyLoading: "Seite wird geladen…",
  historyError:
    "Diese Seite konnte nicht geladen werden. Bereits geladene Einträge bleiben sichtbar.",
  historyPageFilters:
    "Suche, Filter und Anzahlen beziehen sich auf die geladene Seite.",
  eventRuntimeRegistered: "Laufzeit registriert",
  eventRuntimeStateChanged: "Laufzeitstatus geändert",
  eventAttemptCreated: "Aufgabenversuch erstellt",
  eventAttemptStateChanged: "Status des Aufgabenversuchs geändert",
  eventReceiptReserved: "Vorgangsbeleg reserviert",
  eventReceiptStateChanged: "Status des Vorgangsbelegs geändert",
  eventInvocationCreated: "Werkzeugaufruf erstellt",
  eventInvocationStateChanged: "Status des Werkzeugaufrufs geändert",
  eventRecoveryRecorded: "Wiederherstellung erfasst",
  eventRuntimeControlChanged: "Laufzeitsteuerung geändert",
  eventReconciliationRecorded: "Ergebnisabgleich erfasst",
  eventHealthSampleRecorded: "Systemzustandsmessung erfasst",
  roomCopyError:
    "Die Sprachdatei des Unternehmensraums konnte nicht geladen werden.",
  approvalCopyError:
    "Die Sprachdatei für Freigaben konnte nicht geladen werden.",
  workforceCopyError:
    "Die Sprachdatei des Teamstudios konnte nicht geladen werden.",
  languageDescription: "Wähle die Sprache für Oberfläche und Agentenantworten.",
  localeSaving: "Sprache wird auf dem Server gespeichert…",
  localeSaved: "Sprache für diesen Arbeitsbereich gespeichert.",
  localeError: "Die Sprache konnte nicht gespeichert werden. Erneut versuchen.",
  home: "Startseite",
  projects: "Projekte",
  companyRoom: "Teamraum",
  experts: "Fachkräfte",
  teams: "Teams",
  operations: "Betrieb",
  activity: "Aktivität",
  approvals: "Freigaben",
  connections: "Verbindungen",
  workspaceGroup: "Arbeitsbereich",
  companyGroup: "Unternehmen",
  controlGroup: "Kontrolle",
  skipToContent: "Zum Hauptinhalt springen",
  openMenu: "Menü öffnen",
  closeMenu: "Menü schließen",
  mainMenu: "Hauptmenü",
  workingExperts: "Arbeitende Fachkräfte: {count}",
  switchToLight: "Zum hellen Design wechseln",
  switchToDark: "Zum dunklen Design wechseln",
  signOut: "Abmelden",
  signOutSecure: "Sichere Sitzung beenden",
  signingOut: "Abmeldung läuft…",
  signOutFailed: "Abmeldung fehlgeschlagen",
  signOutRetry:
    "Deine Sitzung ist möglicherweise noch offen. Versuche es erneut.",
  close: "Schließen",
  clearSearch: "Suche löschen",
  searchPagesAndExperts: "Seiten oder Fachkräfte suchen",
  commandDescription:
    "Öffne eine Seite, starte neue Arbeit oder finde eine Fachkraft.",
  noResults: "Keine Ergebnisse gefunden.",
  pages: "Seiten",
  commandResults: "Suchergebnisse",
  expertsLoading: "Fachkräfte werden geladen…",
  expertsRetry: "Fachkräfte konnten nicht geladen werden · erneut versuchen",
  projectStartBlocked: "Neues Projekt · Sicherheitsstopp aktiv",
  providerSetupMessage:
    "Noch ist kein nutzbares Modell verbunden. Du kannst jetzt ein Projekt speichern; die Arbeit beginnt, sobald ein Modell verbunden ist.",
  providerSetupChecking: "Verfügbare Modelle werden geprüft…",
  providerSetupError:
    "Die Modellverfügbarkeit konnte nicht geprüft werden. Versuche es erneut oder prüfe deine Verbindungen.",
  providerSetupAction: "Modell verbinden",
  notifications: "Benachrichtigungen",
  openSearch: "Suche und Befehle öffnen",
  search: "Suchen",
  createNew: "Neu erstellen",
  new: "Neu",
  newProject: "Neues Projekt",
  newTeam: "Neues Team",
  newExpert: "Neue Fachkraft",
  project: "Projekt",
  projectOperations: "Projektbetrieb",
  expertDetail: "Details zur Fachkraft",
  agentChat: "Agentenchat",
  settings: "Verbindungen und Einstellungen",
  systemChecking: "System wird geprüft",
  systemReady: "System bereit",
  apiUnavailable: "API nicht erreichbar",
  localWorkspace: "Lokaler Arbeitsbereich",
  openSource: "Open Source",
  pageNotFound: "Seite nicht gefunden",
  pageNotFoundDescription:
    "Diese Adresse ist ungültig oder die Seite wurde verschoben.",
  backHome: "Zur Startseite",
  homeCopyError:
    "Die Sprachdatei für die Startseite konnte nicht geladen werden.",
  projectListCopyError:
    "Die Sprachdatei für die Projektseite konnte nicht geladen werden.",
  newProjectCopyError:
    "Die Sprachdatei für die Seite Neues Projekt konnte nicht geladen werden.",
  agentDirectoryCopyError:
    "Die Sprachdatei für das Fachkräfteverzeichnis konnte nicht geladen werden.",
  newAgentCopyError:
    "Die Sprachdatei für die Seite „Experten hinzufügen“ konnte nicht geladen werden.",
  authCopyError:
    "Die Sprachdatei für die Anmeldung konnte nicht geladen werden.",
} satisfies ShellPack;
