import type { ShellPack } from "../i18n";

export default {
  skillsLibrary: "المهارات والأدوات",
  skillsLoadError: "تعذّر تحميل مكتبة المهارات.",
  historyPages: "صفحات السجلات",
  historyOlder: "سجلات أقدم",
  historyNewer: "سجلات أحدث",
  historyLatest: "أحدث السجلات",
  historyWindow:
    "الصفحة {page} · عدد السجلات: {count} · الحد الأقصى لكل صفحة: {limit}.",
  historyPaused: "تعرض صفحة أقدم. التحديث التلقائي متوقف مؤقتًا.",
  historyLoading: "جارٍ تحميل الصفحة…",
  historyError: "تعذر تحميل هذه الصفحة. تبقى السجلات المحمّلة سابقًا ظاهرة.",
  historyPageFilters: "يُطبّق البحث والتصفية والأعداد على الصفحة المحمّلة.",
  eventRuntimeRegistered: "تم تسجيل عملية التشغيل",
  eventRuntimeStateChanged: "تغيّرت حالة عملية التشغيل",
  eventAttemptCreated: "تم إنشاء محاولة للمهمة",
  eventAttemptStateChanged: "تغيّرت حالة محاولة المهمة",
  eventReceiptReserved: "تم حجز سجل العملية",
  eventReceiptStateChanged: "تغيّرت حالة سجل العملية",
  eventInvocationCreated: "تم إنشاء استدعاء الأداة",
  eventInvocationStateChanged: "تغيّرت حالة استدعاء الأداة",
  eventRecoveryRecorded: "تم تسجيل الاستعادة",
  eventRuntimeControlChanged: "تغيّر التحكم في التشغيل",
  eventReconciliationRecorded: "تم تسجيل مطابقة النتيجة",
  eventHealthSampleRecorded: "تم تسجيل قياس صحة النظام",
  roomCopyError: "تعذّر تحميل ملف لغة غرفة الشركة.",
  approvalCopyError: "تعذّر تحميل ملف لغة الموافقات.",
  workforceCopyError: "تعذّر تحميل ملف لغة صفحة الفرق.",
  languageDescription: "اختر لغة الواجهة وردود الوكلاء لمساحة العمل.",
  localeSaving: "جارٍ حفظ اللغة على الخادم…",
  localeSaved: "حُفظت لغة مساحة العمل.",
  localeError: "تعذّر حفظ اللغة على الخادم. حاول مجددًا.",
  home: "الرئيسية",
  projects: "المشاريع",
  companyRoom: "غرفة الفريق",
  experts: "الخبراء",
  teams: "الفرق",
  operations: "مركز العمليات",
  activity: "النشاط",
  approvals: "الموافقات",
  connections: "الاتصالات",
  workspaceGroup: "مساحة العمل",
  companyGroup: "الشركة",
  controlGroup: "التحكم",
  skipToContent: "انتقل إلى المحتوى الرئيسي",
  openMenu: "افتح القائمة",
  closeMenu: "أغلق القائمة",
  mainMenu: "القائمة الرئيسية",
  workingExperts: "الخبراء قيد العمل: {count}",
  switchToLight: "التبديل إلى المظهر الفاتح",
  switchToDark: "التبديل إلى المظهر الداكن",
  signOut: "تسجيل الخروج",
  signOutSecure: "إنهاء الجلسة الآمنة",
  signingOut: "جارٍ تسجيل الخروج…",
  signOutFailed: "تعذر تسجيل الخروج",
  signOutRetry: "قد تكون جلستك لا تزال مفتوحة. حاول مجددًا.",
  close: "إغلاق",
  clearSearch: "مسح البحث",
  searchPagesAndExperts: "ابحث عن صفحة أو خبير",
  commandDescription: "افتح صفحة أو ابدأ عملًا جديدًا أو اعثر على خبيرك.",
  noResults: "لم يتم العثور على نتائج.",
  pages: "الصفحات",
  commandResults: "نتائج البحث",
  expertsLoading: "جارٍ تحميل الخبراء…",
  expertsRetry: "تعذر تحميل الخبراء · حاول مجددًا",
  projectStartBlocked: "مشروع جديد · إيقاف الأمان مفعّل",
  notifications: "الإشعارات",
  openSearch: "افتح البحث ولوحة الأوامر",
  search: "بحث",
  createNew: "إنشاء جديد",
  new: "جديد",
  newProject: "مشروع جديد",
  newTeam: "فريق جديد",
  newExpert: "خبير جديد",
  project: "مشروع",
  projectOperations: "عمليات المشروع",
  expertDetail: "تفاصيل الخبير",
  agentChat: "محادثة الوكيل",
  settings: "الاتصالات والإعدادات",
  systemChecking: "جارٍ فحص النظام",
  systemReady: "النظام جاهز",
  apiUnavailable: "واجهة API غير متاحة",
  localWorkspace: "مساحة عمل محلية",
  openSource: "مفتوح المصدر",
  pageNotFound: "الصفحة غير موجودة",
  pageNotFoundDescription: "العنوان غير صالح أو ربما نُقلت الصفحة.",
  backHome: "العودة إلى الرئيسية",
  homeCopyError: "تعذّر تحميل ملف لغة الصفحة الرئيسية.",
  projectListCopyError: "تعذّر تحميل ملف لغة صفحة المشاريع.",
  newProjectCopyError: "تعذّر تحميل ملف لغة صفحة المشروع الجديد.",
  agentDirectoryCopyError: "تعذّر تحميل ملف لغة دليل الخبراء.",
  newAgentCopyError: "تعذّر تحميل ملف لغة صفحة إضافة الخبير.",
  authCopyError: "تعذّر تحميل ملف لغة تسجيل الدخول.",
} satisfies ShellPack;
