CREATE TABLE "inference_usage_corrections" (
	"attempt_id" uuid PRIMARY KEY NOT NULL,
	"receipt_id" integer NOT NULL,
	"applied_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "inference_usage_corrections" ADD CONSTRAINT "inference_usage_corrections_attempt_id_inference_response_evidence_attempt_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."inference_response_evidence"("attempt_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inference_usage_corrections" ADD CONSTRAINT "inference_usage_corrections_receipt_id_usage_events_id_fk" FOREIGN KEY ("receipt_id") REFERENCES "public"."usage_events"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "inference_usage_corrections_receipt_unique" ON "inference_usage_corrections" USING btree ("receipt_id");--> statement-breakpoint
CREATE VIEW "public"."effective_usage_events" AS (select "usage_events"."id", "usage_events"."agent_id", "usage_events"."task_id", "usage_events"."kind", "usage_events"."model_id", "usage_events"."provider", "usage_events"."inference_key", "usage_events"."ordinary_inference_id", case when "inference_attempts"."evidence_conflict_at" is not null then false when "inference_response_evidence"."attempt_id" is not null then true else "usage_events"."usage_reported" end as "usage_reported", "usage_events"."outcome", "usage_events"."failure_kind", case when "inference_response_evidence"."attempt_id" is not null then "inference_response_evidence"."prompt_tokens" else "usage_events"."prompt_tokens" end as "prompt_tokens", case when "inference_response_evidence"."attempt_id" is not null then "inference_response_evidence"."completion_tokens" else "usage_events"."completion_tokens" end as "completion_tokens", case when "inference_response_evidence"."attempt_id" is not null then "inference_response_evidence"."total_tokens" else "usage_events"."total_tokens" end as "total_tokens", coalesce("inference_response_evidence"."reported_cost_usd","usage_events"."reported_cost_usd") as "reported_cost_usd", "usage_events"."created_at" from "usage_events" left join "inference_attempts" on "inference_attempts"."id" = "usage_events"."ordinary_inference_id" left join "inference_usage_corrections" on ("inference_usage_corrections"."receipt_id" = "usage_events"."id" and "inference_usage_corrections"."attempt_id" = "usage_events"."ordinary_inference_id") left join "inference_response_evidence" on ("inference_response_evidence"."attempt_id" = "inference_usage_corrections"."attempt_id" and "inference_response_evidence"."model_id" = "usage_events"."model_id" and "inference_response_evidence"."provider" = "usage_events"."provider"));