import type { MeetingTurnCopy } from "../meeting-turn-copy";
const copy: MeetingTurnCopy = {
  outcomeHelp: "此轮保存的回复，并非会议的当前状态。",
  recordedFailure: "已保存的结果报告了错误。请检查现有回复及未回复的专家。",
  skipped: "没有已保存回复的专家",
  skip_busy: "忙碌",
  skip_unavailable: "不可用",
  skip_empty_response: "未生成回复",
  skip_model_error: "回复生成失败",
  skip_provider_unavailable: "提供商不可用",
  skip_budget_guard: "已达到回复预算",
  inboxTitle: "已保存的会议轮次",
  inboxHelp:
    "即使会议未列出，本项目已保存的请求仍可在此查看。这些记录属于当前浏览器标签页；清除它们不会取消服务器上的工作。",
  meetingId: "会议 ID",
  participants: "已保存的参与者 ID",
  defaultParticipants: "已保存的请求中未指定",
  noParticipants: "空参与者列表",
  tokenLimit: "已保存的响应令牌上限",
  defaultLimit: "未指定；使用服务器默认值",
  damagedTitle: "损坏的轮次记录",
  reviewDamaged: "检查损坏的记录",
  damagedHelp:
    "下方显示原始本地内容。清除前请复制所需证据。无法根据损坏的数据发送请求。",
  clearDamaged: "清除已检查的本地记录",
  clearHelp:
    "我已检查并保留所需证据。清除此本地副本不会取消已接受的轮次或删除其服务器记录。",
  localKey: "本地记录键",
  storageReadError:
    "无法完整读取已保存的请求。这不代表列表为空。请恢复浏览器存储并刷新。",
  refreshInbox: "刷新已保存的记录",
  changed: "记录已更改或无法清除。请刷新列表并检查当前记录。",
  previous: "上一页记录",
  next: "下一页记录",
  scanMore: "扫描更多已保存的记录",
  scanIncomplete: "存储扫描尚未完成。可能存在其他请求；请继续扫描以查找。",
  pageSummary: "已找到 {count} 条记录，显示第 {from}–{to} 条",
  title: "恢复会议轮次",
  help: "原始请求已保存在此浏览器标签页中。刷新或检查回执不会启动新轮次。",
  prompt: "已保存的操作员消息",
  pending: "响应尚未确认。再次发送前请检查已记录的结果。",
  check: "检查已记录的结果",
  checking: "正在检查…",
  running: "已接受的轮次仍在运行，请稍后再次检查。",
  notRecorded: "未找到回执。你可以明确重试同一请求标识和原始输入。",
  retry: "重试原始请求",
  recorded: "此轮次已结束，结果已记录。继续前请检查会议记录。",
  unconfirmed: "已接受轮次的结果尚未确认。同一标识不会再次执行。",
  review: "检查并继续",
  reviewHelp:
    "这只会清除本地标记，不会取消服务器上的工作。缺少凭据不能证明请求从未被接受。新轮次可能重复工作或产生模型用量；请先检查已保存的输入及可用会议记录。",
  continue: "我已检查记录",
  cancel: "保留恢复状态",
  storage: "浏览器存储不可用。保存恢复标识前无法发送新轮次。",
  invalid:
    "无法读取保存的恢复记录。请保留此标签页，并在开始新轮次前检查存储的记录。",
  loadError: "无法验证回执。原始请求仍被保留。",
  recordId: "请求标识",
  requestFailed: "轮次响应尚未确认。请使用恢复面板检查已保存的结果。",
};
export default copy;
