import type { MeetingTurnCopy } from "../meeting-turn-copy";
const copy: MeetingTurnCopy = {
  outcomeHelp: "此輪儲存的回覆，並非會議的目前狀態。",
  recordedFailure: "已儲存的結果回報了錯誤。請檢查現有回覆及未回覆的專家。",
  skipped: "沒有已儲存回覆的專家",
  skip_busy: "忙碌",
  skip_unavailable: "無法使用",
  skip_empty_response: "未產生回覆",
  skip_model_error: "回覆產生失敗",
  skip_provider_unavailable: "供應商無法使用",
  skip_budget_guard: "已達回覆預算",
  inboxTitle: "已儲存的會議回合",
  inboxHelp:
    "即使會議未列出，本專案已儲存的請求仍可在此查看。這些記錄屬於目前的瀏覽器分頁；清除它們不會取消伺服器上的工作。",
  meetingId: "會議 ID",
  participants: "已儲存的參與者 ID",
  defaultParticipants: "已儲存的請求中未指定",
  noParticipants: "空參與者清單",
  tokenLimit: "已儲存的回應 Token 上限",
  defaultLimit: "未指定；使用伺服器預設值",
  damagedTitle: "損壞的回合記錄",
  reviewDamaged: "檢查損壞的記錄",
  damagedHelp:
    "下方顯示原始本機內容。清除前請複製所需證據。無法根據損壞的資料傳送請求。",
  clearDamaged: "清除已檢查的本機記錄",
  clearHelp:
    "我已檢查並保留所需證據。清除此本機副本不會取消已接受的回合或刪除其伺服器記錄。",
  localKey: "本機記錄鍵",
  storageReadError:
    "無法完整讀取已儲存的請求。這不代表清單為空。請恢復瀏覽器儲存功能並重新整理。",
  refreshInbox: "重新整理已儲存的記錄",
  changed: "記錄已變更或無法清除。請重新整理清單並檢查目前的記錄。",
  previous: "上一頁記錄",
  next: "下一頁記錄",
  scanMore: "掃描更多已儲存的記錄",
  scanIncomplete: "儲存空間掃描尚未完成。可能存在其他請求；請繼續掃描以尋找。",
  pageSummary: "已找到 {count} 筆記錄，顯示第 {from}–{to} 筆",
  title: "恢復會議輪次",
  help: "原始請求已儲存在此瀏覽器分頁中。重新整理或檢查回執不會啟動新輪次。",
  prompt: "已儲存的操作員訊息",
  pending: "回應尚未確認。再次傳送前請檢查已記錄的結果。",
  check: "檢查已記錄的結果",
  checking: "正在檢查…",
  running: "已接受的輪次仍在執行，請稍後再次檢查。",
  notRecorded: "未找到回執。你可以明確重試相同請求識別碼與原始輸入。",
  retry: "重試原始請求",
  recorded: "此輪次已結束，結果已記錄。繼續前請檢查會議紀錄。",
  unconfirmed: "已接受輪次的結果尚未確認。相同識別碼不會再次執行。",
  review: "檢查並繼續",
  reviewHelp:
    "這只會清除本機標記，不會取消伺服器上的工作。缺少憑據不能證明請求從未被接受。新回合可能重複工作或產生模型用量；請先檢查已儲存的輸入及可用會議記錄。",
  continue: "我已檢查紀錄",
  cancel: "保留恢復狀態",
  storage: "瀏覽器儲存空間無法使用。儲存恢復識別碼前無法傳送新輪次。",
  invalid:
    "無法讀取已儲存的恢復紀錄。請保留此分頁，並在開始新輪次前檢查儲存的紀錄。",
  loadError: "無法驗證回執。原始請求仍被保留。",
  recordId: "請求識別碼",
  requestFailed: "輪次回應尚未確認。請使用恢復面板檢查已儲存的結果。",
};
export default copy;
