import type { WorkforceCopy } from "../workforce-copy";

export default {
  storageError:
    "This tab could not save the request. Installation has not started. Check your browser's site storage settings.",
  eyebrow: "Ready-made teams",
  title: "Team Studio",
  description:
    "Choose a team, review its roles and handoffs, then install it under an existing manager.",
  library: "Team templates",
  roles: "Roles",
  crew: "Flexible team",
  flow: "Sequential workflow",
  recommended: "Best suited for",
  triggers: "Starting topics",
  structure: "Team structure",
  handoffs: "Work handoffs",
  noHandoffs: "No handoffs are defined for this team.",
  manager: "Manager",
  expert: "Expert",
  reportsTo: "Reports to",
  selectedManager: "Selected manager",
  ai: "AI routing",
  next: "Next step",
  review: "Review",
  configure: "Configure team",
  setup: "Install team",
  managerHelp:
    "Only active managers with permission to create experts are listed.",
  noManagers: "No eligible manager is available.",
  outcome: "First outcome (optional)",
  outcomePlaceholder: "Describe the result you want this team to deliver.",
  outcomeHelp: "Leave this blank to install the team without starting work.",
  outcomeInvalid: "Enter at least 3 characters or leave this blank.",
  finite: "One outcome",
  continuous: "Continuous",
  cadence: "Repeat every",
  hour: "Hour",
  fourHours: "4 hours",
  day: "Day",
  week: "Week",
  scope: "Permissions follow the selected manager's limits.",
  approval: "Actions requiring approval remain subject to approval.",
  atomic: "Team members and the optional task are saved together.",
  install: "Install team",
  installStart: "Install and start",
  installing: "Installing…",
  installed: "Team installed",
  receipt: "Installation receipt",
  openTask: "Open live task",
  another: "Create another team",
  retry: "Try again",
  loading: "Loading Team Studio",
  loadError: "Could not load team or manager data.",
  empty: "No team templates are available.",
  stale:
    "Some data could not be refreshed. Review the updated catalog before installing.",
  safetyUnknown: "Safety status could not be verified. Installation is paused.",
  stopped: "Emergency stop is active. New teams cannot be installed.",
  unknown:
    "The installation result is unknown. Your request is saved in this browser tab. Recover it before starting another team.",
  recover: "Recover installation",
  rejected:
    "The server rejected this installation. Review your entries and try again.",
  versionChanged:
    "The template changed. Refresh it and review the new version.",
  managerChanged:
    "The manager is no longer eligible. Refresh the list and select another manager.",
  capacity: "The workspace has reached its agent or task limit.",
} satisfies WorkforceCopy;
