import type { WorkforceCopy } from "../workforce-copy";

export default {
  storageError:
    "İstek bu sekmede güvenli biçimde saklanamadı. Kurulum başlatılmadı. Tarayıcının site depolama ayarlarını kontrol et.",
  eyebrow: "Hazır ekipler",
  title: "Ekip Stüdyosu",
  description:
    "Bir ekip şablonu seç, roller ile görev devirlerini incele ve mevcut bir yöneticinin altında kur.",
  library: "Ekip şablonları",
  roles: "Roller",
  crew: "Esnek ekip",
  flow: "Sıralı akış",
  recommended: "Uygun olduğu işler",
  triggers: "Başlatma konuları",
  structure: "Ekip yapısı",
  handoffs: "Görev devirleri",
  noHandoffs: "Bu ekip şablonunda kayıtlı görev devri yok.",
  manager: "Yönetici",
  expert: "Uzman",
  reportsTo: "Bağlı olduğu rol",
  selectedManager: "Seçilen yönetici",
  ai: "AI yönlendirme",
  next: "Sıradaki adım",
  review: "İnceleme",
  configure: "Ekibi yapılandır",
  setup: "Ekip kurulumu",
  managerHelp:
    "Yalnızca uzman oluşturma izni olan aktif yöneticiler listelenir.",
  noManagers: "Kurulum için uygun yönetici bulunamadı.",
  outcome: "İlk sonuç (isteğe bağlı)",
  outcomePlaceholder: "Bu ekibin teslim etmesini istediğin sonucu yaz.",
  outcomeHelp: "Çalışma başlatmadan yalnızca ekibi kurmak için boş bırak.",
  outcomeInvalid: "En az 3 karakter yaz veya boş bırak.",
  finite: "Tek sonuç",
  continuous: "Sürekli",
  cadence: "Tekrar sıklığı",
  hour: "Her saat",
  fourHours: "4 saatte bir",
  day: "Her gün",
  week: "Her hafta",
  scope: "İzinler seçilen yöneticinin yetkileriyle sınırlıdır.",
  approval: "Onay gerektiren işlemler onaya tabi kalır.",
  atomic: "Ekip üyeleri ve varsa ilk görev birlikte kaydedilir.",
  install: "Ekibi kur",
  installStart: "Ekibi kur ve başlat",
  installing: "Kuruluyor…",
  installed: "Ekip kuruldu",
  receipt: "Kurulum makbuzu",
  openTask: "Canlı işi aç",
  another: "Başka ekip kur",
  retry: "Yeniden dene",
  loading: "Ekip Stüdyosu yükleniyor",
  loadError: "Ekip veya yönetici verisi yüklenemedi.",
  empty: "Kullanılabilir ekip şablonu yok.",
  stale: "Bazı veriler yenilenemedi. Kurulumdan önce güncel kataloğu incele.",
  safetyUnknown: "Güvenlik durumu doğrulanamadı. Kurulum bekletiliyor.",
  stopped: "Acil durdurma etkin. Yeni ekip kurulamaz.",
  unknown:
    "Kurulumun sonucu henüz bilinmiyor. İstek bu tarayıcı sekmesinde saklandı. Başka ekip kurmadan önce sonucu kurtar.",
  recover: "Kurulumu kurtar",
  rejected:
    "Sunucu kurulumu reddetti. Bilgilerini gözden geçirip yeniden dene.",
  versionChanged: "Şablon değişti. Yenileyip yeni sürümü incele.",
  managerChanged:
    "Yönetici artık uygun değil. Listeyi yenileyip başka yönetici seç.",
  capacity: "Çalışma alanının uzman veya görev sınırına ulaşıldı.",
} satisfies WorkforceCopy;
