import type { WorkforceCopy } from "../workforce-copy";

export default {
  storageError:
    "此标签页无法保存请求，尚未开始创建。请检查浏览器的网站存储设置。",
  eyebrow: "预设团队",
  title: "团队工作室",
  description: "选择团队，查看角色和任务交接，再将其创建在现有负责人之下。",
  library: "团队模板",
  roles: "角色",
  crew: "灵活团队",
  flow: "顺序流程",
  recommended: "适用任务",
  triggers: "启动主题",
  structure: "团队结构",
  handoffs: "任务交接",
  noHandoffs: "此团队尚未定义任务交接。",
  manager: "负责人",
  expert: "专家",
  reportsTo: "汇报对象",
  selectedManager: "所选负责人",
  ai: "AI 分配",
  next: "下一步",
  review: "审核",
  configure: "配置团队",
  setup: "创建团队",
  managerHelp: "仅列出拥有创建专家权限的活跃负责人。",
  noManagers: "没有符合条件的负责人。",
  outcome: "首个目标（可选）",
  outcomePlaceholder: "描述希望团队交付的成果。",
  outcomeHelp: "留空可仅创建团队，不启动任务。",
  outcomeInvalid: "请输入至少 3 个字符，或留空。",
  finite: "单个目标",
  continuous: "持续运行",
  cadence: "重复周期",
  hour: "每小时",
  fourHours: "每 4 小时",
  day: "每天",
  week: "每周",
  scope: "权限受所选负责人的权限范围限制。",
  approval: "需要批准的操作仍需获得批准。",
  atomic: "团队成员与可选的首个任务会一并保存。",
  install: "创建团队",
  installStart: "创建并启动",
  installing: "正在创建…",
  installed: "团队已创建",
  receipt: "创建凭据",
  openTask: "打开当前任务",
  another: "创建另一个团队",
  retry: "重试",
  loading: "正在加载团队工作室",
  loadError: "无法加载团队或负责人数据。",
  empty: "没有可用的团队模板。",
  stale: "部分数据无法刷新。创建前请查看最新目录。",
  safetyUnknown: "无法确认安全状态。创建已暂停。",
  stopped: "紧急停止已开启，无法创建新团队。",
  unknown:
    "创建结果未知。请求已保存在此浏览器标签页中。创建另一个团队前，请先恢复此请求的结果。",
  recover: "恢复创建结果",
  rejected: "服务器拒绝了此次创建。请检查输入后重试。",
  versionChanged: "模板已更改。请刷新并检查新版本。",
  managerChanged: "负责人已不符合条件。请刷新列表并重新选择。",
  capacity: "已达到专家或任务数量上限。",
} satisfies WorkforceCopy;
