import type { WorkforceCopy } from "../workforce-copy";

export default {
  storageError:
    "此分頁無法儲存請求，尚未開始建立。請檢查瀏覽器的網站儲存設定。",
  eyebrow: "預設團隊",
  title: "團隊工作室",
  description: "選擇團隊，查看角色和任務交接，再將其建立於現有負責人之下。",
  library: "團隊範本",
  roles: "角色",
  crew: "彈性團隊",
  flow: "循序流程",
  recommended: "適用任務",
  triggers: "啟動主題",
  structure: "團隊結構",
  handoffs: "任務交接",
  noHandoffs: "此團隊尚未定義任務交接。",
  manager: "負責人",
  expert: "專家",
  reportsTo: "彙報對象",
  selectedManager: "所選負責人",
  ai: "AI 分派",
  next: "下一步",
  review: "審查",
  configure: "設定團隊",
  setup: "建立團隊",
  managerHelp: "僅列出具有建立專家權限的活躍負責人。",
  noManagers: "沒有符合資格的負責人。",
  outcome: "首個目標（選填）",
  outcomePlaceholder: "描述希望團隊交付的成果。",
  outcomeHelp: "留空可僅建立團隊，不啟動任務。",
  outcomeInvalid: "請輸入至少 3 個字元，或留空。",
  finite: "單一目標",
  continuous: "持續執行",
  cadence: "重複週期",
  hour: "每小時",
  fourHours: "每 4 小時",
  day: "每天",
  week: "每週",
  scope: "權限受所選負責人的權限範圍限制。",
  approval: "需要核准的操作仍須取得核准。",
  atomic: "團隊成員與選填的首個任務會一併儲存。",
  install: "建立團隊",
  installStart: "建立並啟動",
  installing: "正在建立…",
  installed: "團隊已建立",
  receipt: "建立憑據",
  openTask: "開啟目前任務",
  another: "建立另一個團隊",
  retry: "重試",
  loading: "正在載入團隊工作室",
  loadError: "無法載入團隊或負責人資料。",
  empty: "沒有可用的團隊範本。",
  stale: "部分資料無法重新整理。建立前請查看最新目錄。",
  safetyUnknown: "無法確認安全狀態。建立已暫停。",
  stopped: "緊急停止已開啟，無法建立新團隊。",
  unknown:
    "建立結果不明。請求已儲存在此瀏覽器分頁中。建立另一個團隊前，請先復原此請求的結果。",
  recover: "復原建立結果",
  rejected: "伺服器拒絕了此次建立。請檢查輸入後重試。",
  versionChanged: "範本已變更。請重新整理並檢查新版本。",
  managerChanged: "負責人已不符合資格。請重新整理清單並重新選擇。",
  capacity: "已達專家或任務數量上限。",
} satisfies WorkforceCopy;
