import type { BrowserCopy } from "../browser-copy";
const copy: BrowserCopy = {
  zoomIn: "原始尺寸",
  zoomOut: "符合視窗",
  title: "瀏覽器",
  help: "檢視代理的瀏覽器，接管後即可操作。畫面以定期擷取螢幕的方式更新。",
  address: "網站位址",
  go: "開啟位址",
  addressInvalid: "請輸入不含使用者名稱或密碼的 HTTP 或 HTTPS 位址。",
  take: "接管控制",
  release: "交還控制",
  ownerAgent: "代理正在控制瀏覽器",
  ownerOperator: "您正在控制瀏覽器",
  ownerOther: "操作員控制已啟用；此分頁尚未驗證您的控制權限。",
  agentBusy: "請等待代理目前的瀏覽器操作完成。",
  blocked: "安全控制允許後才能繼續變更瀏覽器。",
  loading: "正在檢查瀏覽器…",
  refresh: "更新畫面",
  pause: "暫停畫面",
  resume: "繼續畫面",
  polling: "畫面定期更新",
  paused: "畫面已暫停 · 輸入已停用",
  syncLost: "無法確認最新畫面。輸入已停用，保留上一次畫面。",
  received: "畫面接收時間",
  empty: "沒有瀏覽器工作階段。請先接管控制，再開啟位址。",
  imageLabel: "瀏覽器畫面",
  frameHelp:
    "點選畫面選擇目標。Tab 將焦點移出畫面；Escape 將焦點移到控制按鈕。使用下方按鈕傳送遠端按鍵。螢幕閱讀器無法透過此畫面讀取遠端網頁內容。",
  textLabel: "傳送到所選遠端欄位的文字",
  textHelp:
    "在畫面中選擇欄位，在此輸入文字後傳送。Enter 新增換行。密碼會在此顯示，完成後請清空草稿。",
  textInvalid:
    "請輸入 1–4096 個 UTF-16 程式碼單元，不得包含 NUL 或不完整的 Unicode 字元。",
  send: "傳送文字",
  busy: "正在等待瀏覽器回應…",
  sent: "瀏覽器操作已確認。",
  unknown: "操作結果未知。",
  unknownHelp:
    "不會自動重試。繼續前請更新畫面並檢查遠端頁面。此本機標記不含文字或位址，也不是伺服器回執。",
  review: "檢查目前畫面",
  reviewCheck: "我已檢查目前頁面，並了解先前的操作可能已經發生。",
  reviewDone: "完成檢查",
  reviewRequired: "傳送新操作前，請先檢查結果未知的操作。",
  error: "要求遭拒。請更新畫面並檢查瀏覽器控制權。",
  close: "關閉瀏覽器",
  closeTitle: "關閉此瀏覽器工作階段？",
  closeHelp: "遠端頁面及其未儲存的資料將被關閉。需要您目前有效的控制權限。",
  cancel: "取消",
  confirm: "關閉工作階段",
  fullscreen: "全螢幕",
  exitFullscreen: "離開全螢幕",
  fullscreenError: "此瀏覽器不支援全螢幕。",
  back: "上一頁",
  forward: "下一頁",
  reload: "重新載入頁面",
  tab: "下一個欄位",
  shiftTab: "上一個欄位",
  enter: "Enter",
  backspace: "退格",
  escape: "退出鍵",
  up: "向上",
  down: "向下",
  left: "向左",
  right: "向右",
  scrollUp: "向上捲動",
  scrollDown: "向下捲動",
  storageError: "本機復原儲存空間無法使用。恢復前無法傳送新操作。",
  retryStorage: "重試本機儲存",
  damaged: "無法讀取本機復原標記。清除前請檢查目前頁面。",
  draftsHint:
    "文字和位址草稿僅保留在此分頁的記憶體中。重新載入或關閉前請先複製。",
  windowVisible: "視窗在主機上可見",
  windowHidden: "瀏覽器在背景執行",
};
copy.unknownHelp += " 操作仍可能稍後完成。";
export default copy;
