import type { BrowserCopy } from "../browser-copy";
const copy: BrowserCopy = {
  zoomIn: "原始尺寸",
  zoomOut: "适应窗口",
  title: "浏览器",
  help: "查看代理的浏览器，接管后即可操作。画面以定期截图的方式更新。",
  address: "网站地址",
  go: "打开地址",
  addressInvalid: "请输入不含用户名或密码的 HTTP 或 HTTPS 地址。",
  take: "接管控制",
  release: "交还控制",
  ownerAgent: "代理正在控制浏览器",
  ownerOperator: "您正在控制浏览器",
  ownerOther: "操作员控制已启用；此标签页尚未验证您的控制权限。",
  agentBusy: "请等待代理当前的浏览器操作完成。",
  blocked: "安全控制允许后才能继续更改浏览器。",
  loading: "正在检查浏览器…",
  refresh: "刷新画面",
  pause: "暂停画面",
  resume: "恢复画面",
  polling: "画面定期更新",
  paused: "画面已暂停 · 输入已禁用",
  syncLost: "无法确认最新画面。输入已禁用，保留上一次画面。",
  received: "画面接收时间",
  empty: "没有浏览器会话。请先接管控制，再打开地址。",
  imageLabel: "浏览器画面",
  frameHelp:
    "点击画面选择目标。Tab 将焦点移出画面；Escape 将焦点移到控制按钮。使用下方按钮发送远程按键。屏幕阅读器无法通过此画面读取远程网页内容。",
  textLabel: "发送到所选远程字段的文本",
  textHelp:
    "在画面中选择字段，在此输入文本后发送。Enter 添加换行。密码会在此显示，完成后请清空草稿。",
  textInvalid:
    "请输入 1–4096 个 UTF-16 代码单元，不得包含 NUL 或不完整的 Unicode 字符。",
  send: "发送文本",
  busy: "正在等待浏览器响应…",
  sent: "浏览器操作已确认。",
  unknown: "操作结果未知。",
  unknownHelp:
    "不会自动重试。继续前请刷新画面并检查远程页面。此本地标记不含文本或地址，也不是服务器回执。",
  review: "检查当前画面",
  reviewCheck: "我已检查当前页面，并了解之前的操作可能已经发生。",
  reviewDone: "完成检查",
  reviewRequired: "发送新操作前，请先检查结果未知的操作。",
  error: "请求被拒绝。请刷新画面并检查浏览器控制权。",
  close: "关闭浏览器",
  closeTitle: "关闭此浏览器会话？",
  closeHelp: "远程页面及其未保存的数据将被关闭。需要您当前有效的控制权限。",
  cancel: "取消",
  confirm: "关闭会话",
  fullscreen: "全屏",
  exitFullscreen: "退出全屏",
  fullscreenError: "此浏览器不支持全屏。",
  back: "后退",
  forward: "前进",
  reload: "重新加载页面",
  tab: "下一个字段",
  shiftTab: "上一个字段",
  enter: "回车",
  backspace: "退格",
  escape: "退出键",
  up: "向上",
  down: "向下",
  left: "向左",
  right: "向右",
  scrollUp: "向上滚动",
  scrollDown: "向下滚动",
  storageError: "本地恢复存储不可用。恢复前无法发送新操作。",
  retryStorage: "重试本地存储",
  damaged: "无法读取本地恢复标记。清除前请检查当前页面。",
  draftsHint:
    "文本和地址草稿仅保留在此标签页的内存中。重新加载或关闭前请先复制。",
  windowVisible: "窗口在主机上可见",
  windowHidden: "浏览器在后台运行",
};
copy.unknownHelp += " 操作仍可能稍后完成。";
export default copy;
