import type { ExpertDetailCopy } from "../expert-detail-copy";
const copy: ExpertDetailCopy = {
  managedPrompt:
    "此预设角色的指令跟随工作区语言。编辑并保存后将成为自定义指令；之后切换语言不会改变您的文本。",
  promptRequired: "保存前请输入工作指令。",
  invalid: "专家地址无效",
  missing: "未找到专家",
  loadError: "无法加载专家",
  loadHelp: "记录暂不可用或已不存在。请返回列表或重试。",
  loading: "正在加载专家…",
  refresh: "刷新记录",
  stale: "当前显示上次加载的记录。更改设置前请先成功刷新。",
  created: "创建时间",
  lastSeen: "最近报告的活动",
  noSignal: "尚无报告",
  noStep: "未报告当前步骤",
  nextModel: "已保存的工作模型",
  changeModel: "更改模型",
  modelHelp:
    "此选项在下一轮选择模型时生效，不会切换已在执行的请求，也不保证提供商可用。",
  save: "保存更改",
  saving: "正在保存…",
  saved: "服务器已确认更改。",
  unknown: "无法确认结果，更改可能已保存。再次提交前请刷新并检查。",
  changed: "专家配置已在别处更改。保存前请刷新并检查最新值。",
  busyError: "此专家有正在执行的轮次时无法更改权限。请等待完成后刷新。",
  capacity: "活跃专家数量已达上限。恢复前请检查团队名单。",
  denied: "服务器拒绝了此更改。请刷新并检查专家权限和模型选择。",
  review: "检查最新值",
  discard: "使用已保存的指令",
  source: "原始存储内容",
  promptHelp:
    "指令引导专家行为，不会授予工具权限。草稿保留在此页面，直到保存或离开。",
  promptChanged:
    "编辑期间，已保存的指令发生了变化。草稿已保留。保存前请与服务器版本比较。",
  permissionsHelp:
    "这是已保存的权限。运行规则和必要的人工审批仍然有效。轮次占用期间无法更改权限。",
  enabled: "已启用",
  disabled: "已禁用",
  hostShell: "根 CEO 主机命令行",
  hostHelp:
    "主机命令仍需精确的一次性人工审批，并需服务器允许主机执行。命令使用服务账户现有的操作系统权限执行，没有沙箱或权限提升。",
  archive: "归档专家",
  archiveTitle: "归档此专家？",
  archiveHelp:
    "这会将专家移出活跃名单，阻止其未完成的工作并撤销这些工作尚未使用的审批权限。记录会保留。若已批准的操作仍在执行，必须等结果入库后才能归档。",
  restore: "恢复专家",
  restoreHelp: "恢复后专家将回到活跃名单。之前被阻止的任务不会自动继续。",
  cancel: "取消",
  active: "活跃名单中",
  archived: "已归档",
  chat: "聊天",
  computer: "计算机",
  tasks: "任务",
  stats: "统计",
  settings: "设置",
  taskLoading: "正在加载已分配任务…",
  taskError: "无法加载已分配任务。",
  taskEmpty: "此专家尚未分配任务。",
  taskWindow: "最多显示最近 200 个已分配任务，可能还有更早的记录。",
  progress: "进度",
  low: "低",
  normal: "普通",
  high: "高",
  urgent: "紧急",
  statsWindow:
    "此样本最多使用最近 200 条活动事件和 200 条消息。这不是历史总量、成功操作数或费用记录。",
  statsError: "统计来源不可用。缺失数据不会被当作零。",
  replies: "样本中的代理回复",
  toolEvents: "终端和文件事件",
  createdTasks: "任务创建事件",
  delegations: "任务委派事件",
  reviews: "审查事件",
  approvalRequests: "审批请求",
  modelUsage: "记录中的模型",
  modelUsageHelp: "最常见的五个模型；条形图显示其占样本代理回复的比例。",
  noModels: "这些回复中没有记录模型标识。",
  recentTools: "最近的终端和文件事件",
  noTools: "此样本中没有终端或文件事件。",
  oldest: "样本中最早的事件",
  records: "活动事件样本数",
  avatar: "头像",
  avatarBuiltin: "内置吉祥物",
  avatarCustom: "自定义头像",
  avatarHelp:
    "支持 PNG、JPEG 或 WebP，最大 5 MB。浏览器在本地裁剪和压缩，再将不超过 64 KB 的副本保存到你自己的服务器。原文件不会发送到图像服务。",
  chooseImage: "选择图像",
  processing: "正在准备…",
  preview: "未保存的预览",
  resetAvatar: "使用内置吉祥物",
  saveAvatar: "保存头像",
  avatarFileError: "请选择不超过 5 MB 的非空 PNG、JPEG 或 WebP 文件。",
  avatarPrepareError:
    "无法准备此图像。请尝试更小的有效图像；最大分辨率为 4000 万像素。",
  avatarChanged: "已保存的头像发生了变化。预览已保留；保存前请刷新并检查。",
  configuration: "已保存的配置",
  configHelp:
    "角色指令描述意图。下列权限与服务器规则和审批共同控制访问。此页面不测量运行健康状况或主机隔离情况。",
  serverPrompt: "查看最新保存的指令",
  busyArchive: "已批准的操作正在执行。请等待结果记录后再归档。",
  readonly: "服务器未提供配置版本。编辑前请刷新。",
  actionTitle: "权限",
  taskMore: "打开所有项目",
};
export default copy;
