import type { ExpertDetailCopy } from "../expert-detail-copy";
const copy: ExpertDetailCopy = {
  managedPrompt:
    "此預設角色的指示會跟隨工作區語言。編輯並儲存後將成為自訂指示；之後切換語言不會變更您的文字。",
  promptRequired: "儲存前請輸入工作指令。",
  invalid: "專家地址無效",
  missing: "找不到專家",
  loadError: "無法載入專家",
  loadHelp: "紀錄暫時無法使用或已不存在。請返回清單或重試。",
  loading: "正在載入專家…",
  refresh: "重新整理紀錄",
  stale: "目前顯示上次載入的紀錄。變更設定前請先成功重新整理。",
  created: "建立時間",
  lastSeen: "最近回報的活動",
  noSignal: "尚無回報",
  noStep: "未回報目前步驟",
  nextModel: "已儲存的工作模型",
  changeModel: "變更模型",
  modelHelp:
    "此選項在下一輪選擇模型時生效，不會切換已在執行的請求，也不保證供應商可用。",
  save: "儲存變更",
  saving: "正在儲存…",
  saved: "伺服器已確認變更。",
  unknown: "無法確認結果，變更可能已儲存。再次提交前請重新整理並檢查。",
  changed: "專家設定已在其他地方變更。儲存前請重新整理並檢查最新值。",
  busyError: "此專家有正在執行的輪次時無法變更權限。請等待完成後重新整理。",
  capacity: "活躍專家數量已達上限。恢復前請檢查團隊名單。",
  denied: "伺服器拒絕了此變更。請重新整理並檢查專家權限和模型選擇。",
  review: "檢查最新值",
  discard: "使用已儲存的指令",
  source: "原始儲存內容",
  promptHelp:
    "指令引導專家行為，不會授予工具權限。草稿保留在此頁面，直到儲存或離開。",
  promptChanged:
    "編輯期間，已儲存的指令發生變更。草稿已保留。儲存前請與伺服器版本比較。",
  permissionsHelp:
    "這是已儲存的權限。執行規則和必要的人工核准仍然有效。輪次占用期間無法變更權限。",
  enabled: "已啟用",
  disabled: "已停用",
  hostShell: "根 CEO 主機命令列",
  hostHelp:
    "主機命令仍需精確的一次性人工核准，並需伺服器允許主機執行。命令使用服務帳戶現有的作業系統權限執行，沒有沙箱或權限提升。",
  archive: "封存專家",
  archiveTitle: "封存此專家？",
  archiveHelp:
    "這會將專家移出活躍名單，阻止其未完成的工作並撤銷這些工作尚未使用的核准權限。紀錄會保留。若已核准的操作仍在執行，必須等結果入庫後才能封存。",
  restore: "恢復專家",
  restoreHelp: "恢復後專家將回到活躍名單。之前被阻止的任務不會自動繼續。",
  cancel: "取消",
  active: "活躍名單中",
  archived: "已封存",
  chat: "聊天",
  computer: "電腦",
  tasks: "任務",
  stats: "統計",
  settings: "設定",
  taskLoading: "正在載入已指派任務…",
  taskError: "無法載入已指派任務。",
  taskEmpty: "此專家尚未指派任務。",
  taskWindow: "最多顯示最近 200 個已指派任務，可能還有更早的紀錄。",
  progress: "進度",
  low: "低",
  normal: "一般",
  high: "高",
  urgent: "緊急",
  statsWindow:
    "此樣本最多使用最近 200 筆活動事件和 200 則訊息。這不是歷史總量、成功操作數或費用紀錄。",
  statsError: "統計來源無法使用。缺失資料不會被當作零。",
  replies: "樣本中的代理回覆",
  toolEvents: "終端機和檔案事件",
  createdTasks: "任務建立事件",
  delegations: "任務委派事件",
  reviews: "審查事件",
  approvalRequests: "核准請求",
  modelUsage: "紀錄中的模型",
  modelUsageHelp: "最常見的五個模型；長條圖顯示其占樣本代理回覆的比例。",
  noModels: "這些回覆中沒有記錄模型識別碼。",
  recentTools: "最近的終端機和檔案事件",
  noTools: "此樣本中沒有終端機或檔案事件。",
  oldest: "樣本中最早的事件",
  records: "活動事件樣本數",
  avatar: "頭像",
  avatarBuiltin: "內建頭像",
  avatarCustom: "自訂頭像",
  avatarHelp:
    "支援 PNG、JPEG 或 WebP，最大 5 MB。瀏覽器在本機裁剪和壓縮，再將不超過 64 KB 的副本儲存到你自己的伺服器。原檔案不會傳送到影像服務。",
  chooseImage: "選擇影像",
  processing: "正在準備…",
  preview: "未儲存的預覽",
  resetAvatar: "使用內建頭像",
  saveAvatar: "儲存頭像",
  avatarFileError: "請選擇不超過 5 MB 的非空 PNG、JPEG 或 WebP 檔案。",
  avatarPrepareError:
    "無法準備此影像。請嘗試較小的有效影像；最大解析度為 4000 萬像素。",
  avatarChanged: "已儲存的頭像發生變更。預覽已保留；儲存前請重新整理並檢查。",
  configuration: "已儲存的設定",
  configHelp:
    "角色指令描述意圖。下列權限與伺服器規則和核准共同控制存取。此頁面不測量執行健康狀況或主機隔離情況。",
  serverPrompt: "查看最新儲存的指令",
  busyArchive: "已核准的操作正在執行。請等待結果記錄後再封存。",
  readonly: "伺服器未提供設定版本。編輯前請重新整理。",
  actionTitle: "權限",
  taskMore: "開啟所有專案",
};
export default copy;
