import type { ComputerCopy } from "../computer-copy";
const copy: ComputerCopy = {
  commandRequired: "請輸入命令。",
  title: "電腦工作區",
  agentLabel: "{name} 的電腦工作區",
  scope: "瀏覽器、命令和檔案屬於此專家的共用工作區。",
  projectScope:
    "這些工具在多個專案之間共用專家的工作區。在此輸入的命令是操作員操作，並非此專案的步驟。",
  source: "原始內容",
  activity: "操作紀錄",
  activityHelp:
    "每頁最多顯示此專家的 20 筆紀錄，可能涉及其他工作。僅最新一頁會自動重新整理。",
  projectActivityHelp:
    "每頁最多顯示依此專案篩選的 20 筆紀錄。此處輸入的操作員指令不限於此專案。",
  activityEmpty: "此範圍內沒有紀錄。",
  activityError: "無法載入操作紀錄。",
  activityStale: "更新失敗。仍顯示先前載入的紀錄。",
  refresh: "重新整理",
  loading: "載入中…",
  ready: "工作區已存在",
  notCreated: "首次使用時建立",
  statusError: "無法驗證工作區狀態。",
  bytes: "已儲存位元組",
  files: "工作檔案",
  folders: "資料夾",
  browser: "瀏覽器",
  terminal: "終端機",
  surfaces: "電腦工具",
  follow: "跟隨新的代理程式事件",
  followHelp: "只在收到新的代理程式事件時切換工具，不會中斷文字輸入。",
  permissionOff: "瀏覽器權限已關閉。",
  terminalHelp:
    "每次請求執行一條命令。路徑受工作區限制，但不提供作業系統層級隔離。",
  hostHelp:
    "主機命令以 API 服務帳戶的作業系統權限執行。伺服器必須明確啟用此模式。",
  host: "主機操作員",
  workspace: "工作區",
  command: "命令",
  run: "執行命令",
  keyboard: "Enter 換行。在非輸入法組字狀態下，Ctrl/Command+Enter 執行命令。",
  tooLong: "命令超過 32,768 個字元。草稿未被截短。",
  disabled: "終端機權限已關閉。",
  blocked: "在安全狀態允許之前，無法傳送命令。",
  cwdLoading: "正在檢查工作目錄…",
  cwdError: "無法驗證工作目錄。執行命令前請先重新整理。",
  folder: "工作目錄",
  running: "請求已傳送，正在等待結果…",
  unconfirmed: "命令結果尚未確認",
  unconfirmedHelp:
    "操作可能已執行，結果仍未確認。 檢查只讀取此請求的紀錄，不會重複執行或取消操作。",
  reviewCheck:
    "我已檢查可能的影響。繼續只會清除此本機警告，不會取消或重複命令。",
  reviewDone: "完成檢查",
  storageError: "此分頁無法儲存復原資料。草稿仍可見，新的命令已被阻止。",
  storageRetry: "重試本機儲存",
  damaged: "已儲存的終端機資料已損壞。清除此本機紀錄前，請檢查先前的命令。",
  localOnly:
    "草稿和最新回覆儲存在此瀏覽器分頁中，重新整理後仍保留。關閉分頁可能將其刪除，不會與手機或其他裝置共用。",
  result: "已記錄的命令回覆",
  output: "命令輸出",
  emptyOutput: "未傳回輸出。",
  copy: "複製輸出",
  copied: "已複製",
  copyError: "複製失敗。可以手動選取輸出。",
  clearOutput: "清除可見輸出",
  reuse: "將命令用作草稿",
  exit: "結束代碼",
  duration: "耗時",
  latest: "最新結果",
  historyHelp: "最多顯示最近 6 筆回覆；僅儲存最新回覆以便重新整理後復原。",
};
export default copy;
