import type { ComputerCopy } from "../computer-copy";
const copy: ComputerCopy = {
  commandRequired: "请输入命令。",
  title: "计算机工作区",
  agentLabel: "{name} 的计算机工作区",
  scope: "浏览器、命令和文件属于此专家的共享工作区。",
  projectScope:
    "这些工具在多个项目之间共享专家的工作区。在此输入的命令是操作员操作，并非此项目的步骤。",
  source: "原始内容",
  activity: "操作记录",
  activityHelp:
    "每页最多显示此专家的 20 条记录，可能涉及其他工作。仅最新一页会自动刷新。",
  projectActivityHelp:
    "每页最多显示按此项目筛选的 20 条记录。此处输入的操作员命令不限定于该项目。",
  activityEmpty: "此范围内没有记录。",
  activityError: "无法加载操作记录。",
  activityStale: "刷新失败。仍显示先前加载的记录。",
  refresh: "刷新",
  loading: "正在加载…",
  ready: "工作区已存在",
  notCreated: "首次使用时创建",
  statusError: "无法验证工作区状态。",
  bytes: "已存储字节",
  files: "工作文件",
  folders: "文件夹",
  browser: "浏览器",
  terminal: "终端",
  surfaces: "计算机工具",
  follow: "跟随新的智能体事件",
  followHelp: "仅在收到新的智能体事件时切换工具，不会中断文字输入。",
  permissionOff: "浏览器权限已关闭。",
  terminalHelp:
    "每次请求执行一条命令。路径受工作区限制，但不提供操作系统级隔离。",
  hostHelp:
    "主机命令以 API 服务账户的操作系统权限运行。服务器必须明确启用此模式。",
  host: "主机操作员",
  workspace: "工作区",
  command: "命令",
  run: "运行命令",
  keyboard: "Enter 换行。在非输入法组字状态下，Ctrl/Command+Enter 运行命令。",
  tooLong: "命令超过 32,768 个字符。草稿未被截短。",
  disabled: "终端权限已关闭。",
  blocked: "在安全状态允许之前，无法发送命令。",
  cwdLoading: "正在检查工作目录…",
  cwdError: "无法验证工作目录。运行命令前请先刷新。",
  folder: "工作目录",
  running: "请求已发送，正在等待结果…",
  unconfirmed: "命令结果尚未确认",
  unconfirmedHelp:
    "操作可能已执行，结果仍未确认。 检查只读取此请求的记录，不会重复执行或取消操作。",
  reviewCheck:
    "我已检查可能的影响。继续只会清除此本地警告，不会取消或重复命令。",
  reviewDone: "完成检查",
  storageError: "此标签页无法保存恢复数据。草稿仍可见，新命令已被阻止。",
  storageRetry: "重试本地保存",
  damaged: "已保存的终端数据已损坏。清除此本地记录前，请检查之前的命令。",
  localOnly:
    "草稿和最新回复保存在此浏览器标签页中，刷新后仍保留。关闭标签页可能将其删除，不会与手机或其他设备共享。",
  result: "已记录的命令回复",
  output: "命令输出",
  emptyOutput: "未返回输出。",
  copy: "复制输出",
  copied: "已复制",
  copyError: "复制失败。可以手动选择输出。",
  clearOutput: "清除可见输出",
  reuse: "将命令用作草稿",
  exit: "退出码",
  duration: "耗时",
  latest: "最新结果",
  historyHelp: "最多显示最近 6 条回复；仅保存最新回复以便刷新后恢复。",
};
export default copy;
