import type { CompanyRoomCopy } from "../company-room-copy";
export default {
  title: "公司聊天室",
  eyebrow: "共享记忆",
  description: "团队的持久对话空间。管理成员、提及专家，并集中记录决策。",
  members: "聊天室成员",
  memberRegion: "公司聊天室成员",
  activeMembers: "活跃成员",
  rosterHelp:
    "成员数量与回复预算分别管理。成员可能正忙，或因没有补充而不回复。",
  openChat: "打开专家对话",
  join: "加入聊天室",
  leave: "移出聊天室",
  inactive: "未启用",
  memberAdded: "已添加成员",
  memberRemoved: "已移出成员",
  memberError: "无法确认成员变更。重试前请刷新列表。",
  rosterError: "无法加载成员列表。",
  rosterStale: "无法刷新成员列表。发送和成员变更已暂停。",
  noAgents: "没有可用专家",
  noMembers: "暂无成员",
  loadingMembers: "正在加载成员",
  loadingMessages: "正在加载消息",
  messagesError: "无法加载聊天室。",
  messagesStale: "正在显示上次加载的对话。发送前请刷新。",
  empty: "聊天室还很安静",
  emptyHelp: "发送消息或使用 @ 提及成员。消息保留已记录的发送者身份。",
  firstMessage: "发送第一条消息",
  retry: "刷新",
  older: "加载更早消息",
  newMessages: "前往最新消息",
  loadedMessages: "已加载消息",
  founder: "操作员",
  agent: "专家",
  roomReply: "聊天室回复",
  projectNote: "项目备注",
  operatorMessage: "操作员消息",
  project: "项目",
  source: "消息和自定义身份保留原始语言。",
  skipped: "回复状态",
  busy: "正在处理其他工作",
  unavailable: "不可用",
  empty_response: "未生成回复",
  model_error: "无法生成回复",
  not_relevant: "没有补充内容",
  not_mentioned: "未被提及",
  budget_guard: "因回复预算而跳过",
  close: "关闭",
  compose: "发送至公司聊天室的消息",
  placeholder: "输入消息；使用 @ 提及成员",
  send: "发送至公司聊天室",
  sending: "正在保存消息并等待回复…",
  mentionMembers: "可提及的聊天室成员",
  removeMention: "移除提及",
  noMatches: "没有匹配的活跃成员",
  mentionedHelp: "只会考虑由你提及的活跃成员进行回复。",
  ambientHelp: "未提及时，成员会评估消息；只有能提供补充的成员才会回复。",
  invalidMention: "提及的成员已退出或更改身份。发送前请检查草稿。",
  stored: "消息已保存",
  storedHelp: "本轮有限回复已结束。被跳过的成员未回复。",
  unconfirmed:
    "消息已保存，但无法确认所有回复。请检查实时对话；恢复不会重新启动回复轮次。",
  unknown: "发送结果不明。请先恢复本次发送，再撰写其他消息。",
  recover: "恢复发送",
  storageError: "浏览器无法保存恢复信息。请腾出会话存储空间后重试。",
  conflict: "此发送标识对应其他内容。请保留草稿，并在重新发送前检查聊天室。",
  invalid: "请求被拒绝。请检查消息和成员。",
  capacity: "已达到聊天室消息上限。",
  stopped: "紧急停止已启用。新消息已暂停，已有发送仍可恢复。",
  safetyUnknown: "无法确认安全状态。新消息已暂停。",
  pendingHelp: "有一条发送等待恢复。其文本、接收成员和语言已固定。",
  newSend: "撰写另一条消息",
} satisfies CompanyRoomCopy;
