import type { CompanyRoomCopy } from "../company-room-copy";
export default {
  title: "公司聊天室",
  eyebrow: "共用記憶",
  description: "團隊的持久對話空間。管理成員、提及專家，並集中記錄決策。",
  members: "聊天室成員",
  memberRegion: "公司聊天室成員",
  activeMembers: "啟用中的成員",
  rosterHelp:
    "成員數量與回覆預算分別管理。成員可能正忙，或因沒有補充而不回覆。",
  openChat: "開啟專家對話",
  join: "加入聊天室",
  leave: "移出聊天室",
  inactive: "未啟用",
  memberAdded: "已新增成員",
  memberRemoved: "已移出成員",
  memberError: "無法確認成員變更。重試前請重新整理清單。",
  rosterError: "無法載入成員清單。",
  rosterStale: "無法更新成員清單。傳送和成員變更已暫停。",
  noAgents: "沒有可用專家",
  noMembers: "尚無成員",
  loadingMembers: "正在載入成員",
  loadingMessages: "正在載入訊息",
  messagesError: "無法載入聊天室。",
  messagesStale: "正在顯示上次載入的對話。傳送前請重新整理。",
  empty: "聊天室還很安靜",
  emptyHelp: "傳送訊息或使用 @ 提及成員。訊息保留已記錄的傳送者身分。",
  firstMessage: "撰寫第一則訊息",
  retry: "重新整理",
  older: "載入更早的訊息",
  newMessages: "前往最新訊息",
  loadedMessages: "已載入訊息",
  founder: "操作員",
  agent: "專家",
  roomReply: "聊天室回覆",
  projectNote: "專案備註",
  operatorMessage: "操作員訊息",
  project: "專案",
  source: "訊息和自訂身分保留原始語言。",
  skipped: "回覆狀態",
  busy: "正在處理其他工作",
  unavailable: "無法使用",
  empty_response: "未產生回覆",
  model_error: "無法產生回覆",
  not_relevant: "沒有補充內容",
  not_mentioned: "未被提及",
  budget_guard: "因回覆預算而略過",
  close: "關閉",
  compose: "傳送至公司聊天室的訊息",
  placeholder: "輸入訊息；使用 @ 提及成員",
  send: "傳送至公司聊天室",
  sending: "正在儲存訊息並等待回覆…",
  mentionMembers: "可提及的聊天室成員",
  removeMention: "移除提及",
  noMatches: "沒有符合的啟用中成員",
  mentionedHelp: "只會考慮由你提及的啟用中成員進行回覆。",
  ambientHelp: "未提及成員時，成員會評估訊息；只有能提供補充的成員才會回覆。",
  invalidMention: "提及的成員已退出或變更身分。傳送前請檢查草稿。",
  stored: "訊息已儲存",
  storedHelp: "本輪有限回覆已結束。被略過的成員未回覆。",
  unconfirmed:
    "訊息已儲存，但無法確認所有回覆。請檢查即時對話；復原不會重新啟動回覆輪次。",
  unknown: "傳送結果不明。請先復原本次傳送，再撰寫其他訊息。",
  recover: "復原傳送",
  storageError: "瀏覽器無法儲存復原資訊。請騰出工作階段儲存空間後重試。",
  conflict: "此傳送識別碼對應其他內容。請保留草稿，並在重新傳送前檢查聊天室。",
  invalid: "要求遭拒。請檢查訊息與成員。",
  capacity: "已達聊天室訊息上限。",
  stopped: "緊急停止已啟用。新訊息已暫停，現有傳送仍可復原。",
  safetyUnknown: "無法確認安全狀態。新訊息已暫停。",
  pendingHelp: "有一則傳送等待復原。其文字、接收成員與語言已固定。",
  newSend: "撰寫另一則訊息",
} satisfies CompanyRoomCopy;
