export default {
  source: [
    "Improve source code",
    "Your agent works in a separate copy. Apply the checked version to the original source, with rollback available.",
    "Source folder",
    "Agent",
    "What should change?",
    "Create working copy",
    "Changes",
    "Inspect",
    "Check commands (JSON)",
    "Run checks",
    "Apply checked version",
    "Roll back",
    "Refresh",
    "Working…",
    "Action completed.",
    "Action could not finish. Refresh the records and inspect the outcome.",
    "No source changes yet.",
    "Restart the installation after applying source changes. This action does not roll back the running application or database migrations.",
    "Each check can take up to 20 minutes. Keep this tab open; if disconnected, refresh the outcome instead of resubmitting.",
    "Latest check output",
    "Status",
    "Choose an agent",
    "Draft",
    "Checking",
    "Checks passed",
    "Applying",
    "Applied",
    "Rolling back",
    "Rolled back",
    "Failed",
    "Outcome unknown",
    "Preparing",
  ],
  policy: [
    "Agent access",
    "Read only",
    "Approval mode",
    "Full access",
    "Custom",
    "File changes",
    "Run commands",
    "Browser actions",
    "Create teams and tasks",
    "Elevated commands",
    "Save",
    "Saving…",
    "Permissions saved.",
    "Permissions could not be loaded or have changed. Refresh and retry.",
    "Refresh",
    "Full access also authorizes eligible queued actions automatically. Agent permissions, operating-system limits and emergency stop still apply.",
    "Inspect and plan. File changes and commands are blocked.",
    "Protected actions use single-use approval.",
  ],
  extensions: [
    "Personal skills and tools",
    "Create new",
    "ID (starts with user-)",
    "Title",
    "Description",
    "Type",
    "Skill",
    "Tool",
    "Instructions",
    "Underlying tool",
    "Fixed inputs (JSON)",
    "Save",
    "Cancel",
    "Edit",
    "Enabled",
    "Disabled",
    "Export",
    "Import JSON",
    "Could not save. Check the input; the latest version was reloaded.",
    "Saved.",
    "Tool packs",
    "Save changes",
    "Data",
    "Documents",
    "Web",
    "Code",
    "Planning",
    "Personal tools run a selected built-in operation with fixed inputs. Skill instructions grant no extra permissions.",
    "No personal capabilities yet.",
  ],
  program: [
    "Executable tool",
    "JavaScript body",
    "This code runs in Node with the service account's file and network access. Terminal permission and single-use approval are required; full access can authorize eligible requests. Read the input object and return the result. Add only code you trust.",
  ],
};
