export default {
  source: [
    "Quellcode verbessern",
    "Dein Agent arbeitet in einer separaten Kopie. Übernimm die geprüfte Version in den ursprünglichen Quellcode und mache sie bei Bedarf rückgängig.",
    "Quellordner",
    "Agent",
    "Was soll sich ändern?",
    "Arbeitskopie erstellen",
    "Änderungen",
    "Prüfen",
    "Prüfbefehle (JSON)",
    "Prüfungen starten",
    "Geprüfte Version übernehmen",
    "Rückgängig machen",
    "Aktualisieren",
    "Wird bearbeitet…",
    "Aktion abgeschlossen.",
    "Aktion nicht abgeschlossen. Aktualisiere die Einträge und prüfe das Ergebnis.",
    "Noch keine Quellcodeänderungen.",
    "Starte die Installation nach der Übernahme neu. Laufende Anwendung und Datenbankmigrationen werden dadurch nicht zurückgesetzt.",
    "Jede Prüfung kann bis zu 20 Minuten dauern. Lass den Tab offen; nach Verbindungsabbruch das Ergebnis aktualisieren, nicht erneut senden.",
    "Letzte Prüfausgabe",
    "Status",
    "Agent auswählen",
    "Entwurf",
    "Wird geprüft",
    "Prüfungen bestanden",
    "Wird übernommen",
    "Übernommen",
    "Wird rückgängig gemacht",
    "Rückgängig gemacht",
    "Fehlgeschlagen",
    "Ergebnis unklar",
    "Wird vorbereitet",
  ],
  policy: [
    "Agentenzugriff",
    "Nur lesen",
    "Mit Genehmigung",
    "Vollzugriff",
    "Benutzerdefiniert",
    "Dateiänderungen",
    "Befehle ausführen",
    "Browseraktionen",
    "Teams und Aufgaben erstellen",
    "Erhöhte Befehle",
    "Speichern",
    "Wird gespeichert…",
    "Berechtigungen gespeichert.",
    "Berechtigungen konnten nicht geladen werden oder wurden geändert. Aktualisieren und erneut versuchen.",
    "Aktualisieren",
    "Vollzugriff genehmigt auch geeignete wartende Aktionen automatisch. Agentenrechte, Betriebssystemgrenzen und Not-Aus gelten weiterhin.",
    "Prüfen und planen. Dateiänderungen und Befehle sind gesperrt.",
    "Geschützte Aktionen benötigen eine einmalige Genehmigung.",
  ],
  extensions: [
    "Persönliche Skills und Werkzeuge",
    "Neu erstellen",
    "ID (beginnt mit user-)",
    "Titel",
    "Beschreibung",
    "Typ",
    "Skill",
    "Werkzeug",
    "Anweisungen",
    "Basiswerkzeug",
    "Feste Eingaben (JSON)",
    "Speichern",
    "Abbrechen",
    "Bearbeiten",
    "Aktiviert",
    "Deaktiviert",
    "Exportieren",
    "JSON importieren",
    "Speichern fehlgeschlagen. Eingaben prüfen; aktuelle Version wurde geladen.",
    "Gespeichert.",
    "Werkzeugpakete",
    "Änderungen speichern",
    "Daten",
    "Dokumente",
    "Web",
    "Code",
    "Planung",
    "Persönliche Werkzeuge führen eine integrierte Operation mit festen Eingaben aus. Skill-Anweisungen gewähren keine zusätzlichen Rechte.",
    "Noch keine persönlichen Erweiterungen.",
  ],
  program: [
    "Ausführbares Werkzeug",
    "JavaScript-Code",
    "Dieser Code läuft in Node mit dem Datei- und Netzwerkzugriff des Dienstkontos. Terminalberechtigung und einmalige Genehmigung sind erforderlich; Vollzugriff kann geeignete Anfragen genehmigen. Lies das input-Objekt und gib das Ergebnis mit return zurück. Füge nur vertrauenswürdigen Code hinzu.",
  ],
};
