export default {
  source: [
    "Kaynak kodunu geliştir",
    "Ajanın ayrı bir kopyada çalışır. Kontroller geçen sürümü asıl kaynağa uygula; gerekirse geri al.",
    "Kaynak klasörü",
    "Ajan",
    "Ne değişsin?",
    "Çalışma kopyası oluştur",
    "Değişiklikler",
    "İncele",
    "Kontrol komutları (JSON)",
    "Kontrolleri çalıştır",
    "Geçen sürümü uygula",
    "Geri al",
    "Yenile",
    "İşlem sürüyor…",
    "İşlem tamamlandı.",
    "İşlem tamamlanamadı. Kayıtları yenile ve sonucu incele.",
    "Henüz kaynak değişikliği yok.",
    "Kaynak uygulandıktan sonra kurulumu yeniden başlat. Bu işlem çalışan uygulamayı veya veritabanı değişikliklerini geri almaz.",
    "Kontroller her biri en fazla 20 dakika sürebilir. Sekmeyi açık tut; bağlantı kesilirse sonucu yenile, işlemi tekrar gönderme.",
    "Son kontrol çıktısı",
    "Durum",
    "Ajan seç",
    "Taslak",
    "Kontrol ediliyor",
    "Kontrol geçti",
    "Uygulanıyor",
    "Uygulandı",
    "Geri alınıyor",
    "Geri alındı",
    "Başarısız",
    "Sonuç belirsiz",
    "Hazırlanıyor",
    "Codex hâlâ çalışıyor veya sürecin temizlendiği doğrulanmadı. Kaynak kontrollerinden önce görevi açıp kodlama oturumunu incele.",
    "Görevi aç",
  ],
  policy: [
    "Ajan erişimi",
    "Salt okunur",
    "Onaylı çalışma",
    "Tam erişim",
    "Özel",
    "Dosya değişiklikleri",
    "Komut çalıştırma",
    "Tarayıcı işlemleri",
    "Ekip ve görev oluşturma",
    "Yükseltilmiş komutlar",
    "Kaydet",
    "Kaydediliyor…",
    "İzinler kaydedildi.",
    "İzinler yüklenemedi veya değişti. Yenile ve yeniden dene.",
    "Yenile",
    "Tam erişim, uygun bekleyen işlemleri de otomatik onaylar. Ajan izinleri, işletim sistemi sınırları ve acil durdurma geçerliliğini korur.",
    "İnceleme ve planlama yapılabilir. Dosya değişiklikleri ve komutlar engellenir.",
    "Korunan işlemler tek kullanımlık onayla yürütülür.",
  ],
  extensions: [
    "Kişisel skill ve araçlar",
    "Yeni oluştur",
    "Kimlik (user- ile başlar)",
    "Başlık",
    "Açıklama",
    "Tür",
    "Skill",
    "Araç",
    "Talimatlar",
    "Temel araç",
    "Sabit girdiler (JSON)",
    "Kaydet",
    "İptal",
    "Düzenle",
    "Etkin",
    "Devre dışı",
    "Dışa aktar",
    "JSON içe aktar",
    "Kaydedilemedi. Bilgileri kontrol et; güncel sürüm yeniden yüklendi.",
    "Kaydedildi.",
    "Araç paketleri",
    "Değişiklikleri kaydet",
    "Veri",
    "Belgeler",
    "Web",
    "Kod",
    "Planlama",
    "Kişisel araçlar, seçtiğin yerleşik işlemi sabit girdilerle çalıştırır. Skill talimatları ek yetki vermez.",
    "Henüz kişisel araç yok.",
  ],
  program: [
    "Çalışan araç",
    "JavaScript gövdesi",
    "Bu kod Node ile çalışır ve servis hesabının dosya/ağ erişimini kullanabilir. Terminal izni ve tek kullanımlık onay gerekir; tam erişim modu uygun istekleri onaylayabilir. Girdi input nesnesidir; sonucu return ile döndür. Yalnız güvendiğin kodu ekle.",
  ],
};
