import type { FileCopy } from "../file-copy";
const copy: FileCopy = {
  filesTitle: "工作區檔案",
  filesHelp: "這些檔案由此專家的各個專案共用。儲存前請檢查目前版本。",
  root: "工作區根目錄",
  openFile: "開啟檔案",
  openFolder: "開啟資料夾",
  newFile: "新增檔案",
  refreshFiles: "重新整理檔案清單",
  loadingFiles: "正在載入檔案…",
  listError: "無法載入目錄。",
  listStale: "重新整理失敗。仍顯示上次載入的目錄。",
  partialList:
    "此清單不完整。最多檢查 2,000 個項目，不支援或無法讀取的項目可能省略。",
  emptyList: "此目錄為空。",
  entriesLabel: "顯示的項目",
  pathLabel: "相對檔案路徑",
  pathHelp: "使用 / 分隔資料夾。新增檔案不會取代既有檔案。",
  pathInvalid:
    "請輸入最多 2,048 個字元的相對路徑，不含空白路徑段、. 或 ..、反斜線或前後空格。",
  create: "建立",
  fileCreated: "伺服器已確認建立檔案。",
  contentLabel: "{name} 的內容",
  save: "儲存",
  close: "關閉",
  readError: "無法讀取檔案。你的草稿仍會保留。",
  reading: "正在讀取檔案…",
  readonly: "僅供預覽。無法在此儲存截斷的檔案、二進位檔案或不支援的檔案。",
  contentInvalid:
    "請使用不含 NUL 字元且不超過 128 KiB 的完整 UTF-8 文字。草稿並未縮短。",
  snapshotHint: "你正在編輯快照。儲存時，伺服器會再次檢查版本。",
  saved: "伺服器已確認儲存內容。",
  draftsTitle: "此分頁中的草稿",
  resumeDraft: "繼續編輯草稿",
  discardDraft: "捨棄草稿",
  discardTitle: "捨棄此本機草稿？",
  discardBody: "這會移除本機草稿，不會復原或取消伺服器上的寫入。",
  discardConfirm: "捨棄本機草稿",
  reviewTitle: "檢查檔案版本",
  reviewHelp: "草稿仍會保留。再次儲存前，請與伺服器上的目前檔案比較。",
  compare: "比較目前檔案",
  comparisonLabel: "伺服器上的目前內容",
  comparisonError: "無法讀取目前檔案。草稿仍會保留，檢查尚未完成。",
  reviewCheck: "我已檢查目前內容。下次儲存時，我的草稿可以取代此版本。",
  reviewDone: "完成檢查",
  writeUnknown: "寫入結果尚未確認",
  writeUnknownHelp:
    "請求可能已修改檔案。清除本機警告前，請檢查目前內容與伺服器活動。清除警告不會重送或取消請求。",
  writePending: "請求已傳送，正在等待檔案回應…",
  reviewRequest: "檢查先前的寫入",
  missingFile: "檔案目前不存在。這無法證明先前的請求是否曾執行。",
  fileStorageError:
    "此分頁無法儲存復原資料。離開前請保留或複製可見草稿。新的寫入已遭阻擋。",
  fileDamaged:
    "已儲存的檔案資料損毀。清除本機資料前，請檢查先前操作的影響並複製可見草稿。",
  fileResetCheck:
    "我已檢查先前操作的影響並複製所需草稿。清除此分頁中的檔案草稿與寫入警告。",
  fileReset: "清除本機檔案資料",
  fileLocalOnly:
    "草稿與待處理的寫入保存在此瀏覽器分頁中，重新整理後仍會保留。關閉分頁可能導致遺失，且不會與其他裝置共用。",
  fileBlocked: "安全狀態允許後才能修改檔案。",
  title: "檢查刪除範圍",
  remove: "刪除",
  help: "清單中的所有項目都將永久刪除。範圍變更時必須重新檢查。請避免其他程式修改這些檔案。",
  inspect: "檢查目前範圍",
  inspecting: "正在檢查…",
  scope: "完整刪除清單",
  count: "項目數（含目標本身）",
  bytes: "檔案位元組數",
  file: "檔案",
  folder: "資料夾",
  confirm: "我已檢查完整範圍，並了解刪除後無法復原。",
  submit: "刪除已檢查的項目",
  pending: "正在等待刪除回應…",
  cancel: "取消",
  success: "伺服器已確認刪除。",
  unknown: "刪除結果尚未確認",
  unknownHelp:
    "請求可能已刪除部分或全部目標。請檢查目前的檔案與伺服器活動。收到錯誤不代表內容已保留。",
  missing: "目標目前不存在。這無法證明由誰刪除，也無法證明先前的請求已完成。",
  error: "無法檢查範圍。請檢查連線、權限，以及檔案是否仍在變動。",
  limited:
    "無法在此檢查此範圍：可能含有連結或特殊檔案，或超過 1,000 個項目、64 MiB、32 層目錄或檢查時間限制。請在伺服器上管理。",
  changed: "範圍已變更。請重新檢查後再確認刪除。",
  storageError: "此分頁無法儲存復原資料。不會傳送新的刪除請求。",
  damaged: "已儲存的刪除資料損毀。清除此本機紀錄前，請檢查先前操作的影響。",
  clearConfirm: "我已檢查可能的影響。清除此警告不會取消或重送伺服器請求。",
  clear: "清除本機警告",
  recover: "檢查先前的刪除",
  localOnly:
    "復原資料儲存在此瀏覽器分頁。關閉分頁可能會遺失資料，且不會與其他裝置共用。",
  storageRetry: "重試本機儲存",
  blocked: "安全狀態允許後才能刪除。",
  required: "刪除前請確認已檢查的範圍。",
};
export default copy;
