import type { FileCopy } from "../file-copy";
const copy: FileCopy = {
  filesTitle: "工作区文件",
  filesHelp: "这些文件由该专家的各个项目共用。保存前请检查当前版本。",
  root: "工作区根目录",
  openFile: "打开文件",
  openFolder: "打开文件夹",
  newFile: "新建文件",
  refreshFiles: "刷新文件列表",
  loadingFiles: "正在加载文件…",
  listError: "无法加载目录。",
  listStale: "刷新失败。仍显示上次加载的目录。",
  partialList:
    "此列表不完整。最多检查 2,000 个项目，不受支持或无法读取的项目可能被省略。",
  emptyList: "此目录为空。",
  entriesLabel: "显示的项目",
  pathLabel: "相对文件路径",
  pathHelp: "使用 / 分隔文件夹。新建文件不会替换已有文件。",
  pathInvalid:
    "请输入最多 2,048 个字符的相对路径，不包含空白路径段、. 或 ..、反斜杠或首尾空格。",
  create: "创建",
  fileCreated: "服务器已确认创建文件。",
  contentLabel: "{name} 的内容",
  save: "保存",
  close: "关闭",
  readError: "无法读取文件。你的草稿仍被保留。",
  reading: "正在读取文件…",
  readonly: "仅供预览。无法在此保存被截断的文件、二进制文件或不受支持的文件。",
  contentInvalid:
    "请使用不含 NUL 字符且不超过 128 KiB 的完整 UTF-8 文本。草稿未被缩短。",
  snapshotHint: "你正在编辑一个快照。保存时，服务器会再次检查版本。",
  saved: "服务器已确认保存内容。",
  draftsTitle: "此标签页中的草稿",
  resumeDraft: "继续编辑草稿",
  discardDraft: "丢弃草稿",
  discardTitle: "丢弃此本地草稿？",
  discardBody: "这会移除本地草稿，不会撤销或取消服务器上的写入。",
  discardConfirm: "丢弃本地草稿",
  reviewTitle: "检查文件版本",
  reviewHelp: "草稿仍被保留。再次保存前，请与服务器上的当前文件比较。",
  compare: "比较当前文件",
  comparisonLabel: "服务器上的当前内容",
  comparisonError: "无法读取当前文件。草稿仍被保留，检查尚未完成。",
  reviewCheck: "我已检查当前内容。下次保存时，我的草稿可以替换此版本。",
  reviewDone: "完成检查",
  writeUnknown: "写入结果尚未确认",
  writeUnknownHelp:
    "请求可能已修改文件。清除本地警告前，请检查当前内容和服务器活动。清除警告不会重发或取消请求。",
  writePending: "请求已发送，正在等待文件响应…",
  reviewRequest: "检查之前的写入",
  missingFile: "文件目前不存在。这无法证明之前的请求是否曾执行。",
  fileStorageError:
    "此标签页无法保存恢复数据。离开前请保留或复制可见的草稿。新的写入已被阻止。",
  fileDamaged:
    "已保存的文件数据损坏。清除本地数据前，请检查之前操作的影响并复制可见草稿。",
  fileResetCheck:
    "我已检查之前操作的影响并复制所需草稿。清除此标签页中的文件草稿和写入警告。",
  fileReset: "清除本地文件数据",
  fileLocalOnly:
    "草稿和待处理的写入保存在此浏览器标签页中，刷新后仍保留。关闭标签页可能导致丢失，且不会与其他设备共享。",
  fileBlocked: "安全状态允许后才能修改文件。",
  title: "检查删除范围",
  remove: "删除",
  help: "列表中的所有项目都将被永久删除。范围发生变化时必须重新检查。请阻止其他程序修改这些文件。",
  inspect: "检查当前范围",
  inspecting: "正在检查…",
  scope: "完整删除列表",
  count: "项目数（含目标本身）",
  bytes: "文件字节数",
  file: "文件",
  folder: "文件夹",
  confirm: "我已检查完整范围，并理解删除后无法撤销。",
  submit: "删除已检查的项目",
  pending: "正在等待删除响应…",
  cancel: "取消",
  success: "服务器已确认删除。",
  unknown: "删除结果尚未确认",
  unknownHelp:
    "请求可能已删除部分或全部目标。请检查当前文件和服务器活动。收到错误不代表内容已被保留。",
  missing: "目标目前不存在。这无法证明由谁删除，也无法证明之前的请求已完成。",
  error: "无法检查范围。请检查连接、权限以及文件是否仍在变化。",
  limited:
    "无法在此检查该范围：可能包含链接或特殊文件，或超过 1,000 个项目、64 MiB、32 层目录或检查时间限制。请在服务器上管理。",
  changed: "范围已发生变化。请重新检查后再确认删除。",
  storageError: "此标签页无法保存恢复数据。不会发送新的删除请求。",
  damaged: "已保存的删除数据损坏。清除此本地记录前，请检查之前操作的影响。",
  clearConfirm: "我已检查可能的影响。清除此警告不会取消或重发服务器请求。",
  clear: "清除本地警告",
  recover: "检查之前的删除",
  localOnly:
    "恢复数据保存在此浏览器标签页中。关闭标签页可能会丢失数据，且不会与其他设备共享。",
  storageRetry: "重试本地保存",
  blocked: "安全状态允许后才能删除。",
  required: "删除前请确认已检查的范围。",
};
export default copy;
