import type { ExpertChatCopy } from "../expert-chat-copy";
export default {
  projectTitle: "项目对话",
  projectHelp:
    "消息和近期上下文关联到此项目及其协调者。现有工具权限和审批要求仍然适用。",
  projectPrompt: "查看此项目的目标并提出下一步建议。",
  projectUnavailable: "此项目不可用或协调者已更改。发送新请求前请刷新项目。",
  required: "请输入消息。",
  title: "对话",
  help: "向此专家提问或安排工作。工具权限和审批仍然有效。",
  history: "对话历史",
  empty: "开始对话",
  emptyHelp: "消息保存在服务器上。模型接收近期上下文，并不拥有无限记忆。",
  loading: "正在加载消息…",
  historyError: "无法加载对话历史。",
  historyStale: "无法刷新历史。仍显示上次加载的消息。",
  refresh: "刷新历史",
  older: "加载更早的消息",
  olderError: "无法加载更早的消息。当前视图已保留。",
  windowLimit: "最多同时显示 500 条消息。返回最新消息以跟进新动态。",
  latest: "查看最新消息",
  newMessages: "有新消息",
  you: "你",
  system: "系统记录",
  model: "记录的模型",
  copy: "复制消息",
  copied: "已复制",
  copyError: "复制失败。请选择消息文本进行复制。",
  unsafeLink: "已阻止不安全链接",
  mode: "请求类型",
  ask: "提问",
  delegate: "分配工作",
  continuous: "持续职责",
  askHelp: "进行一轮对话；专家可以使用获准的工具。",
  delegateHelp: "创建具有明确结果的项目并加入队列。排队中的工作不一定已开始。",
  continuousHelp: "创建每小时重复的工作并加入队列。执行取决于工作进程和审批。",
  instruction: "消息或工作说明",
  placeholder: "描述问题或你需要的结果…",
  send: "发送请求",
  keyboard: "Enter 换行。Ctrl/⌘ + Enter 发送。",
  tooLong: "文本超出所选请求类型的长度限制。",
  blocked: "安全状态允许前，新工作暂停。你仍可编写内容并阅读已保存的结果。",
  unavailable: "发送前请刷新并检查专家设置。已归档的专家无法开始新工作。",
  draftLocal: "未发送的文本保存在此浏览器标签页中。关闭标签页后可能丢失。",
  storageError:
    "无法保存或清除此标签页的本地记录。请备份文本；存储恢复前无法发送。",
  sending: "正在等待服务器…",
  unconfirmed: "结果尚未确认",
  unconfirmedHelp: "请求可能仍在运行，也可能已经停止。检查记录不会重新执行。",
  check: "检查已保存的结果",
  checking: "正在检查…",
  missing: "尚未找到已保存的结果。已发送的请求仍可能到达服务器。",
  recover: "恢复同一请求",
  recoverHelp:
    "使用原始标识和设置。如果服务器从未记录过此请求，可将保存的请求启动一次。",
  readError: "无法读取已保存的结果。请保留此请求标识并再次检查。",
  rejected: "请求在开始执行前被拒绝。",
  configChanged: "专家设置已更改。创建新请求前请刷新并检查。",
  busy: "专家正在工作。此请求未被接受。",
  capacity: "已达到工作区容量上限。创建新请求前请检查现有工作。",
  invalid: "服务器无法接受此请求。请检查原始文本和选项。",
  conflict: "此标识与已保存的请求不匹配。继续前请检查记录。",
  receipt: "发送记录",
  done: "回复已保存",
  queued: "项目已加入队列",
  systemResult: "本轮以系统通知结束",
  project: "打开项目",
  operations: "打开运行管理",
  continue: "继续",
  review: "继续前检查",
  reviewHelp:
    "清除此标签页的待处理记录不会取消服务器上的工作。新请求可能重复操作。请先检查历史、项目和工具记录。",
  acknowledge: "我已检查记录，并理解新请求可能重复操作。",
  cancel: "取消",
  activity: "最近记录的动态",
  activityHelp:
    "此专家最近的 12 个事件。它们可能属于其他工作，不能证明本请求正在运行或已完成。",
  activityEmpty: "没有近期动态记录。",
  activityError: "无法刷新动态。显示的记录可能已过时。",
  source: "原始记录文本",
  prompt: "描述你的角色、能力和限制。",
} satisfies ExpertChatCopy;
