import type { ExpertChatCopy } from "../expert-chat-copy";
export default {
  projectTitle: "專案對話",
  projectHelp:
    "訊息與近期脈絡會連結至此專案及其協調者。現有工具權限與核准要求仍然適用。",
  projectPrompt: "檢視此專案的目標並提出下一步建議。",
  projectUnavailable:
    "此專案無法使用或協調者已變更。傳送新請求前請重新整理專案。",
  required: "請輸入訊息。",
  title: "對話",
  help: "向此專家提問或安排工作。工具權限和核准仍然有效。",
  history: "對話紀錄",
  empty: "開始對話",
  emptyHelp: "訊息儲存在伺服器上。模型接收近期上下文，並不具備無限記憶。",
  loading: "正在載入訊息…",
  historyError: "無法載入對話紀錄。",
  historyStale: "無法更新紀錄。仍顯示上次載入的訊息。",
  refresh: "更新紀錄",
  older: "載入更早的訊息",
  olderError: "無法載入更早的訊息。目前畫面已保留。",
  windowLimit: "最多同時顯示 500 則訊息。返回最新訊息以追蹤新動態。",
  latest: "查看最新訊息",
  newMessages: "有新訊息",
  you: "你",
  system: "系統紀錄",
  model: "記錄的模型",
  copy: "複製訊息",
  copied: "已複製",
  copyError: "複製失敗。請選取訊息文字進行複製。",
  unsafeLink: "已封鎖不安全的連結",
  mode: "請求類型",
  ask: "提問",
  delegate: "分配工作",
  continuous: "持續職責",
  askHelp: "進行一回合對話；專家可以使用獲准的工具。",
  delegateHelp: "建立具有明確成果的專案並加入佇列。排隊中的工作不一定已開始。",
  continuousHelp: "建立每小時重複的工作並加入佇列。執行取決於工作程序和核准。",
  instruction: "訊息或工作說明",
  placeholder: "描述問題或你需要的結果…",
  send: "傳送請求",
  keyboard: "Enter 換行。Ctrl/⌘ + Enter 傳送。",
  tooLong: "文字超出所選請求類型的長度限制。",
  blocked: "安全狀態允許前，新工作暫停。你仍可撰寫內容並閱讀已儲存的結果。",
  unavailable: "傳送前請更新並檢查專家設定。已封存的專家無法開始新工作。",
  draftLocal: "未傳送的文字保存在此瀏覽器分頁中。關閉分頁後可能遺失。",
  storageError:
    "無法儲存或清除此分頁的本機紀錄。請備份文字；儲存功能恢復前無法傳送。",
  sending: "正在等待伺服器…",
  unconfirmed: "結果尚未確認",
  unconfirmedHelp: "請求可能仍在執行，也可能已經停止。檢查紀錄不會重新執行。",
  check: "檢查已儲存的結果",
  checking: "正在檢查…",
  missing: "尚未找到已儲存的結果。已傳送的請求仍可能抵達伺服器。",
  recover: "復原同一請求",
  recoverHelp:
    "使用原始識別碼和設定。如果伺服器從未記錄此請求，可將儲存的請求啟動一次。",
  readError: "無法讀取已儲存的結果。請保留此請求識別碼並再次檢查。",
  rejected: "請求在開始執行前遭拒絕。",
  configChanged: "專家設定已變更。建立新請求前請更新並檢查。",
  busy: "專家正在工作。此請求未被接受。",
  capacity: "已達工作區容量上限。建立新請求前請檢查現有工作。",
  invalid: "伺服器無法接受此請求。請檢查原始文字和選項。",
  conflict: "此識別碼與已儲存的請求不符。繼續前請檢查紀錄。",
  receipt: "傳送紀錄",
  done: "回覆已儲存",
  queued: "專案已加入佇列",
  systemResult: "本回合以系統通知結束",
  project: "開啟專案",
  operations: "開啟執行管理",
  continue: "繼續",
  review: "繼續前檢查",
  reviewHelp:
    "清除此分頁的待處理紀錄不會取消伺服器上的工作。新請求可能重複操作。請先檢查歷史、專案和工具紀錄。",
  acknowledge: "我已檢查紀錄，並理解新請求可能重複操作。",
  cancel: "取消",
  activity: "最近記錄的動態",
  activityHelp:
    "此專家最近的 12 個事件。它們可能屬於其他工作，不能證明本請求正在執行或已完成。",
  activityEmpty: "沒有近期動態紀錄。",
  activityError: "無法更新動態。顯示的紀錄可能已過時。",
  source: "原始紀錄文字",
  prompt: "描述你的角色、能力和限制。",
} satisfies ExpertChatCopy;
